### ISSUE TITLE
Explicit import results in `unexpected character '#'`

### ISSUE THREAD

**Issue by smeijer** [google/zx#100]
## Expected Behavior
Explicit import should work, as mentioned in [readme](https://github.com/google/zx#importing-from-other-scripts).

## Actual Behavior
Explicit import doesn't work. It throws:

> Error: Module parse failed: Unexpected character '#' (138:2)

## Steps to Reproduce the Problem

1. Create `index.ts`
    ```ts
    import { $ } from 'zx'
    await $`date`
    ```

2. Run the file
    ```shell
    ncc run src/index.ts
    ```

## Specifications

- Version: 1.8.0
- Platform: Ubuntu

**Comment by antonmedv** [comment]
Can’t reproduce.

**Comment by Dunky13** [comment]
I'm facing a similar issue, but when trying to run `npx @vercel/ncc build src/index.ts`

```sh
Need to install the following packages:
  @vercel/ncc
Ok to proceed? (y)
ncc: Version 0.28.5
ncc: Compiling file index.js
ncc: Using typescript@4.2.4 (local user-provided)
Error: Module parse failed: Unexpected character '#' (138:2)
File was processed with these loaders:
 * ../../../.npm/_npx/7a71fb44c9115061/node_modules/@vercel/ncc/dist/ncc/loaders/empty-loader.js
 * ../../../.npm/_npx/7a71fb44c9115061/node_modules/@vercel/ncc/dist/ncc/loaders/relocate-loader.js
 * ../../../.npm/_npx/7a71fb44c9115061/node_modules/@vercel/ncc/dist/ncc/loaders/shebang-loader.js
You may need an additional loader to handle the result of these loaders.
|
| export class ProcessOutput {
>   #code = 0
|   #stdout = ''
|   #stderr = ''
```

**Comment by FarazzShaikh** [comment]
The [private class field](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Classes/Private_class_fields) syntax is new and may not be supported by ncc just yet.
