### ISSUE TITLE
`fs.exists` support

### ISSUE THREAD

**Issue by possibilities** [google/zx#104]
Would be great to have access to fs.exists. Maybe existsSync can be exported as fs.exists wrapped in a Promise just to keep the API consistent?

**Comment by antonmedv** [comment]
> Deprecated: Use fs.stat() or fs.access() instead.

**Comment by possibilities** [comment]
Got it thanks!

**Comment by Francesco-Lanciana** [comment]
@antonmedv If I try to use `fs.accessSync` it throws an error, saying that `TypeError: fs.accessSync is not a function`. Any idea why?

**Comment by antonmedv** [comment]
Use async version
