### ISSUE TITLE
Adding more Examples

### ISSUE THREAD

**Issue by Siddhant-K-code** [google/zx#108]
I wanted to work on adding more examples under https://github.com/google/zx/tree/main/examples

I have created a [small repo.](https://github.com/Siddhant-K-code/zx-examples) for this, so I can add those examples + some more interesting examples here. 

Can I work on this?

**Comment by antonmedv** [comment]
I think you need to work more on examples. Right now it is not much.

**Comment by Siddhant-K-code** [comment]
I will try to add more and more, then I will make a PR here for the same.
