### ISSUE TITLE
Enhancement: use git-flow branching model

### ISSUE THREAD

**Issue by FlamingTuri** [google/zx#109]
I suggest adopting git-flow workflow ([link1](https://danielkummer.github.io/git-flow-cheatsheet/) and [link2](https://www.atlassian.com/git/tutorials/comparing-workflows/gitflow-workflow) are nice tutorials that explain what to do), starting by adding a `develop` branch to the repo.
Things like CI/CD or test related improvements (i.e. 1.7.x tags) should not trigger a new zx release in my opinion. Moreover, if a change breaks for any reason a test, it would at most stay on `develop` branch instead of being directly pushed on `main` one. Finally, this introduction would give more control on which features will reach `main` branch and which ones will instead stay on `develop` branch for further assessments.

**Comment by antonmedv** [comment]
I more like https://guides.github.com/introduction/flow/

**Comment by FlamingTuri** [comment]
The approach you linked is what I would apply to `develop` branch. It works fine if the changes to merge always introduce new features or fix an existing bug and should be introduced in a new release. However, in this way even a typo fix in the readme or in an internal variable/function would cause a version upgrade, but would not bring any actual improvement for the ones using zx. 
Maybe it is just me that I am eager to know what has been introduced in the latest release and I feel a bit disappointed when I discover that the changes were "only" mantainance :sweat_smile:

Anyways, I do not want to impose my point of view, I understand that at the moment there are other priorities and there is no need to introduce additional overhead.

**Comment by antonmedv** [comment]
> this way even a typo fix in the readme 

Why? We have a bunch of typo fixes without a new release.

> in an internal variable/function would cause a version upgrade

Again why?

**Comment by FlamingTuri** [comment]
My bad, seeing the `npm-publish.yml` script name I assumed that each time a branch would be merged into `main` a github action would trigger, creating a new tag and then publishing to npm repository. Instead, as it is now, the release tag is generated manually on main and then the publish action is triggered afterwards. My assumptions were also influenced by the idea I had of the git-flow strategy.

**Comment by antonmedv** [comment]
No problem. Feel free to suggest any improvments.
