### ISSUE TITLE
Feature suggestion: include shelljs

### ISSUE THREAD

**Issue by rattrayalex** [google/zx#11]
I really love that you include a bunch of handy, commonly-used packages without any need to `require()` them!

I think it'd also be extremely handy to include all of [shelljs](https://github.com/shelljs/shelljs) too, so you can write this:

```js
if (!which('git')) {
  echo('Sorry, this script requires git');
  exit(1);
}

// Copy files to release dir
rm('-rf', 'out/Release');
cp('-R', 'stuff/', 'out/Release');

// Replace macros in each .js file
cd('lib');
ls('*.js').forEach(function (file) {
  sed('-i', 'BUILD_VERSION', 'v0.1.2', file);
  sed('-i', /^.*REMOVE_THIS_LINE.*$/, '', file);
  sed('-i', /.*REPLACE_LINE_WITH_MACRO.*\n/, cat('macro.js'), file);
});
cd('..');

// Run external tool synchronously
if (shell.exec('git commit -am "Auto-commit"').code !== 0) {
  echo('Error: Git commit failed');
  exit(1);
}
```

Instead of this:
```js
var shell = require('shelljs');

if (!shell.which('git')) {
  shell.echo('Sorry, this script requires git');
  shell.exit(1);
}

// Copy files to release dir
shell.rm('-rf', 'out/Release');
shell.cp('-R', 'stuff/', 'out/Release');

// Replace macros in each .js file
shell.cd('lib');
shell.ls('*.js').forEach(function (file) {
  shell.sed('-i', 'BUILD_VERSION', 'v0.1.2', file);
  shell.sed('-i', /^.*REMOVE_THIS_LINE.*$/, '', file);
  shell.sed('-i', /.*REPLACE_LINE_WITH_MACRO.*\n/, shell.cat('macro.js'), file);
});
shell.cd('..');

// Run external tool synchronously
if (shell.exec('git commit -am "Auto-commit"').code !== 0) {
  shell.echo('Error: Git commit failed');
  shell.exit(1);
}
```

The `` await $`foo ${arg}` `` syntax is definitely great too and I'm excited to use it as well, but for many of these commonly-used commands, synchronous js-native functions would be handy too – especially with escaping/quoting challenges (eg, I love that you can use a JS regex with sed in shelljs, and I'm not sure how that'd translate directly into `` $`cmd` `` syntax).

**Comment by kapouer** [comment]
Note that adding more dependencies makes the tool less simple to maintain and distribute,
which is a nice thing to keep in mind if "xz" is meant to be some kind of "shell" alternative.
I have debian in mind of course - where the situation is actually pretty good, only "shq" needs to be packaged,
and "shelljs" has already all its dependencies packaged (maybe more work is required for the tests suites).

**Comment by rattrayalex** [comment]
I think shelljs seems to be implemented in pure JS (for example, [`echo` is basically `process.stdout.write`](https://github.com/shelljs/shelljs/blob/master/src/echo.js#L57)) so it's portable across platforms.

I would _hope_ that adding a library like it would be very simple to maintain; just something like this:

```js
import shell from shelljs;

const {sed, cp, ls, rm, which, /*etc*/} = shell;
export {
  shell,
  
  sed,
  cp,
  ls,
  rm,
  which,
  /*etc*/
}
```

I do predict some slightly tricky questions around whether to use shelljs's implementation of `cd` or keep the current one, and of course you'd have to document that you need to use `shell.exec()` to access that functionality instead of just `exec()` (since it'd conflict with the evil builtin function). There may be other conflicts or difficulties I'm not thinking of.

If shelljs were included, it might also be worth considering using it under the hood for `` $`cmd` ``, since it returns the nice `ShellString` response with `.code`, `.stdout`, `.stderr`, but that would not need to happen right away by any means.

Worth noting that shelljs is 211kb unpackaged according to npm (probably fine for the use-case, but much larger than `zx`s current 24kb) and gets almost 7mm downloads/wk, indicating it's very widely used for this purpose.

**Comment by antonmedv** [comment]
Including shelljs isn't planned for zx.
It can be easily done on user side: 
```
require('shelljs/global');
```
