### ISSUE TITLE
Support ts-node

### ISSUE THREAD

**Issue by korosuke613** [google/zx#110]
In zx@1.2.2, I could use zx with ts-node. So it easy to debug with JetBrains IDE and other tools. However, in zx@1.10.1, it is no longer possible to run using ts-node.

## Expected Behavior
use zx@1.2.2
```
❯ npm ls zx                  
throw-issues@ /Users/korosuke613/ghq/github.com/korosuke613/playground/zx/throw-issues
└── zx@1.2.2

❯ node --loader ts-node/esm echo.ts
(node:45900) ExperimentalWarning: --experimental-loader is an experimental feature. This feature could change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
$ echo Hello!
Hello!
```

## Actual Behavior
use zx@1.10.1
```
❯ npm ls zx      
throw-issues@ /Users/korosuke613/ghq/github.com/korosuke613/playground/zx/throw-issues
└── zx@1.10.1

❯ node --loader ts-node/esm echo.ts                    
(node:44584) ExperimentalWarning: --experimental-loader is an experimental feature. This feature could change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
ReferenceError: $ is not defined
    at file:///Users/korosuke613/ghq/github.com/korosuke613/playground/zx/throw-issues/echo.ts:3:1
    at ModuleJob.run (internal/modules/esm/module_job.js:152:23)
    at Loader.import (internal/modules/esm/loader.js:166:24)
    at Object.loadESM (internal/process/esm_loader.js:68:5)
```

## Steps to Reproduce the Problem

1. Prepare the following files. ([ref](https://github.com/korosuke613/playground/tree/57eeff51770c452a207493ce1fb177e4a6acea93/zx/throw-issues))

echo.ts
```ts
import { $ } from "zx"

await $`echo Hello!`
```

tsconfig.json
```json
{
  "compilerOptions": {
    "target": "ESNext",
    "module": "ESNext",
    "moduleResolution": "node",
  }
}
```

package.json
```json
{
  "type": "module",
  "dependencies": {
    "zx": "^1.10.1"
  },
  "devDependencies": {
    "ts-node": "^9.1.1"
  }
}
```

2. `npm install`
3. `node --loader ts-node/esm echo.ts`

## Specifications

- Version
  - node: 14.16.1
  - npm: 7.11.2
  - typescript: 4.2.4
  - zx: 1.10.1
- Platform: macOS 11.3 (20E232)

**Comment by antongolub** [comment]
@korosuke613, you dont need to import `$` from `zx`. It's global var.

```
import 'zx'
await $`echo Hello!`
```
```
node --loader ts-node/esm echo.ts
(node:21301) ExperimentalWarning: --experimental-loader is an experimental feature. This feature could change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
$ echo Hello!
Hello!

```

**Comment by korosuke613** [comment]
@antongolub, I missed that… I was able to run it successfully by `import 'zx'`. Thanks!

**Comment by antonmedv** [comment]
Strange, I assumed what `import {$} from 'zx'` will also work.

**Comment by antonmedv** [comment]
BTW, you can run .ts directly via `zx` executable.:

```
zx examples/typescript.ts
```

**Comment by korosuke613** [comment]
@antonmedv 
Yes, I am very happy to be able to run it with zx command 🎉. However, there are times when you want to use `ts-node` during development for debugging with the IDE, so that's what I did this time.

**Comment by antonmedv** [comment]
Yes, let's try to fix ts-node case as well.

**Comment by antonmedv** [comment]
Does it work now, in the main branch?

**Comment by korosuke613** [comment]
@antonmedv 
Yes! 
I packed the main branch and ran `node --loader ts-node/esm echo.ts`. It ran fine. I think this issue has been resolved.
