### ISSUE TITLE
Setting environment variables doesn't work

### ISSUE THREAD

**Issue by hannojg** [google/zx#116]
## Expected Behavior

Env vars set via `export` are available in the bash session after the zx script has terminated.

## Actual Behavior

Anything that has been exported in the script isn't available afterwards

## Steps to Reproduce the Problem

1. Create a simple script
```
#!/usr/bin/env zx

await $`export TEST=Hello`
```

2. Try to get env in bash
```
echo $TEST
```

Fails.

Its not even accessible in the zx session:

1.
```
#!/usr/bin/env zx

await $`export TEST=Hello`
await $`export FOO=$TEST`
```

Fails with:
```
Error: /bin/bash: TEST: unbound variable
    at file:///start.mjs:23:8
```

## Specifications

- Version: zx version 1.12.0
- Platform: Ubuntu, bash

**Comment by antonmedv** [comment]
https://github.com/google/zx#passing-env-variables

**Comment by ugolas** [comment]
I think the issue is not with "passing env variables", but setting them in the zx script like:

await $`export TEST=Hello`
OR
process.env.TEST="Hello"

After the script finishes, the above vars aren't set:

echo $TEST -> prints nothing..

**Comment by antonmedv** [comment]
As expected.

**Comment by ugolas** [comment]
@antonmedv anyway to make it work? and equivalent to using "source" on bash files? 

To apply the env vars on the env after the script is done?

**Comment by antonmedv** [comment]
Any program can modify environment variables only of sub processes. 

It can’t modify env vars of itself or parent process. 

Bash source is not a program, it’s a special builtin for updating environment vars in a shell.
