### ISSUE TITLE
bi-directional env passing

### ISSUE THREAD

**Issue by Dunky13** [google/zx#119]
## Expected Behavior
https://github.com/google/zx#passing-env-variables
As defined in the above URL, you can pass env variables from the script to shell commands. It would be nice to also do it the other way around like:
```ts
await $`source .envfile`
console.log(process.env) //containing the above sourced env variables
```

## Actual Behavior
Env variables are not passed to `process.env`

**Comment by antonmedv** [comment]
I think this is out of the scope of zx project.

**Comment by Dunky13** [comment]
That's a shame, but I understand. If you reconsider, please let me know.

I'm working on a workaround with the dotenv library for the time being

**Comment by Dunky13** [comment]
Using the `dotenv` library (https://github.com/motdotla/dotenv) I created the following workaround:

```ts
const source = async (path: string): Promise<void> => {
  if (path in process.env) {
    return
  }
  const env_vars = (await $`source ${path} && env`).stdout
  const _obj = dotenv.parse(env_vars)
  for (const k in _obj) {
    process.env[k] = _obj[k]
  }
  process.env[path] = 'true'
}
```

I hope it helps people who face a similar issue

**Comment by bkniffler** [comment]
People who want this should probably upvote the PR here: https://github.com/google/zx/pull/327
