### ISSUE TITLE
question is ignored by command

### ISSUE THREAD

**Issue by Rhuaer** [google/zx#120]
## Expected Behavior
question function can accept input content.

## Actual Behavior
question is ignored by command.

## Steps to Reproduce the Problem

``` js
#!/usr/bin/env zx

let data= await $`cat ${__dirname}/data.txt`;
let input= await question("type something: ");
```
1. execute the code above with zx
1. question is skiped

## Specifications

- Version: zx version 1.11.0
- Platform: win10 wsl2

**Comment by antonmedv** [comment]
Can’t reproduce.
