### ISSUE TITLE
Error with node v12.22.1 and  v10.18.0

### ISSUE THREAD

**Issue by Clive-primotus** [google/zx#122]
Hi, which version of node should we use? ( I didn't see it specified in github nor  https://www.npmjs.com/package/zx)
I tried with  12.22.21 => 
```
let ok = await scriptFromStdin()
             ^^^^^

SyntaxError: Unexpected reserved word
```  

with v10.18.0

```
/.nvm/versions/node/v10.18.0/lib/node_modules/zx/zx.mjs:17
import {basename, dirname, extname, join, parse, resolve} from 'path'
       ^

SyntaxError: Unexpected token {
```  
Thanks
## Steps to Reproduce the Problem

1.
1.
1.

## Specifications

- Version:
- Platform:

**Comment by antongolub** [comment]
nodejs >= 14.8 is needed for work

**Comment by Clive-primotus** [comment]
thanks I'll give a try right now.
