### ISSUE TITLE
Incompatible with ts-node

### ISSUE THREAD

**Issue by polkovnikov-ph** [google/zx#125]
## Expected Behavior
No errors

## Actual Behavior
```
Error [ERR_REQUIRE_ESM]: Must use import to load ES Module: ...\node_modules\zx\index.mjs
```

## Steps to Reproduce the Problem

1. `import {$} from 'zx';` from `index.ts`
1. `ts-node index.ts`

## Specifications

- Version: 1.14.1
- Platform: Windows

**Comment by antonmedv** [comment]
Or use 
```
zx index.ts
```

**Comment by rhyek** [comment]
I think using zx directly may be helpful in some cases, but ts-node is widely used, supported, and (very importantly) it allows script compilation to conform to whatever tsconfig developer's have in their project and also whatever compiler is being used. (Maybe a patched tsc with `ts-patch`, `ttypescript`, etc).

Ts-node should be supported. I am actually surprised using `zx` directly is supported. What is the use case for it? If people are writing typescript they already have it configured and available. Let people use that configuration.

**Comment by polkovnikov-ph** [comment]
That was exactly my case. I already had a TS configuration for backend code. Setting up separate `tsconfig`, putting TS in `--build` mode etc. is not a good DX for a tool that is supposed to simplify writing terminal-invoking scripts.

**Comment by cefn** [comment]
An alternative for people who just want simple zx scripts to run without the contagion of ESM configs, is to use `@cspotcode/zx` as per https://github.com/cefn/zx-tsnode-repro/pull/3

**Comment by tvsbrent** [comment]
I haven't gone far with this yet, but this is the shebang I'm using in a script to get `ts-node` to use ESM mode:

```
#!/usr/bin/env -S npx ts-node --esm --compilerOptions={"module":"ESNext","target":"ESNext","moduleResolution":"node"}

import { $ } from 'zx';

await $`echo ${'stuff'}`;
```

**Comment by 0xdevalias** [comment]
@tvsbrent While I don't think there is much more than you've already figured out, I just did a bit of a deepdive into using TypeScript / `ts-node` with `zw` in https://github.com/google/zx/issues/467; which might be of interest.

I ended up with a similar shebang to you, but using `ts-node-esm` instead:

```
#!/usr/bin/env npx --package=ts-node -- ts-node-esm
```

---

It's also possible to enable the `swc` transpiler in `ts-node` to get it to run a bit faster again:

- https://typestrong.org/ts-node/docs/swc

```
npm i --save-dev @swc/core
```

And then use this variation of the shebang with the `--swc` arg:

```
#!/usr/bin/env npx --package=ts-node -- ts-node-esm --swc
```

**Comment by Y80** [comment]
```js
  async handlePostBmm() {
    const zx = await import('zx');
    const process = await Promise.all([
      zx.$`cd /codes/nextjs/scripts`,
      zx.$`./main.sh`,
    ]);
    return {
      time: new Date(),
      message: 'ok',
      process,
    };
  }
```

**Comment by anacierdem** [comment]
If you just want to use zx from a cjs module without fully opting in to be an es module, you'll need to use a dynamic `import()` and set `"moduleResolution": "nodeXX"` in your compiler options. When using ts-node, you can only provide this option for it like this (e.g in your `tsconfig.json`):
```json
{
  "ts-node": {
    "moduleResolution": "nodeXX"
  }
}
```

The `moduleResolution` compiler option basically tells ts-node to keep dynamic `import()` statements as they are (among other things). Without this option, `import()`s get compiled down to a `require()` and you cannot import an es module with a 'require()`.
