### ISSUE TITLE
Can't run command inside variable

### ISSUE THREAD

**Issue by taschetto** [google/zx#126]
The following script will fail because `zx` adds quotes to the final command to be run.

```javascript
#!/usr/bin/env zx

const cmd = 'MYVAR1=1 MYVAR2=2 yarn build'

await $`${cmd}`
```

## Expected Behavior

```
$ MYVAR1=1 MYVAR2=2 yarn build
yarn run v1.6.0
Creating an optimized production build...
```

## Actual Behavior

```
$ 'MYVAR1=1 MYVAR2=2 yarn build'
/bin/bash: MYVAR1=1 MYVAR2=2 yarn build: command not found
Error: /bin/bash: MYVAR1=1 MYVAR2=2 yarn build: command not found
    at file:///......../script.mjs:5:8
error Command failed with exit code 1.
```

## Specifications

- Version: `zx` `v1.14.1`
- Platform: `Ubuntu 18.04`

**Comment by antongolub** [comment]
```ts
$.noquote = async (...args) =&gt; { const q = $.quote; $.quote = v =&gt; v; const p = $(...args); await p; $.quote = q; return p };
$.noquote`your cmd`
```

**Comment by antonmedv** [comment]
This is by design.

**Comment by leejunhui** [comment]
> ```ts
> $.noquote = async (...args) => { const q = $.quote; $.quote = v => v; const p = $(...args); await p; $.quote = q; return p };
> $.noquote`your cmd`
> ```

it worked，but why not zx implement this feature by providing some options?

**Comment by iursevla** [comment]
https://github.com/google/zx/issues/126#issuecomment-850621670

Any plans to include this into the codebase? @antongolub

**Comment by antonmedv** [comment]
No. We do not plan to add this into a codebase. If you prefer to use unsafe code, use node api directly.
