### ISSUE TITLE
`pipe` doesn't receive input if `ProcessPromise` is already resolved/awaited

### ISSUE THREAD

**Issue by atsu85** [google/zx#127]
## Expected Behavior
(Without much knowledge of NodeJS) I intuitively expected for even resolved `ProcessPromise` `pipe` to either 
a) receive output from original `ProcessPromise` as input, so the resulting `ProcessPromise` (or its awaited `ProcessOutput`) would contain output from original `ProcessPromise` transformed by the `pipe`
or
b) `pipe` to throw Error (fail fast if `ProcessPromise` was already resolved/awaited as it wouldn't make sense to pipe awaited `ProcessOutput` if it wouldn't work anyway)

## Actual Behavior
Current implementation silently produces `ProcessOutput` that after awaiting contains empty `stdout`

## Steps to Reproduce the Problem
```JavaScript
  const processPromise = $`echo "Hello"`;
  await processPromise // after awaiting promise `pipe` doesn't receive output
  let processOutput = await processPromise
      .pipe($`less`)
  assert(processOutput.exitCode === 0)
  assert(processOutput.stdout === '') // this is unexpected - intuitively would expect "Hello"
  assert(processOutput.stderr === '')
```

**Comment by atsu85** [comment]
@antonmedv, i'll add a test that passes with current (for me not very intuitive) implementation soon

**Comment by atsu85** [comment]
@antonmedv, take a look at the 
* [test that I added to document current behaviour](https://github.com/google/zx/pull/129/commits/2af729fc3bc04dea758964233f74b89b6142bfdc) (before my changes).
* [change i made (including updated test)](https://github.com/google/zx/pull/129/commits/67f542fad56adaea7a60f3e6b8579dedb89916fd)

**Comment by antonmedv** [comment]
Fixed.
