### ISSUE TITLE
Example script doesn't show proper usage

### ISSUE THREAD

**Issue by adamtaylor13** [google/zx#13]
## Expected Behavior
The example script shows this example:
```
#!/usr/bin/env zx

let branch = await $`git branch --show-current`
```
Which leads one to assume you could just use the branch name now, as it's been returned from the command.

## Actual Behavior
Despite my expectation, `branch` is now a `ProcessOutput` object which must be used as such:
```
branch.toString()
```
and that's assuming the command executed correctly!

---

Ideally a successful execution could just return the `stdout`, rather than the entire ProcessOutput object. Or at the very least, the example script should probably indicate that you cannot just use the stdout results as you would in a bash script. I can certainly see the argument for returning the standard ProcessOutput object every time, I'm just thinking of useful shortcuts here.

---

## Steps to Reproduce the Problem
Exactly as described above. Paste into a .mjs file and execute with `zx`

## Specifications

- Version: zx version 1.0.2
- Platform: MacOS 10.13.6

**Comment by rattrayalex** [comment]
Interesting… the `shelljs` behavior of `ShellString` might make this a bit more intuitive, since it preserves the `.stdout` behavior but you can still use the object mostly like a real string of its stdout.
