### ISSUE TITLE
Feature request: Unquote on a per-command basis

### ISSUE THREAD

**Issue by ryardley** [google/zx#130]
## Expected Behavior
I would like to be able to not use quoting sometimes. For example when doing path substitution Eg. 

```js
const file = '~/.yarnrc';
$`cat ${file}`
```

Should show me the contents of `~/.yarnrc` however this is not the case beacuse of quoting

## Actual Behavior

```js
const file = '~/.yarnrc';
$`cat ${file}`
```

Will fail to find `.yarnrc` because `~` is not expanded as we have a default quoting mechanism which effectively runs the command:

```js
cat '~/.yarnrc`
```

To fix this we need to change the `$.quote` config but if we wish to maintain the default for other situations we would want to do something like

```js
const file = '~/.yarnrc';
const q = $.quote;
$.quote = a => a;
await $`cat ${file}`
$.quote = q;
```

We can create a function/macro handle this but it is verbose and not ideal:

```js
async function cat(file){
  const q = $.quote;
  $.quote = a => a;
  await $`cat ${file}`
  $.quote = q;
}

await cat('~/.yarnrc');
```

## Proposal

Don't know about syntax but I propose adding someway to avoid quoting on a per command level:

```js
const file = '~/.yarnrc';
$.nq`cat ${file}` // ignore quoting strategy
```

**Comment by antonmedv** [comment]
Ignoring quotes can be dangerous. What about using path.resolve on argument? Or replacing ~ to os.homedir()?

**Comment by atsu85** [comment]
@ryardley, here is my solution:
* i've created a util function:
```TypeScript
export function $withoutEscaping(pieces: TemplateStringsArray, ...args: unknown[]): ProcessPromise<ProcessOutput> {
    const origQuote = $.quote
    try {
        $.quote = unescapedCmd => unescapedCmd
        return $(pieces, args)
    } finally {
        $.quote = origQuote
    }
}
```
and then usin `$withoutEscaping` instead of `$` in those rare cases, when i want to avoid quoting:
```TypeScript
$withoutEscaping`cat ${file}`
```
instead of:
```TypeScript
$`cat ${file}`
```

**Comment by antonmedv** [comment]
What about raw helper: await $`cat ${raw(file)}`

**Comment by ryardley** [comment]
> @ryardley, here is my solution:
> 
> * i've created a util function:
> 
> ```TypeScript
> 
> export function $withoutEscaping(pieces: TemplateStringsArray, ...args: unknown[]): ProcessPromise<ProcessOutput> {
> 
>     const origQuote = $.quote
> 
>     try {
> 
>         $.quote = unescapedCmd => unescapedCmd
> 
>         return $(pieces, args)
> 
>     } finally {
> 
>         $.quote = origQuote
> 
>     }
> 
> }
> 
> ```
> 
> and then usin `$withoutEscaping` instead of `$` in those rare cases, when i want to avoid quoting:
> 
> ```TypeScript
> 
> $withoutEscaping`cat ${file}`
> 
> ```
> 
> instead of:
> 
> ```TypeScript
> 
> $`cat ${file}`
> 
> ```
> 
> 
> 
> 

Looks like a good solution. Nice catch on using finally to turn quotes back on.

I think this should be core api. If you are using it, it will be in order to solve a problem you are having. Maybe under `$.raw`?

**Comment by antongolub** [comment]
@ryardley,
```js
$.raw = async (...args) => {
  const q = $.quote
  $.quote = v => v
  return $(...args).finally(() => {$.quote = q})
}
```

**Comment by antonmedv** [comment]
As unquoting is unsafe, zx will not provide it.
