### ISSUE TITLE
Cant run zx ExperimentalWarning: The ESM module loader is experimental.

### ISSUE THREAD

**Issue by vuvgaG-dukgu3-wysnox** [google/zx#132]
## Expected Behavior
Simple running of a .ts file

## Actual Behavior

(node:18579) ExperimentalWarning: The ESM module loader is experimental.
file:///Users/vuvgaG/.nvm/versions/node/v13.9.0/lib/node_modules/zx/zx.mjs:33
    let ok = await scriptFromStdin()
             ^^^^^

SyntaxError: Unexpected reserved word
    at Loader.moduleStrategy (internal/modules/esm/translators.js:81:18)
    at async link (internal/modules/esm/module_job.js:37:21)
## Steps to Reproduce the Problem

contents is 

```ts
#!/usr/bin/env zx
import 'zx
```

Running this produces the above error by both executing like `./script.ts` and `zx scripts.ts`

Or by just running `zx --version`

## Specifications

- Version: can't run --version I get the same error
- Platform: Mac OS 11.3
```
vuvgaG@iMac [19:19:51] [~/Repositories/profile] [master *]
-> % type zx
zx is /Users/vuvgaG/.nvm/versions/node/v13.9.0/bin/zx
```

**Comment by antongolub** [comment]
node >= 14.8.0 is required

**Comment by vuvgaG-dukgu3-wysnox** [comment]
with node 16 i'm getting

```
node:internal/process/promises:246
          triggerUncaughtException(err, true /* fromPromise */);
          ^

Error [ERR_MODULE_NOT_FOUND]: Cannot find package 'zx' imported from
```

**Comment by antongolub** [comment]
`which zx`. If it still refers to `node/v13.9.0`, you may need to reinstall the package: `npm i -g zx`.
