### ISSUE TITLE
ts-ignore not working

### ISSUE THREAD

**Issue by Dunky13** [google/zx#136]
## Expected Behavior
`tsc` compiles succesfully. (I know ZX can/will do it, but need `tsc` to compile for our deployment process)

## Actual Behavior
```sh
node_modules/typescript/lib/lib.dom.d.ts:19624:18 - error TS2451: Cannot redeclare block-scoped variable 'fetch'.

19624 declare function fetch(input: RequestInfo, init?: RequestInit): Promise<Response>;
                       ~~~~~

  node_modules/zx/index.d.ts:76:9
    76   const fetch: typeof _fetch
               ~~~~~
    'fetch' was also declared here.


Found 1 error.
```

I did check the path `node_modules/zx/index.d.ts:76:9` and line 75 contains `// @ts-ignore` but it doesn't seem to work.

## Steps to Reproduce the Problem

1. Run `tsc` with zx@1.14.1 & typescript@4.3.2

## Specifications

- Version: 1.14.1
- Typescript version 4.3.2

**Comment by antonmedv** [comment]
Looks like not related to zx.

**Comment by antongolub** [comment]
Hey, @Dunky13,

Just don’t include ‘dom’ lib on compile.

**Comment by Dunky13** [comment]
I don't think I'm doing that

**Comment by Dunky13** [comment]
I wasn't completely wrong, but I did not explicitly specify it.
This issue: https://github.com/mswjs/msw/issues/408 helped me out
