### ISSUE TITLE
Can't write scripts with commander

### ISSUE THREAD

**Issue by mysteryven** [google/zx#137]
here is my `test.mjs`: 

```bash
#!/usr/bin/env zx

import { Command } from 'commander';
const program = new Command();

program
    .command("publish <name>")
    .action((name) => {
        console.log(name)
    });

program.parse(process.argv);
```

## Expected Behavior

I run this file with `zx ./test.mjs`, I want to get result like below: 

```
Usage: index [options] [command]

Options:
  -h, --help      display help for command

Commands:
  publish <name>
  help [command]  display help for command

```

I got above result when I run `node test.js`, this file only diff with `test.mjs` in shebangs

```
#!/usr/bin/env

import { Command } from 'commander';
const program = new Command();

program
    .command("publish <name>")
    .action((name) => {
        console.log(name)
    });

program.parse(process.argv);

```

## Actual Behavior

when I run `zx ./test.mjs`, the result was:

error: unknown command './test.mjs'. See 'zx --help'.

## Steps to Reproduce the Problem

1. zx ./test.mjs

## Specifications

- Version: node(v14.15.1), zx(v1.14.1)
- Platform: MacOS

**Comment by antonmedv** [comment]
I suspect this error thrown from commander.  Please, refer to commander’s doc.

**Comment by shadowspawn** [comment]
The issue is the arguments in `process.argv`. Commander expects by default that `arg[0]` is the script name, and `arg[1]` is the first of the user supplied arguments. But when launched by `zx` there is an extra argument which is `zx` itself.

```js
// foo.mjs
console.log(process.argv);
```

```
% zx foo.mjs install
[ '/usr/local/bin/node', '/usr/local/bin/zx', 'foo.mjs', 'install' ]
```

As a work-around you could call parse like this:

```
program.parse(process.argv.slice(1)); // node-style with arg[0] utility and arg[1] is script name
// or
program.parse(process.argv.slice(3), { from: 'user' });
```
