### ISSUE TITLE
Code blocks in .md files always execute

### ISSUE THREAD

**Issue by DanCouper** [google/zx#138]
## Expected Behavior

Only code I want to execute should execute.

## Actual Behavior

Anything in either a fenced block or indented by 4 spaces/tab blindly executes: it is all added to the output `.mjs` file regardless of if I want it there or not.

## Steps to Reproduce the Problem

1. Save text of this issue as a .md file
2. Execute it using `zx`

Or probably more usefully:
- [gist 1 (works)](https://gist.github.com/DanCouper/8756cc220fc709836cfd1b065566bc5e#file-zx_example_1-md)
- [gist 2 (executes script block, fails)](https://gist.github.com/DanCouper/8756cc220fc709836cfd1b065566bc5e#file-zx_example_2-md)
- [gist 3 (attempts to execute line after script block, fails)](https://gist.github.com/DanCouper/8756cc220fc709836cfd1b065566bc5e#file-zx_example_3-md)

I am finding the ability of `zx` to execute scripts written as `.md` files very useful from a documentation PoV.

The actual executable part works well, _ex_:

```js
$`echo "Example script execution in fenced block with a js language tag"`;
```

```
$`echo "Example script execution in a fenced block without any language tag"`;
```

    $`echo "Example script execution in indented block"`;

But if I want to document some piece of code within the markdown file, I have an issue. So for example,
maybe I want to explain how to run it via some aliased command in my npm scripts block:

```
yarn runscript ./scripts/example.md
```

But that will just cause the script to explode.

I understand why, see the tiny .md file parser:
- [Entering "tab" state here](https://github.com/google/zx/blob/2dfb3488bfc82fe205fe2eb566ef7f37abcbdf55/zx.mjs#L140)
- [Entering "code" state here](https://github.com/google/zx/blob/2dfb3488bfc82fe205fe2eb566ef7f37abcbdf55/zx.mjs#L143)

So when I just glanced at that function, I thought I could use a different language tag (well, anything except js).

```sh
yarn runscript ./scripts/example.md
```

And the little parser manages to ignore it. But then the parsing breaks and it tries to execute _this_ line here  instead. Looking at the function, I see why, and I'm currently [naïvely] dealing with this by patching the package, removing the ability to parse indented code blocks as part of the output, then just indenting any examples.

## Specifications

- Version: all
- Platform: all

**Comment by DanCouper** [comment]
That's fair, I guess it's an edge case for most people. Effectively what I want is a basic ability to have literate scripts, and inline comments aren't ideal, I'd rather just have it ignore specific blocks. I'll have a think about this before committing to it, but I'll probably maintain a fork that allows this, I just need to have a think about a sensible way to do it without overcomplicating.

**Comment by antonmedv** [comment]
If you have some good ideas, feel free to open a new discussion regarding new features.

**Comment by antonmedv** [comment]
Fixed!

After more thought, I decided to only execute code blocks with tabs and with explicit js|javascript tags.

Also added support for bash tags!

![image](https://user-images.githubusercontent.com/141232/129290745-169e1c13-f45b-4b49-8b0f-7043d8421214.png)
