### ISSUE TITLE
Script stops at the question() call

### ISSUE THREAD

**Issue by TimBobkov** [google/zx#139]
My first test of using of ZX. Create script for obtaining configs for all or some AKS clusters from all subscriptions. Found that script stop at one question without any notification. This looks like [closed issue](https://github.com/google/zx/issues/120).
My script:
```javascript
#!/usr/bin/env zx

let accountParams = '';
let accounts = [];
$.quote = v => v;
$.verbose = false;
const yesOrNo = ['yes', 'no'];

async function getAKSConfigs(accounts) {
  for (const element of accounts) {
    console.log(`Subscription ID: ${element.id}, name: ${element.name}`);
    const rawAKSList = await $`az aks list --subscription ${element.id}`;
    const aksList = JSON.parse(rawAKSList);
    if (aksList.length > 0) {
      for (const aks of aksList) {
        console.log(`Get credentials for ${aks.name} at ${aks.resourceGroup}`);
        await $`az aks get-credentials -n ${aks.name} -g ${aks.resourceGroup} --subscription ${element.id} --overwrite-existing`;
      }
    } else {
      console.log(`No AKS cluster found in subscription ${element.name}`);
    }
  }
}
function displayAccounts() {
  for (let i = 0; i < accounts.length; i++) {
    console.log(`${i} - ID: ${accounts[i].id}, name: ${accounts[i].name}`);
  }
}

const refreshAccounts = await question('Refresh accounts? ', {
  choices: yesOrNo
});

if ( refreshAccounts === 'yes') {
  accountParams = '--refresh --only-show-errors';
};
const rawAccounts = await $`az account list ${accountParams}`;
for (const element of JSON.parse(rawAccounts)) {
  accounts.push({
    id: element.id,
    name: element.name
  });
}

displayAccounts();
await $`echo 'Just for question work'`;
const account = await question('Select account number? (Type ALL for all accounts) ');


if (account === 'ALL') {
  await $`rm -f ~/.kube/config`;
  await getAKSConfigs(accounts);
} else {
  await getAKSConfigs([accounts[account]]);
};
```
So `const account = await question('Select account number? (Type ALL for all accounts)');` kill my script. I have found that adding any dummy command before this question repair it. That's why I add ```await $`echo 'Just for question work'`;```.

## Expected Behavior
Any question works in the same way.

## Actual Behavior
Some question broke script without any errors anywhere. Script can be repaired by adding any `$.<command>` before question.

## Steps to Reproduce the Problem

1. Run my script without ```await $`echo 'Just for question work'`;``` line

## Specifications

- Version: 1.14.1
- Platform: Ubuntu 20.04 at WSL2

**Comment by antonmedv** [comment]
Please, provide minimal reproducible example.

**Comment by TimBobkov** [comment]
Hi @antonmedv.
This is minimal amount of code for reproduce:
```javascript
#!/usr/bin/env zx

let accountParams = '';
let accounts = [];
$.quote = v => v;

const rawAccounts = await $`az account list ${accountParams}`;
for (const element of JSON.parse(rawAccounts)) {
  accounts.push({
    id: element.id,
    name: element.name
  });
}

const account = await question('Select account number? (Type ALL for all accounts) ');
console.log(account);
```

**Comment by antonmedv** [comment]
Can’t reproduce. Works for me.

**Comment by TimBobkov** [comment]
Does you check with AZ CLI? I don't see such issue with other used commands...

**Comment by antonmedv** [comment]
I don’t have az

**Comment by TimBobkov** [comment]
Is there any possibility for you to install it just for tests?
Link: https://docs.microsoft.com/en-us/cli/azure/install-azure-cli

**Comment by Dunky13** [comment]
Hi @antonmedv,

I'm facing the same issue, when running zx within a docker container.
When I have the following code:
```ts
const response = await question("Are you alive?", {choices: [...yes, ...no]})
```
It prints the question, and stops

But when I run:
```ts
await $`echo ''`
const response = await question("Are you alive?", {choices: [...yes, ...no]})
```
The script waits for response, most of the times. (But not always). Really weird

**Comment by antonmedv** [comment]
question is only a wrapper. Can you try in with nodejs directly?

**Comment by TimBobkov** [comment]
try to use this code:
```javascript
const readline = require('readline');

let params= '';
$.quote = v => v;

const var1 = await $`az ${params}`;

// const var2 = await question('Any question? ');
// console.log(var2)
const rl = readline.createInterface({
  input: process.stdin,
  output: process.stdout
});
rl.question('What do you think of Node.js? ', (answer) => {
  console.log(`Thank you for your valuable feedback: ${answer}`);
  rl.close();
});
```
same behavior...
Adding dummy command like this:
```javascript
const readline = require('readline');

let params= '';
$.quote = v => v;

const var1 = await $`az ${params}`;

// const var2 = await question('Any question? ');
// console.log(var2)
await $`echo ''`
const rl = readline.createInterface({
  input: process.stdin,
  output: process.stdout
});
rl.question('What do you think of Node.js? ', (answer) => {
  console.log(`Thank you for your valuable feedback: ${answer}`);
  rl.close();
});
```
fix everything

**Comment by antonmedv** [comment]
Looks like something wrong with stdin pipe. Try to comment it.

**Comment by woodgear** [comment]
use  `process.stdin.isTTY = false`
works for me.

**Comment by Dunky13** [comment]
That worked for me, thank you @woodgear

**Comment by antonmedv** [comment]
Let’s investigate what it causes nodejs to stop.

**Comment by itech001** [comment]
> use `process.stdin.isTTY = false`
> works for me.

this work for me too, thanks~~~

**Comment by cspotcode** [comment]
Setting `process.stdin.isTTY = false` is disabling this:
https://github.com/google/zx/blob/bb9cf3891583313405a29b47e8151b65b7376f91/index.mjs#L57-L59

So it sounds like that `.pipe` call is not quite correct and should be adjusted in some way, because I'm guessing that it is negatively affecting the stdin stream.

**Comment by cspotcode** [comment]
I figured it out.  `zx` needs to call `process.stdin.unpipe(child.stdin)`.  Otherwise, backpressure might pause `process.stdin`.  If it is paused, then it will never emit events, so any question prompts will not have any pending work on the event loop.  When the event loop is empty, node exits.

This ticket should be reopened, and the bugfix is to call `process.stdin.unpipe`

**Comment by antonmedv** [comment]
Awesome! Can you create a bug fix?
