### ISSUE TITLE
Not able to execute long running command at background(via a '&' at the end of command)

### ISSUE THREAD

**Issue by wuminqi** [google/zx#140]
Hi, I am trying to use `zx` to launch a long running task at background.  It seems that putting a '&' at the end of command does not work in `zx`. Is it a known limitation? Does anyone know how to execute long running task at background using `zx`?

Here is a [sample repo](https://github.com/wuminqi/issue-zx.long.running.task) to reproduce the issue.

And the entry script is like below:

```
#!/usr/bin/env zx

console.log('before ~')
await $`nohup ./bin/sleep.mjs &`
console.log('after ~')
```

## Expected Behavior

- sleep.mjs is executed at background.
- issue.mjs quits after 'after ~' is outputted.

## Actual Behavior

- sleep.mjs is executed at foreground.
- issue.mjs does not quit itself, and 'after ~' is not outputted.

```shell
issue-zx.long.running.task git:(master)  ./bin/issue.mjs 
before ~
$ nohup ./bin/sleep.mjs &
Awake ...
Awake ...
Awake ...
Awake ...
Awake ...
Awake ...
Awake ...
Awake ...
^C
```

## Steps to Reproduce the Problem

Run `./bin/issue.mjs` under root directory of [sample project](https://github.com/wuminqi/issue-zx.long.running.task).

## Specifications

- Version: 1.14.1
- Platform: MacOS 11.4

**Comment by antonmedv** [comment]
Everything right. Zx still attached to child process. To start deamon process refer to nodejs doc.

**Comment by wuminqi** [comment]
Thanks, glad to know it is by design. 

Surely it can be implemented via Node.js, but It will be more convenient if Zx can provide that ability as Bash does.

**Comment by antonmedv** [comment]
What about creating a separate func - deamon() for this.

**Comment by wongjiahau** [comment]
@antonmedv That would be great if say `daemon` function is to be included in `zx`!

**Comment by anuraaga** [comment]
I happened to find this issue and as far as I can tell, this is relatively simple by just not awaiting the promise returned by zx, this may be the intended pattern for daemons with zx.

#!/usr/bin/env zx

console.log('before ~')
const p = $`./bin/sleep.mjs`;
await new Promise((resolve) = {
  p.stdout.on('data', (chunk) => {
    if (chunk.includes('Ready')) {
     resolve(true);
    }
  });
});
// Do more stuff with background process
console.log('after ~')

**Comment by antonmedv** [comment]
More simple solution:
```js
const serve = $`./bin/sleep.mjs`

for await (const chunk of serve.stdout) {
  if (chunk.includes('Ready')) break
}
```
