### ISSUE TITLE
question() does not filter choices

### ISSUE THREAD

**Issue by Dunky13** [google/zx#142]
## Expected Behavior
Ask again if expected choices does not match with supplied choices option.

## Actual Behavior
Return supplied choice, which did not match with `option?.choices`

## Steps to Reproduce the Problem
Ask a `question("Some question", choices: [...yes, ...no]` where `yes` and `no` are arrays of Yes/No permutations

If I input `da` or anything that does not match the `choices` array, I expect it to ask the question again, until a satisfactory answer is supplied.

**Comment by antonmedv** [comment]
> Ask again if expected choices does not match with supplied choices option.

This is not correct. 

It’s only autocomplete.

**Comment by Dunky13** [comment]
Could this be clarified in the documentation? It was not super clear to me, as it is documented
