### ISSUE TITLE
string not passed correctly

### ISSUE THREAD

**Issue by nailtonoliveira** [google/zx#144]
## Expected Behavior
I was playing here to see the possibilities and I ran into a problem. I wanted to take advantage of the code to not duplicate, and it turned out it didn't work correctly, as the string is not passed correctly as a parameter of the command.
```shell
docker-compose up -d
```

## Actual Behavior
But i'm getting this and the docker-compose command doesn't execute correctly.
```shell
docker-compose 'up -d'
```

That is a example of my script:
```js
#!/usr/bin/env zx

const args = process.argv.slice(3)

async function exec(command) {
  await $`docker-compose ${command}`
}

if (!args.length) {
  exec('up -d')
} else {
  if (args[0] !== 'down') {
    console.log('Error: invalid argument')
  } else {
    exec('down')
  }
}
```

Ps.: With the `down` argument it works perfectly

**Comment by antongolub** [comment]
Hey, @nailtonoliveira,

By desing **zx** apllies [shq](https://www.npmjs.com/package/shq) to all string literal chunks. But you can override this handler and perform _unsafe_ call if necessary:
```js
const q = $.quote
$.quote = v => v
$`docker-compose ${command}`
$.quote = q
```

**Comment by nailtonoliveira** [comment]
Thanks @antongolub!

**Comment by antonmedv** [comment]
When passing arguments to `${...}` there is no need to add quotes. **Quotes will 
be added automatically if needed.**

```js
let name = 'foo & bar'
await $`mkdir ${name}`
```

For quotes **zx** uses special bash syntax (next commands are valid bash):

```bash
mkdir $'foo & bar'
$'ls' $'-la'
```

If you add quotes `"${name}"`, it will produce a wrong command. 

If you need to add something extra, consider putting it inside curly brackets.

```js
await $`mkdir ${'path/to-dir/' + name}`
```

This will also work properly:

```js
await $`mkdir path/to-dir/${name}`
```

### Array of arguments

The `zx` can also take an array or arguments in the `${...}`. Items of the array
will be quoted separately and concatenated via a space. 

Do **not** add a `.join(' ')`.

```js
let flags = [
  '--oneline',
  '--decorate',
  '--color',
]
await $`git log ${flags}`
```

If you already have a string with arrays, it's your responsibility
to correctly parse it and distinguish separate arguments. For example like this:

```js
await $`git log ${'--oneline --decorate --color'.split(' ')}`
```
