### ISSUE TITLE
fs.constants is undefined

### ISSUE THREAD

**Issue by kctang** [google/zx#146]
## Expected Behavior
`fs.constants` should return value as defined by https://nodejs.org/api/fs.html#fs_fs_constants.

## Actual Behavior

Returns undefined.

## Steps to Reproduce the Problem

Run script with `console.log(fs.constants)`

## Workaround

```
import {constants} from "fs"

console.log(constants)
```

**Comment by antongolub** [comment]
It seems reasonable to add this.
