### ISSUE TITLE
Suggestion to document how to pipe both stdout and stderr

### ISSUE THREAD

**Issue by kctang** [google/zx#148]
The docs describe how to pipe `$` output to `stdout`. However, it was not obvious how to pipe `stderr`.

As this is a very common use case when spawning child processes, would be good to make this more obvious to new users.

Took me sometime to realized that this can be done via:

```
      const testCmd = $`npm test`
      testCmd.pipe(process.stdout)
      testCmd.stderr.pipe(process.stdout)
      await testCmd
```

Sharing this information here for those who needs it. Consider adding it to the main README doc and thanks for this amazing tool!

**Comment by antonmedv** [comment]
Good idea.

**Comment by antonmedv** [comment]
Done
