### ISSUE TITLE
Generete wrong template literals ịn JS

### ISSUE THREAD

**Issue by harrytran998** [google/zx#149]
Here it's my code, when executed, the command had contained `''` character --> Run failed.

```js
#!/usr/bin/env zx

let originCmd = 'yarn do:something'
const parameters = ['XXX', 'YYY']

const executeCmd = originCmd + ' --option '.concat(parameters.join(' --option '))

await $`${executeCmd}`; 
```
## Expected Behavior

```
yarn do:something --option XXX --option YYY
```

## Actual Behavior
```
'yarn do:something --option XXX --option YYY'
```

## Specifications

- Version: ^1.14.2
- Platform: MacOS 10.15.7

**Comment by antongolub** [comment]
Hey, @harrytran998, see https://github.com/google/zx/issues/144

**Comment by harrytran998** [comment]
> Hey, @harrytran998, see #144

Thank you for the quick response! But can I ask you a question? Why you do not add this feature to this package?

```
$.raw = async (...args) => {
  const q = $.quote
  $.quote = v => v
  try {
    return $(...args)
  } finally {
    $.quote = q
  }
}
```

**Comment by antonmedv** [comment]
Why not just use exec directly here?

**Comment by antonmedv** [comment]
```js
await $`${executeCmd.split(' ')}`;
```
