### ISSUE TITLE
Why did drop the support of Node 14 (Active LTS)?

### ISSUE THREAD

**Issue by ferjul17** [google/zx#154]
## Expected Behavior
I should be able to install `zx` in my project limited to node 14 (the active LTS).

## Actual Behavior

When I try to install `zx` I have the following error message:
> error zx@1.15.2: The engine "node" is incompatible with this module. Expected version ">= 15.0.0". Got "14.17.1"

## Steps to Reproduce the Problem

1. `echo '{ "engines": { "node": "^14" } }' > package.json`
2. `yarn add zx`

## Specifications

- Version: `yarn` `1.22.10`
- Platform: `Linux`

**Comment by antonmedv** [comment]
I added replaceAll call. Actually it’s possible to support 14 too.

**Comment by ferjul17** [comment]
I think that would be good. Node 14 is, for example, the latest version supported by AWS. If you could at least support the LTS of Node, I would appreciate it.

**Comment by antonmedv** [comment]
Returned support for node 14

**Comment by williamboman** [comment]
Thanks for reverting the issue! Could this change perhaps be applied to the v1 release branch too with a new `v1` release? [In this project](https://github.com/williamboman/nvim-lsp-installer/) we're depending on `zx@1` (for no specific reason other than avoiding unexpected breaking changes)
