### ISSUE TITLE
Latest index.d.ts is not published

### ISSUE THREAD

**Issue by Dunky13** [google/zx#155]
https://unpkg.com/zx@1.15.2/index.d.ts

Exploring the latest version (1.15.2) I see that `argv` is not a member of the global definition.
Typescript is complaining about it.

As you can see, `index.d.ts` does not match with the published version

**Comment by Dunky13** [comment]
Also, same goes for the `index.mjs`

The minimis is not provided in the latest release

**Comment by Dunky13** [comment]
I see the latest changes have not been committed in general. Sorry

**Comment by antonmedv** [comment]
Yes, my bad. Next time will develop in branch, not in master.

**Comment by Dunky13** [comment]
Keep up the great work, rewrote our old CLI (bash) into node.js using this framework to bridge the gap :)
