### ISSUE TITLE
SyntaxError: await is only valid in async functions and the top level bodies of modules

### ISSUE THREAD

**Issue by thomaszdxsn** [google/zx#157]
## Expected Behavior

use example code, but can work

## Actual Behavior

```
await Promise.all([
^^^^^

SyntaxError: await is only valid in async functions and the top level bodies of modules
```

## Specifications

- Version: 2.0.0
- Platform: mac m1 / node v16.3.0

**Comment by p3k** [comment]
what is the reason for closing this issue?

**Comment by antonmedv** [comment]
Please read readme.

**Comment by cd-ff** [comment]
Specifically the [usage](https://google.github.io/zx/getting-started#usage), which tells you:

> Write your scripts in a file with an .mjs extension in order to use await at the top level. If you prefer the .js extension, wrap your scripts in something like void async function () {...}().
