### ISSUE TITLE
How do I manually kill a task?

### ISSUE THREAD

**Issue by thecodrr** [google/zx#159]
I am running a react dev server in the background while running tests in the foreground. I want to kill the dev server as soon as the tests complete. How can I do that with zx?

**Comment by antonmedv** [comment]
Get a pid of running process. Kill task.

**Comment by antonmedv** [comment]
Actually nice idea. Maybe introduce it in zx as an api.

**Comment by thecodrr** [comment]
Got it. I made it work like you said.

**Comment by Dunky13** [comment]
Would be nice if the `ProcessPromise<ProcessOutput>` would contain the running pid. So it can easily be referenced and used.
