### ISSUE TITLE
Support NPM scripts natively?

### ISSUE THREAD

**Issue by JAForbes** [google/zx#160]
It would be super useful if zx included `$(npm bin)` on that path of `$` out of the box.

## Expected Behavior

```js
// test.zx.js
const x = await $`eslint --version`
console.log(x.stdout)
```

```shell
$ npm install eslint -D
$ npx zx test.zx.js
v7.22.0
```
## Actual Behavior

```js
// test.zx.js
const x = await $`eslint --version`
console.log(x.stdout)
```

```shell
$ npm install eslint -D
$ npx zx test.zx.js
/usr/bin/bash: eslint: command not found
```

**Comment by antonmedv** [comment]
Nice idea! I'll add it.

**Comment by JAForbes** [comment]
Very exciting! 🎉

**Comment by antonmedv** [comment]
The idea is nice but calling `npm bin` takes too much time to enable it by default.:
```
$ npm bin
/Users/anton/dev/zx/node_modules/.bin
default: 337.515ms
```

This can be easily implemented on user side via:
```js
process.env.PATH += path.delimiter + (await $`npm bin`).stdout.trimEnd()
```

Adding `node_modules/.bin` by default will not work with global and subdirs.

**Comment by JAForbes** [comment]
Thanks for investigating this.  I think you've made a great case for not including this, at least until a better solution comes around.
