### ISSUE TITLE
$'s template strings broken with zx version 2

### ISSUE THREAD

**Issue by apibrac** [google/zx#164]
Hello! I noticed with version 2 most of my scripts broke.
This is caused by [this new function](https://github.com/google/zx/blob/18f64bc2a791ddbf3626217ba9412c06efb9279b/index.mjs#L240) that adds a dollar and a quote in some specific conditions.

I don't really understood the point of it so I prefer asking, is it an intended behavior?
If so it would be great to add an explanation on the Readme and a note in a changelog documentation. If not would be glad to correct it :)

## Expected Behavior

```bash
echo '

const today = new Date()
$`echo "Today year is ${today.getFullYear()} and full date is ${today.toISOString()}"`

' > test.mjs
zx test.mjs

>>> Today year is 2021 and full date is 2021-07-15T16:18:35.288Z
```

## Actual Behavior

```bash
echo '

const today = new Date()
$`echo "Today year is ${today.getFullYear()} and full date is ${today.toISOString()}"`

' > test.mjs
zx test.mjs

>>> Today year is 2021 and full date is $'2021-07-15T16:18:35.288Z'
```

## Steps to Reproduce the Problem

1. npm i -g zx
2. Execute the lines I pasted before

## Specifications

Works as expected with zx version 1.14.1

Broken on :
- Version: 2.0.0
- Platform: wsl2

Thanks for your help!

**Comment by antonmedv** [comment]
This expected behaviour. Can you show example of script with error?

Adding explanation to readme is a good idea.

**Comment by j0nas** [comment]
@antonmedv 

For what it's worth, I encountered the same issue as described by OP and I was a bit surprised. I don't have the exact code, but it was a string constant I'd reused across commands, which ended up with the same erroneous  `$''` wrapping. I ended up inlining the constant to circumvent the issue.


```
/ / script.ts
import 'zx';

const today = new Date();
await $`echo "Today year is ${today.getFullYear()} and full date is ${today.toISOString()}"`
```

This reproduces OP's issue. The output is `Today year is 2021 and full date is $'2021-07-16T00:02:03.348Z'`. The `$''` wrapping should not be there.

**Comment by apibrac** [comment]
Thanks @j0nas for completing the answer, I did not detail properly.

@antonmedv the extra `$''` that appears on zx version 2 may break the command we're running.
As a specific example, I sometimes use `gcloud` cli with timestamps to looks for logs in my projet, the `.mjs` commands look like:
```javascript
const someDate = new Date();
const someLog = "something not important";

const logs = await $`gcloud logging read '
    jsonPayload.message="${someLog}"
    timestamp>="${someDate.toISOString()}"
  ' --format=json`;

JSON.parse(logs).map(...)
```

Until now, it run the command:
```bash
gcloud logging read '
    jsonPayload.message="something not important"
    timestamp>="2011-10-05T14:48:00.000Z"
  ' --format=json`;
```
which is the correct format for such cli.

With zx version 2 it looks like:
```bash
gcloud logging read '
    jsonPayload.message="something not important"
    timestamp>="$'2011-10-05T14:48:00.000Z'"
  ' --format=json`;
```
and it just doesn't work because the date provided for comparison with the timestamp (second condition) has a dollar on it, and extra quotes.

The gcloud cli use case is not very important here, that's why my first example was with `echo`. But we can see that the `$` template string has a strange behavior.
I start to understand that it may work if I match the use of the `${}` with the insertion of a full text (doing ```await $`gcloud logging read ${fullTextFilter} --format=json`;```) but there is some kind of logic that is not explicit enough I think.

**Comment by antonmedv** [comment]
Try to move whole argument to a js var.

**Comment by antonmedv** [comment]
```
let nsg = `
    jsonPayload.message="${someLog}"
    timestamp>="${someDate.toISOString()}"
  `
```

**Comment by OllysCoding** [comment]
How do you call it if you move the whole argument to json, without it wrapping the entire contents of the variable in single quotes

**Comment by lisumio** [comment]
Seems like `zx` only struggles when the expression contains dashes. 

```sh
$`${'some string'}` // some string
$`${'some-string'}` // $'some-string'
```

After going through the source code the issue IMO is [a regex inside of quote function](https://github.com/google/zx/blob/18f64bc2a791ddbf3626217ba9412c06efb9279b/index.mjs#L241).

Instead of:

```js
/^[a-z0-9_.-/]+$/i
```

it should be

```js
/^[a-z0-9_.\-/]+$/i
```

Because JS otherwise considers the dash to be range indicator (it matches all characters between `.` and `/` = between 46 and 47 = only these two characters) and the dash is being ignored. 

You can easily test this: 

```js
/^[a-z0-9_.-/]+$/i.test('some-string')  // false
/^[a-z0-9_.'-/]+$/i.test('some-string') // true
```

I was able to get around this using:

```js
const flag = `--help`
const command = `git ${flag}`

$([command]) // Is executed as `git --help`
```

**Comment by antonmedv** [comment]
Awesome! Can you make a PR with a fix?

**Comment by antonmedv** [comment]
Also `/^[a-z0-9/_.-]+$/i` Will work :)

**Comment by PATROMO** [comment]
@antonmedv can you please create a new release with this fix? :)

**Comment by antonmedv** [comment]
Sure.

**Comment by Morriz** [comment]
Any chance of a release soon? We are suffering from this and find it problematic to use `master`. I am sad to see such a huge bug in a new major release. Don't tests exist for these basics?

**Comment by Morriz** [comment]
This is still not fixed:
```
  const test = '"something"'
  const out = await $`echo "${test}"`
  console.log(out.stdout)
```

**Comment by antonmedv** [comment]
I’m not sure what you expect from the last code. Its seem to me incorrect.

**Comment by Morriz** [comment]
Maybe sometimes it is desired to print quoted strings?  Those should just be encoded correctly imo...

**Comment by antonmedv** [comment]
Omit quotes in echo.

**Comment by j0nas** [comment]
A release with #167 would still be nice. :slightly_smiling_face:

**Comment by Morriz** [comment]
> Omit quotes in echo.

but what if I want to
```
$`echo 'some "${quote}"'`
```

??

**Comment by antonmedv** [comment]
```
$`echo '${'some "' + quote + '"'}'`
```

**Comment by Morriz** [comment]
ok, thanks for the workaround...

but this also fails:
```ts
let bla
$`echo '${bla}'`
```
it shows `$`

**Comment by Morriz** [comment]
I suggest writing tests for those scenarios and fix these instances with pre/post processing to avoid the community hammering you with the same issues

**Comment by YDSS** [comment]
I have the same issue with @smeijer and I understand the concern about security, but I think you can provide a way to disable the enhancement of "Quotes" feature, in my case I only want to it behave as a normal template string.

**Comment by smeijer** [comment]
I've been thinking about the security concern. Maybe it can detect a `--dry-run` arg (or process.env var), and instead of executing the commands, only echo it? That way the user could dry run their script, and read if the commands line up with what they were expecting.

As a bonus, that would also make it quite easy to wrap our scripts with tests.

**Comment by apibrac** [comment]
As suggested by @YDSS, what about creting two commands to let the developper choose depending on its use case? Using the safe/unsafe keywords sometimes used in the web?

Use case 1: command's parameters are not safe, and adding quotes could prevent a security vulnerability
```javascript
$.unsafe`touch ${unsafe_file_name}`
```

Use case 2: command's parameters are controlled by the developper, we can (and want to) accurately plan the template string's output, no unexpected quotes are needed
```javascript
const safe_file_name = "foo"
$`touch ${safe_file_name}`
```

**Comment by Morriz** [comment]
I like that. Especially that the default `$` stays agnostic. Let us decide wether we are using a tool in a safe/unsafe context, and choose `$.unsafe` when we need it...

**Comment by antonmedv** [comment]
We already were thinking about the same API: https://github.com/google/zx/pull/151

But decided not to introduce it. It is dangerous and usually can be avoided altogether. 

If you really need a command from a string there is a solution: use `child_process` directly and provide safety on your own.

**Comment by smeijer** [comment]
I did post a workaround here using patch package. As you are hesitant to add any unsafe operators, I'm curious to why you've removed my comment that explained why I find the default behavior confusing, and contained a patch to disable quoting for those that need it.

**Comment by antonmedv** [comment]
Sorry for hesitation. I don’t want show users not save way of using library. Didn’t mean any disrespect though.

**Comment by Morriz** [comment]
really? that should not happen...and why do you decide what context we consider unsafe? please don't anticipate how users use it but instead add layered approach separating concerns, and add something like `$.safe` instead of the other way around

**Comment by antonmedv** [comment]
Rejecting a feature/or saying no to additional configuration is also a part of an API design.

**Comment by smeijer** [comment]
Definitely. I support your decision to not support unsafe operations. It's your project after all. I just simply don't get why my message sharing a workaround for those that do need it, got removed. But you explained it, and as I mentioned, your project, your issue tracker. So all fine now. :+1:

**Comment by Morriz** [comment]
> Rejecting a feature/or saying no to additional configuration is also a part of an API design.

Well, you have to be honest here and admit you are _adding_ functionality to try to do all that (buggy) safeguarding. It should be an option, not a forced decision.

**Comment by Morriz** [comment]
How can we escape regular bash constructs that don't need quoting? I get errors here:

```ts
const cmd = 'pwd && ls -als .'
```
which gives this error:
```
/usr/local/bin/bash: pwd && ls -als .: command not found
```
because, well, reasons...so we try the next:
```ts
...
const res = await $`${cmd.split(' ')}`
```
which translates to `pwd '&&' ls -als .`, so that is also not possible.

How on earth can we create commands up front so that zx doesn't escape special constructs like `&&` or `||` etc etc etc?

**Comment by dermicus-miclip** [comment]
this is still very annoying and not well documented. :(

**Comment by dermicus-miclip** [comment]
So... yeah, I commented to upvote this issue but google deleted it... Jeez.

**Comment by tigitz** [comment]
Main reason why I've switched from Makefile / bash scripts is to use the power of a programming language to make my commands building easier to manage.

From a DX perspective, this behavior is really surprising and quite frankly a blocker for adoption IMO, all the expected benefits of command building disappear
```js
const dcpProd = 'docker-compose -f /app/docker-compose.yml -f /app/docker-compose.prod.yml'
await $`${dcpProd + ' build'}` // doesn't work

await $`docker-compose -f /app/docker-compose.yml -f /app/docker-compose.prod.yml build` // works
```

I understand the security concerns but is there any solution that could make the above example works while still being secure ?

In the meantime, a workaround solution:
```js
const quoteEscaping = $.quote
$.quote = (command) => command

// run your unescaped commands

// reenable quote escaping
$.quote = quoteEscaping
```

**Comment by antonmedv** [comment]
```js
const dcpProd = 'docker-compose -f /app/docker-compose.yml -f /app/docker-compose.prod.yml'
await $`${dcpProd.split(' ') + ' build'}` // ✅ works
```

**Comment by tigitz** [comment]
@antonmedv I've tried the array approach however, unfortunately, it doesn't work.

![image](https://github.com/google/zx/assets/1524501/1e12fb55-444b-4a28-bbbd-f9c37a5e5181)

![image](https://github.com/google/zx/assets/1524501/faee0339-2a7e-46d0-883c-3750a07c3007)

I'm on the 7.2.2 version 

![image](https://github.com/google/zx/assets/1524501/202f408c-7c6d-4625-ab49-46878816e978)

**Comment by antonmedv** [comment]
![](https://user-images.githubusercontent.com/1524501/249279165-faee0339-2a7e-46d0-883c-3750a07c3007.png)

**Comment by tigitz** [comment]
OK now I get the confusion, I'm running `zx` on alpine where only `sh` is available and not `bash`.

Due to https://github.com/google/zx/blob/aef8209b06b19a6ccf54ad175b59802920d5aee4/src/core.ts#L77-L86 `zx` silently initialize with the default quote function that throws this error.

The error description links to https://github.com/google/zx/blob/main/docs/quotes.md which, AFAIU, describes the behavior of the quote function. Whis is not related to my case at all. It kinda mislead me to this issue.

@antonmedv Rereading the actual JS error helped me clear the confusion, thank you.

Ideally, `zx` should warn about the fact that no supported shell has been found and exit. Or let the execution continue but warn that it needs a quote function to properly function.

I'll try to make PR to improve DX in those cases.

**Comment by antonmedv** [comment]
> Ideally, zx should warn about the fact that no supported shell has been found and exit. Or let the execution continue but warn that it needs a quote function to properly function.

I like this idea. It will make it a better DX. Will implement correct error message in the zx v8.

**Comment by saravanakumar2504** [comment]
> Is there a way to bypass the quoting/escaping? It makes it impossible to create function arguments dynamically.
> 
> For example:
> 
> ```js
> const tarExcludes = ['.coverage', '.env.*', '.git', '.next', 'node_modules']
>   .map((x) => `--exclude='${x}'`)
>   .join(' ');
> 
> await $`tar -zcp ${tarExcludes} -f ../bundle.tgz .`;
> ```
> 
> I expect that to output:
> 
> ```
> $ tar -zcp --exclude='.coverage' --exclude='.env.*' --exclude='.git' --exclude='.next' --exclude='node_modules' -f ../bundle.tgz .
> ```
> 
> But instead, the output is:
> 
> ```
> $ tar -zcp $'--exclude=\'.coverage\' --exclude=\'.env.*\' --exclude=\'.git\' --exclude=\'.next\' --exclude=\'node_modules\'' -f ../bundle.tgz .
> ```
> 
> Which doesn't work. Needless to say, that doesn't have the expected result.

Did someone gets any fix on this ?

**Comment by smeijer** [comment]
I did, but they've removed my comment mentioning the workaround. Given that they stated they don't want me to share it, I don't think I should post it here again.

**Comment by antonmedv** [comment]
@smeijer  I did removed comment, instead of hiding it. Sorry. Don't remember the reason why I did it. Probably something with solution.

**Comment by antonmedv** [comment]
I'm going to put the solution here:

# The Solution

Read this https://google.github.io/zx/quotes

Here is what you can try:

```diff
const tarExcludes = ['.coverage', '.env.*', '.git', '.next', 'node_modules']
- .map((x) => `--exclude='${x}'`)
- .map((x) => `--exclude=${x}`)
  .join(' ');

await $`tar -zcp ${tarExcludes} -f ../bundle.tgz .`;
```

This will produce the next:

```bash
tar -zcp $'--exclude=.coverage' $'--exclude=.env.*' $'--exclude=.git' $'--exclude=.next' $'--exclude=node_modules' -f ../bundle.tgz .
```

This is totally okay to pass arguments to tar like this. In fact `tar` can't tell the difference between `$'--exclude=.env.*'` and `--exclude=$'.env.*'` as the $ is parsed in bash before even starting tar.

**Comment by ufondu88** [comment]
I am having issues with this problem. 

```javascript
const PR_TITLE = "Sample PR title"
const body = "Sample body"

try {
  await $`gh pr create --title=${PR_TITLE} --body=${body}`
} catch (error) {
  throw chalk.red(error.stderr);
}
```

will attempt to run this command
```
gh pr create --title=$'Sample PR title' --body=$'Sample body'
```
which is wrong. 

Expected output:
```
gh pr create --title='Sample PR title' --body='Sample body'
```
Does anyone know of a fix for this?

**Comment by MatMercer** [comment]
@ufondu88 see @tigitz answer, it works.
