### ISSUE TITLE
TypeScript definitions?

### ISSUE THREAD

**Issue by hhimanshu** [google/zx#165]
## Expected Behavior
Hello, I want to use it with TypeScript and wondering if you are planning to release Type definitions for `zx`. Do you folks have planned for it?

## Steps to Reproduce the Problem

1.
1.
1.

## Specifications

- Version:
- Platform:

**Comment by antongolub** [comment]
@hhimanshu,

It's already done: https://github.com/google/zx/blob/main/index.d.ts

**Comment by hhimanshu** [comment]
dang! Thank you @antongolub
