### ISSUE TITLE
Problem with quote like #164

### ISSUE THREAD

**Issue by PATROMO** [google/zx#169]
It looks like it is the same problem as #164 . Instead of dash it is now star.

## Expected Behavior

```
echo '

#!/usr/bin/env zx
let log_path = '/var/log/*.log'
$`cat ${log_path}`

' > test.mjs

zx test.mjs

$ cat /var/log/*.log
```

## Actual Behavior

```
echo '

#!/usr/bin/env zx
let log_path = '/var/log/*.log'
$`cat ${log_path}`

' > test.mjs

zx test.mjs

$ cat $'/var/log/*.log'
```

## Steps to Reproduce the Problem

1. npm i -g zx
2. Execute the lines I pasted before

## Specifications

- Version: 2.0.0
- Platform: macos

**Comment by antonmedv** [comment]
Well this is kind of by design. Zx escapes arguments. Same will not work with ~ char.
