### ISSUE TITLE
The following code parses incorrectly

### ISSUE THREAD

**Issue by qianyin925** [google/zx#171]
## Expected Behavior

- test.mjs

```js
#!/usr/bin/env zx

const commitMessage = '"fix: a bug"'
await $`git commit -m ${commitMessage}`
```

```shell
zx test.mjs

$ git commit -m '"fix: a bug"
```

## Actual Behavior

```shell
zx test.mjs

$ git commit -m $'"fix: a bug"'
```

## Steps to Reproduce the Problem

1. npm i -g zx
2. Execute the lines I pasted before

## Specifications

- Version: 2.0.0
- Platform: macos

**Comment by antonmedv** [comment]
This is expected. I will write better docs with explanation.
