### ISSUE TITLE
Unable to use shell special parameters in shell execution, example $0, $1, $$, etc.

### ISSUE THREAD

**Issue by AddictArts** [google/zx#172]
## Expected Behavior

Enable shell special parameters, such as
$1, $2, $3, ... are the positional parameters.
"$@" is an array-like construct of all positional parameters, {$1, $2, $3 ...}.
"$*" is the IFS expansion of all positional parameters, $1 $2 $3 ....
$# is the number of positional parameters.
$- current options set for the shell.
$$ pid of the current shell (not subshell).
$_ most recent parameter (or the abs path of the command to start the current shell immediately after startup).
$IFS is the (input) field separator.
$? is the most recent foreground pipeline exit status.
$! is the PID of the most recent background command.
$0 is the name of the shell or shell script.

```
await` $`echo $1`
```

echos the arg.

## Actual Behavior

It throws an exception that $1 is unbound.

## Steps to Reproduce the Problem

1. Execute the expected code above in any zx script.

**Comment by antonmedv** [comment]
I didn’t get it.

**Comment by AddictArts** [comment]
Shell scripts often evaluate `$1` etc special parameters. zx is invoking using a shell. so we should be able to duplicate this.

Example:
```
$echo $$
29949
```
So,

```
await $`echo $$`
```

should also work, right?

**Comment by antonmedv** [comment]
await $`echo $$` and you will get pid of created shell process. This is how it’s working. $ spawns a new shell process every time.

**Comment by AddictArts** [comment]
Bad example, see revised version with the error Error: /bin/bash: $1: unbound variable

**Comment by antonmedv** [comment]
Again, it’s another shell.

**Comment by AddictArts** [comment]
> Again, it’s another shell.

Yes, however you don't get an error when doing the same in the shell.

```
% /bin/bash -c "echo $1"

```

No error, so zx should not error either I would thing. Also, positional shell variables should be viable in the script like executing `$ ls -l $1` for example like a shell script.

**Comment by antonmedv** [comment]
See documentation for [$.prefix](https://github.com/google/zx#prefix) (note set -u).

 Two options:
```js
zx <<< '$`echo \${1-default}`'
```

Or 
```js
zx <<< '$.prefix = ""; $`echo $1`'
```

**Comment by AddictArts** [comment]
Perfect, thanks, didn't see the relationship. Thanks
