### ISSUE TITLE
how can I use zx in nestjs

### ISSUE THREAD

**Issue by Innei** [google/zx#174]
How can I use zx mjs in nestjs.

## Expected Behavior

Can complie in typescript. No runtime error.

## Actual Behavior

If use as commonjs module, get this.
![image](https://user-images.githubusercontent.com/41265413/127735734-c110eae4-0e3f-4e69-be4f-ad3ece668fdd.png)

If use `type: module` in `package.json`, and change tsconfig to `target: es2020`, get this.
![image](https://user-images.githubusercontent.com/41265413/127735772-af96d06e-e96d-4d75-8930-bdb89ab7a99a.png)

## Steps to Reproduce the Problem

https://github.com/Innei/nestjs-zx-reproduction

## Specifications

- Version: 2.0.0
- Platform: macOS 11.4, node 16

**Comment by antonmedv** [comment]
Looks like not related to zx, but to your build process. Closing it as not relevant.
