### ISSUE TITLE
Glob patterns

### ISSUE THREAD

**Issue by zloirock** [google/zx#175]
[Glob patterns](https://en.wikipedia.org/wiki/Glob_(programming)) seriously simplify the work with the file system and are used very often. But sometimes I prefer to write some more additional lines and avoid it since the usage of glob patterns requires import and adding a package to dependencies. It could be good to add support of glob patterns to `zx`.

The best option is to have it on `fs-extra` side, but [the issue](https://github.com/jprichardson/node-fs-extra/issues/318) about the support of glob patterns was closed in their repo.

I think that it could be good just to add a package for work with glob patterns with a simple promise-based interface, like [`globby`](https://github.com/sindresorhus/globby), and expose it as a global variable.

**Comment by antonmedv** [comment]
I also was thinking about it. Globby looks nice. (As all Sindre packages). Any other alternatives just to compare?

**Comment by antongolub** [comment]
fast-glob?
