### ISSUE TITLE
Running scripts without extensions errors if they are on a RO filesystem

### ISSUE THREAD

**Issue by NobbZ** [google/zx#176]
## Expected Behavior

No error when running a script without extension from a read only filesystem.

## Actual Behavior

An error when running a script without extension from a read only filesystem.

```
$ /nix/store/yaw3zrrdjs1y73kgqspk3mj12mc7i4vl-nobbz-flake-updater-0.0.1/bin/update
internal/process/esm_loader.js:74
    internalBinding('errors').triggerUncaughtException(
                              ^

[Error: EROFS: read-only file system, open '/nix/store/yaw3zrrdjs1y73kgqspk3mj12mc7i4vl-nobbz-flake-updater-0.0.1/bin/update.mjs'] {
  errno: -30,
  code: 'EROFS',
  syscall: 'open',
  path: '/nix/store/yaw3zrrdjs1y73kgqspk3mj12mc7i4vl-nobbz-flake-updater-0.0.1/bin/update.mjs'
}
```

## Steps to Reproduce the Problem

1. Create a `xz` script without extension but with proper shebang on a read-only filesystem
1. run it
1. see the error

## Specifications

- Version: 2.0.0
- Platform: linux (NixOS)

**Comment by antonmedv** [comment]
In order to run it, zx create in same folder file with + .mjs extension. So file system should be writable.

**Comment by NobbZ** [comment]
Even for FHS linux this is a very hard limitation.

This basically disallows installing ZX scripts (without aa filending) at the system level, eg. in `/usr/{,local/}bin`, as even though FS isn't RO there, though still not allowed to be written to for most users, and probably result in `EACCES`.

The file could as well be written to `$TMP`, `$XDG_CACHE_HOME`, `$XDG_RUNTIME_DIR`, depending on what exactly this file is meant to represent.

Currently I'm helping myself by having the `*.mjs` script somewhere else and an actual executable file that basically is just `exec xz /nix/store/…/lib/script.mjs`.

**Comment by NobbZ** [comment]
Thats in general an understandable limitation. Is there any technical reason for renaming the file at all?

**Comment by antonmedv** [comment]
Nodejs can't import or require it without extension.

**Comment by Dunky13** [comment]
It actually can: https://nodejs.org/docs/latest-v14.x/api/esm.html#esm_customizing_esm_specifier_resolution_algorithm

As you can see 14+ can definitely import without extension, albeit with an experimental tag

**Comment by NobbZ** [comment]
My current use case doesn't involve any require or import at all, yet. Though currently I prefer the manual wrapping I currently do over using an experimental feature of a runtime I am not used to use.

I'm not very keen on writing JavaScript, and usually write just bash or python.

Though the scripts I want to write are just complex enough to be annoying to write and "test" in bash, while at the same time does not justify to fire up the machinery required for a python script on NixOS, as I always need to make it a proper project with `setup.py` or `pyproject.toml` (and also "shelling out" in python is ugly without extra libraries).
