### ISSUE TITLE
using path.join and the zx didnt work well: $ cd  $'C:\\Users\user1\...' 

### ISSUE THREAD

**Issue by radiorz** [google/zx#182]
I use path.join in my script 
```
const toDir = path.join(__dirname,toDir)
await $`cd ${toDir}`
```
and turn out :
```
cd  $'C:\\Users\user1\...' 
```
instead of 
```
cd  C:\\Users\user1\...
```
how can i use the full path in zx ,please help me !

**Comment by antonmedv** [comment]
The `cd  $'C:\\Users\user1\...'` is the same as `cd  C:\\Users\user1\...`.
