### ISSUE TITLE
Support to read and write YAML files

### ISSUE THREAD

**Issue by bobvanderlinden** [google/zx#183]
## Expected Behavior

I expect a general scripting tool to read and write most of the popular configuration files. This includes YAML files.

## Actual Behavior

This behavior doesn't seem available (or documented).

## Specifications

- Version: 2.0.0
- Platform: Linux

**Comment by davidharrigan** [comment]
Just curious why this was closed. Seems like it would be a nice addition. I don't seem to be able to import any third party packages that are globally installed. Is there no plan to support this?

**Comment by antonmedv** [comment]
You can import global packages. Check your NODE_ROOT config.
