### ISSUE TITLE
empty var gets rendered as $''

### ISSUE THREAD

**Issue by Morriz** [google/zx#184]
## Expected Behavior
```
var bla
$`echo ${bla}`
```
Should print nothing

## Actual Behavior

It prints `$''`

## Specifications

- Version: 2.0.0 (actually @master of aug 10)
- Platform: bash@4

**Comment by mrchief** [comment]
This is probably due to [quoting](https://github.com/google/zx/blob/main/index.mjs#L245). For a possible solution, see #187

**Comment by antonmedv** [comment]
Fixed.
