### ISSUE TITLE
colon in variable value causes unexpected output

### ISSUE THREAD

**Issue by mrchief** [google/zx#187]
## Expected Behavior

```
const details = ':ac';
await $`echo ${details}`;

echo :ac
```

## Actual Behavior

```
echo $':ac'
```

## Specifications

- Version: 2.1.0
- Platform: bash

**Comment by antonmedv** [comment]
This is expected. This is part of quoting. Will write a doc about it.

**Comment by mrchief** [comment]
This happens for most punctuations also like `%`, `{`, `*`, `<` and possibly more.

I'm trying to emit markdown strings as part of JSON and assign them to env vars (using it in github actions) so the `$'...'` is causing bash scripts to completely break down as the single quotes are interpreted different by shell.

How can we escape this behavior?

**Comment by mrchief** [comment]
Something like this?

```
$.quote = arg => arg.replace(/\n/g, '\\n').replace(/`/g, '\\\`')
```

works in my case as those are the only things I need to worry about.
