### ISSUE TITLE
Colors not working correctly

### ISSUE THREAD

**Issue by herecydev** [google/zx#193]
## Expected Behavior

Using git bash, running a command like `gatsby develop` produces:

`success onPreInit - 0.037s`

Where the "success" word is colored green.

## Actual Behavior

Running within zx the following is produced:

`←[2K←[1A←[2K←[Gsuccess onPreInit - 0.030s`

## Steps to Reproduce the Problem

1. run the following from within zx and git bash

```
await $`gatsby develop`
```

## Specifications

- Version: 3.0.0
- Platform: Windows

**Comment by antonmedv** [comment]
Clarify what do you use on windows. Cmd.exe, WSL, git-bash, etc?

**Comment by herecydev** [comment]
I mentioned in there I was using git-bash to execute zx

**Comment by antonmedv** [comment]
Works on macOS. I don’t have a windows to debug.

**Comment by antonmedv** [comment]
It all depends on the subprocess. How subprocess detects color support in the terminal. 

Try to add env var COLOR/FORCE_COLORS/etc.

```js
process.env.COLOR=true
```
