### ISSUE TITLE
Cant use Typescript files | Unknown file extension ".ts"

### ISSUE THREAD

**Issue by Eggwise** [google/zx#194]
## Expected Behavior
Should be able to use typescript .ts files

## Actual Behavior

TypeError [ERR_UNKNOWN_FILE_EXTENSION]: Unknown file extension ".ts" for /project/FILE.ts

## Steps to Reproduce the Problem

```
touch test.ts
zx test.ts
```

## Specifications

zx version: both 3.0.0 and 2.1.0
Platform: macbook m1
Now using node v15.14.0 (npm v7.7.6)

using nvm to manage node versions

**Comment by Eggwise** [comment]
Zx was using old GLOBAL npm package instead of dev dependency zx

**Comment by thomaslevesque** [comment]
@Eggwise Could you elaborate? I'm also getting this error.
Can I run TypeScript scripts with the globally installed `zx` package or not?

**Comment by codenoobforreal** [comment]
getting this error too afte following the typescript documentation.

**Comment by brunobely** [comment]
+1 getting this issue with globally installed and locally installed package with `pnpm`
