### ISSUE TITLE
How to make cd works in windows, such as ```cd H:\\``` will go to H drive?

### ISSUE THREAD

**Issue by radiorz** [google/zx#195]
## Expected Behavior
 ```cd H:\\``` will go to H drive?

## Actual Behavior
```
$ cd H:\
/bin/bash: line 1: cd: H:\: No such file or directory
```
## Steps to Reproduce the Problem

1. I installed  zx at global with yarn 
2. and create a simple js file: 
```
$`cd H:\\`
```
3. I can use this shell in powershell .
4. But the error turn out: no such file or directory 

## Specifications
just go to H drive...
- Version: 2.0.0
- Platform: windows 10

**Comment by radiorz** [comment]
I try to use function cd but it still dont work like this:
```
import path from 'path'
const dirs = ['a']
 const projectdir = path.resolve(`./${dirs[0]}`)
     cd(projectdir)
await $`pwd`
```
this script turn out like this:
```
$ cd H:\work\code\a
$ pwd
/root
```

**Comment by radiorz** [comment]
The H drive is a U Disk

**Comment by MarkosKon** [comment]
Try `cd /h/` for mingw64 (Git bash) or `cd /mnt/h/` for WSL.

**Comment by antonmedv** [comment]
Use `cd()` function.
