### ISSUE TITLE
How to execute a pure string command?g++ wrapped  with $''

### ISSUE THREAD

**Issue by ahaoboy** [google/zx#196]
Is there a api to execute a pure string command? 
like: $.exec('sudo apt install default-jre gcc g++ -y')

## Expected Behavior
```
sudo apt install default-jre gcc g++ -y
```

## Actual Behavior
```
sudo apt install default-jre gcc $'g++' -y
```

## Steps to Reproduce the Problem
```
import { $ } from "zx";

const common_str = [
    "default-jre",
    "gcc",
    "g++",
  ]

// sudo apt install $'default-jre gcc g++' -y
await $`sudo apt install ${ common_str.join(' ') } -y`


// sudo apt install default-jre gcc $'g++' -y
await $`sudo apt install ${ common_str } -y`
```

## Specifications

- Version: 3.0.0
- Platform: ubuntu2104

**Comment by antonmedv** [comment]
> await $`sudo apt install ${ common_str } -y`

This is correct solution. Quotes around g++ are intentionally, by design. 

I’ll write a better docs to clarify it.

**Comment by antonmedv** [comment]
Done.
