### ISSUE TITLE
I'm sorry, but isn't the start of your README unkind to a new user

### ISSUE THREAD

**Issue by jradxl** [google/zx#202]
## Expected Behavior
The code examples in the first few lines of the README should execute without error

## Actual Behavior
Putting the example code into script.mjs and executing errors with:
(a) no package.json
(b) no dep executable

test.mjs fails
(a) no wtf executable

## Steps to Reproduce the Problem
See above

## Specifications
Your latest version from here.

## Comments
Heard of this program from a recent podcast from ChangeLog

Surely I am not alone in seeing your code example at start of README and appreciating what it is, and then go to try it...
Why would you use DEP as an example which is from deployer.org and requires a deploy.php
Together in a git project with a package.json
ALL without mentioning this prior to the example!

If you mean the example of observation only, perhaps you should mention it, or alternatively start with the following sentence...

"Assuming you have a Git project containing a package.json and having installed wft from bsdgames and dep from deployer.org, and having prepared a deploy.php with dep init, then the following example gives an example of its use"

If I try your test.mjs
Why would you use WFT  which is available on Ubuntu from bsdgames package, without mentioning it's necessary

Such might encourage a new user to use your project.

**Comment by antonmedv** [comment]
Those example at beginning on README.md indeed only observatory. 

I used the dep command as I’m also a deployer.org author. 

The wtf command used as an example of wrong command which throws exception.
