### ISSUE TITLE
[Windows; Git Bash] Colorize failed after first command

### ISSUE THREAD

**Issue by NeoJRotary** [google/zx#207]
## Expected Behavior
Colorize always work 

## Actual Behavior
![image](https://user-images.githubusercontent.com/24691636/131061785-55e3b133-63ef-4263-8d17-223a980257b7.png)

## Steps to Reproduce the Problem
```
console.log(chalk.green('0'));
console.log(chalk.blue('1'));
await $`echo 1`;
console.log(chalk.blue('1'));
await $`echo 2`;
```

## Specifications

- Version: 3.1.0
- Platform: Windows 10 ( Git bash )

**Comment by imdbere** [comment]
I am having the same issue on Cygwin on Windows, can you give me any more details on how you solved it ?
Thanks !

**Comment by ZiiMakc** [comment]
Same problem, aby ideas why?

**Comment by eco747** [comment]
it seem that's a problem in chalk.
the problem can be resolved with env variable FORCECOLOR = true

**Comment by eco747** [comment]
here is a solution:

create a new function;

```js
function $$( ...args ) {
	const r = $.call( null, ...args );
	r.stdin;	// force _inheritStdin = false
	return r;
}
```

and call `$$` instead of `$`.

**Comment by gbreeze** [comment]
``` js
#!/usr/bin/env zx
$.shell = `C:/Program Files/Git/bin/bash.exe`

const $$ = $
function windowsFixes(...args) {
    const r = $$.call(null, ...args)
    // https://github.com/google/zx/issues/207
    r.stdin	// force _inheritStdin = false
    return r
}
$ = windowsFixes

import 'zx/globals'

await $`pwd`
```
