### ISSUE TITLE
Weird bug, symbol link of mjs file will remove linked dest

### ISSUE THREAD

**Issue by junchih** [google/zx#208]
## Expected Behavior

After called the symbol link of script, the original script remain existing.

## Actual Behavior

After called the symbol link of script, the original script has been removed.

## Steps to Reproduce the Problem

1. install nix-shell
2. install direnv
3. clone and step in https://github.com/junchih/tastes/tree/master/zx/bug/bin, with `direnv allow`
4. successful command `./ok && ls -alh .`
5. issue command `./hello && ls -alh .`

### Noticed

the symbol link file `hello` got same base name of the zx script `hello.mjs`, which got issue. and symbol link `ok` behaves ok.

## Specifications

- Version: 3.1.0
- Platform: macOS 10.15 + nixpkgs 21.05
- Nodejs: 14.17.0

**Comment by Dunky13** [comment]
Node is able to do so using: [experimental-specifier-resolution](https://nodejs.org/docs/latest-v14.x/api/esm.html#esm_customizing_esm_specifier_resolution_algorithm) albeit experimental.

**Comment by antonmedv** [comment]
We can use it as soon it will be stable. But right now is there somebody want to fix this bug?

**Comment by Ivraj** [comment]
Hi @antonmedv. I'd be happy to put in a fix if no one else has already picked it up.

**Comment by Ivraj** [comment]
A sufficient solution should be to write to a tmpdir when calling `writeAndImport` in `importPath`, similar to the implementation of `scriptFromStdin` or `scriptFromHttp`, correct? If so, I can go ahead and put in a PR with that fix. But if I'm mistaken or you have a better solution in mind, let me know.

**Comment by antonmedv** [comment]
It should be on the same dir, otherwise node_modules and imports will not work.

**Comment by Ivraj** [comment]
Oh, gotcha. So instead of a tmpdir, maybe just make the `filepath` arg being passed into `writeAndImport` on line `105` unique? There shouldn't be any issue with that, right?

**Comment by Ivraj** [comment]
As a side note, I got the project set up locally, but was having trouble getting the tests to successfully run on a fresh install. Tracking the issue separating [here](https://github.com/google/zx/issues/273).

**Comment by Ivraj** [comment]
@antonmedv Added a WIP PR with the change I described. Let me know if a solution like that is all good, or whether there's anything I'm overlooking.
