### ISSUE TITLE
No colors and control characters in output of $`` calls

### ISSUE THREAD

**Issue by p3k** [google/zx#212]
## Expected Behavior

Commands called via <code>$``</code> should output colors and control characters the same way the commands do when called directly from the command line.

![image](https://user-images.githubusercontent.com/16631/131642154-27a4ae5f-9e27-4923-8d0d-4a97d545464d.png)

![image](https://user-images.githubusercontent.com/16631/131642340-951260a1-d26b-4b9e-bcb0-47fe1c46a046.png)

## Actual Behavior

Colors and control characters are missing, output looks unfortunate.

![image](https://user-images.githubusercontent.com/16631/131642575-2ff476e0-3ecb-4341-a946-e0426295495b.png)

![image](https://user-images.githubusercontent.com/16631/131642927-aa492976-e857-4373-9644-0a08c877f128.png)

## Steps to Reproduce the Problem

1. Run `yarn foobar` from the command line (causing an error)
1. Get colorized output as in first screenshot above
1. Create test.mjs file with the following content:
    ```sh
    #!/usr/bin/env
    nothrow($`yarn foobar`)
    ```
1. Run `zx test.mjs` from the command line
1. Get same output without colors (except the first line) as in third screenshot above

Similar ways to reproduce this:

* Running Storybook from within a zx script (see other screenshots)
* Running webpack from within a zx script

## Specifications

- Version: 4.0.0
- Platform: Ubuntu 18.04.5 LTS

**Comment by p3k** [comment]
oh sorry, now i found a solution *after* filing this issue:

in https://github.com/google/zx/issues/124#issuecomment-898469918 a suggested fix is to add `process.env.FORCE_COLOR=3` to the script.

this works for me, but before closing this issue i’d like to suggest to add this to a prominent place in the documentation (if not configures this by default) – the amount of similar issues is telling (and a bit of a shame for myself).

**Comment by p3k** [comment]
ah yes this only adds the colors again to the output – is there a similar setting for the control characters?

(i am not sure i am using the correct word; what i mean is that e.g. in webpack a progress indicator appears and is updated on the same line. so instead of outputting multiple lines with 1%, 2%, 3% and so on, this all should happen on one and the very same line.)

**Comment by p3k** [comment]
@antonmedv if i run webpack using this `spawn()` call, i get colors and the desired progress bar:

```js
import { spawn } from "child_process";
spawn(
  "yarn", 
  ["webpack", "--progress",  "--config", "client/apps/compat/polyfill-config.js"],
  { stdio: [0, 1, 2] }
);
```

would it be possible to modify the corresponding line in zx’s code, accordingly or in a similar manner?

https://github.com/google/zx/blob/3f7e8fe37b3e400c018fc1d8a88968ba4db1d325/index.mjs#L83

**Comment by antonmedv** [comment]
If [0,1,2] means inherit. We use piped mode to capture output. Can’t have both.

**Comment by p3k** [comment]
> If [0,1,2] means inherit. We use piped mode to capture output. Can’t have both.

ok… not even via a configuration switch, something like `$.pipe = [true | false]`?

(when simply replacing line 83 for the `inhert` mode i noticed an stdio even error as well as the script not being interruptable properly, anymore… so i assume there is more to be done than just adding the switch and a corresponding conditional check?)

**Comment by antonmedv** [comment]
It is more like API design problem.

**Comment by p3k** [comment]
> It is more like API design problem.

meaning? too much effort needed for a feature out of scope of this project?

**Comment by antonmedv** [comment]
Rejecting a feature/or saying no to additional configuration is also part of an API design.
