### ISSUE TITLE
is there a way to install by yum,apt?

### ISSUE THREAD

**Issue by stone-jin** [google/zx#213]
## Expected Behavior

then we can use to install in dockerfile ?

like: 

```
FROM centos

RUN yum install zx -y 
```

## Actual Behavior

current it is installed by `npm install`;

**Comment by antonmedv** [comment]
Why?

**Comment by stone-jin** [comment]
so that one day, zx can like shell, we can use zx without install.  replace the shell

**Comment by antonmedv** [comment]
Zx calls shell.
