### ISSUE TITLE
Importing of TS files generate .js files

### ISSUE THREAD

**Issue by Egaro555** [google/zx#215]
## Given
```ts
// utils.ts

export const add = (a: number, b: number) => a + b
```

```ts
// index.ts

import 'zx'

import { add } from './utils'

console.log(add(1,1))
```
```
zx index.ts
```

## Expected Behavior
No files created

## Actual Behavior
utils.js was created

## Specifications

- Version: 4.1.1
- Platform: Linux (Ubuntu)

**Comment by antonmedv** [comment]
¯\\\_(ツ)\_/¯


Try to use ts-node instead.
