### ISSUE TITLE
When a string in an array ends with '/', the variable is not passed correctly.

### ISSUE THREAD

**Issue by enoatu** [google/zx#216]
## Expected Behavior
Even if a string in an array ends with '/', it is passed to the argument  correctly.

## Actual Behavior
When a string in an array ends with '/', the variable is not passed correctly.

## Steps to Reproduce the Problem
```
let args = [
  '-ri',
  '--exclude-dir=node_modules/',
  'license',
  '.'
]
await $`grep ${args}`
```
=> This result  includes node_modules.

```
let args = [
  '-ri',
  '--exclude-dir=node_modules',
  'license',
  '.'
]
await $`grep ${args}`
```
=> This result doesn't include node_modules.

## Specifications

- Version: 4.1.1
- Platform: macOS Big Sur 11.5.2

**Comment by antonmedv** [comment]
What is executed command? Run in verbose mode.

**Comment by enoatu** [comment]
Thank you for your reply.
Here is excuted command.
```
$ grep -ri $'--exclude-dir=node_modules/' license .
```
However, I was wrong.
This problem was due to a difference in the grep I had installed. 
I have GNU grep installed on macOS, but the grep run by zx is a BSD grep, so it behaves differently.
