### ISSUE TITLE
Automatic retry

### ISSUE THREAD

**Issue by JAForbes** [google/zx#219]
It would be cool if shell commands could automatically retry.

```js
await $`ssh ${ip}@${host} -c ${command}`
  .retry(5)
  .throttle(5000)
```

**Comment by antonmedv** [comment]
This is easily implemented on user side.

**Comment by JAForbes** [comment]
But its a pretty common scenario for deploy scripts.  Should it be implemented in userland every time?

**Comment by antonmedv** [comment]
Solution:
```js
while (await $`ssh ${host} - ${command}`.exitCode !== 0) {
  await sleep(5000)
}
```

**Comment by antonmedv** [comment]
Or with retry count:
```js
for (let attempt = 1; attempt <= 5; attempt++) {
  if (await $`ssh ${host} - ${command}`.exitCode === 0) break
  await sleep(5000)
}
```

**Comment by JAForbes** [comment]
They aren't great solutions, for one, what if I want the result of the command, not just performing a side effect.  That is arguably the most common case.

Let's say you are using a remote docker host, and every single docker command you run initiates a new SSH connection, and the remote connection is rate limited, and there's concurrent access.

Every single command will require retries.  It is a more common case than other conveniences zx offers right?

**Comment by antonmedv** [comment]
Well, we can think of something like this for zx. Maybe builtin `retry()` function, or similar.

**Comment by JAForbes** [comment]
Yeah a built-in could work.  Do you prefer keeping the `ProcessPromise` interface as simple as possible?

I was thinking chaining on the template expression to make it easier to toggle via comment when debugging.

**Comment by antonmedv** [comment]
Yes, I'd like to keep ProcessPromise simple as possible. I was thinking about next API:
```js
function retry(maxAttempts = 10, retryDelay = 500) {
  return async function (p) {...}
} 

// Usage:

let out = await retry(5)($`ssh host cmd`)
```

**Comment by JAForbes** [comment]
I'm happy with that API.  Only thing I'm not sure about is how comfortable your users will be with currying.

Maybe as an alternative, or in addition, we could take inspiration from `$.verbose` / `$.prefix`:

```js
$.retry = 0

await $`ls xyz`

$.retry = 5

await $`aws s3 cp ...`
await $`terraform apply ...`

$.retry = { attempts: 10, delay: 3000 }

await $`ssh ...`
await $`scp ...`
```

Technically not as powerful because you can't have different delays for different commands running in parallel, but in a scripting environment that is probably fine?

**Comment by antonmedv** [comment]
I think my solution is more readable. I don't think it's difficult to JS devs. Function can return functions.

**Comment by JAForbes** [comment]
Ok great

**Comment by JAForbes** [comment]
A retry function I'm using right now has an optional 3rd argument which evaluates if an error can be ignored or exit early instead of simply retrying https://github.com/JAForbes/swarm-test/blob/main/run.js#L5

Not sure if that's a general pattern, but it's come in handy in this context.

**Comment by antonmedv** [comment]
There is plenty of good libs for retries. 

For example https://github.com/sindresorhus/p-retry

I don’t think we need to provide it by default at this point.
