### ISSUE TITLE
Cannot parse variables properly

### ISSUE THREAD

**Issue by xiyangjun** [google/zx#221]
const repo = {id: 123, branch: 'feat/test'};
const branch = encodeURIComponent(repo.branch);
$\`curl http://xxx.com/api/${repo.id}/${branch}/download`

## Expected Behavior
curl http://xxx.com/api/123/feat%2Ftest/download

## Actual Behavior
curl http://xxx.com/api/123/$'feat%2Ftest'/download

## Steps to Reproduce the Problem

1.
1.
1.

## Specifications

- Version: 4.2.0
- Platform: macOS 10.15.7 
- node: v14.17.6

**Comment by antonmedv** [comment]
https://github.com/google/zx/blob/main/docs/quotes.md
