### ISSUE TITLE
Bug: prints ZX version number when not desired

### ISSUE THREAD

**Issue by sparebytes** [google/zx#222]
## Expected Behavior
`zx ./my-script.mjs -v` will execute `my-script.mjs` and pass `-v` as an argv.

Similar to how the node cli behaves when running `node ./my-script.mjs -v`

## Actual Behavior
zx does not execute my script and prints out the version number

## Specifications

- Version: 4.2.0
- Platform: MacOS 11

**Comment by antonmedv** [comment]
Will. This is expected behaviour.

**Comment by paynecodes** [comment]
I just ran into this as well. I expect my scripts to be able to accept a `--version` and/or `-v` arg without `zx` processing it all.

**Comment by danbulant** [comment]
Maybe it should process them same as node itself does?
`zx -v script` -> shows `zx` version.
`zx script -v` -> passes `-v` as argument to script

**Comment by scottdotau** [comment]
I've run into this too. It happens when you run the script via `. /cli.mjs --version/-v` too, making it impossible for you to create your own version output using these flags, in for example, your own CLI.

**Comment by antonmedv** [comment]
Fixed in 3f7c8ca083ebe372f4f7f67b605720faaf4fbd04
