### ISSUE TITLE
cd does not work as expected

### ISSUE THREAD

**Issue by sparebytes** [google/zx#223]
## Expected Behavior

Overall I expect `cd` to act exactly like `process.chdir` which produces behavior similar to an equivalent bash script.

1. `cd(".."); cd("..")` should go up two directories
2. `cd("/home"); console.log(process.cwd())` should print `/home`

## Actual Behavior

1. `cd(".."); cd("..")` goes up only one directory
2. `cd("/home"); console.log(process.cwd())` does not print `/home`

## Specifications

- Version: 4.2.0
- Platform: Mac OS 11

**Comment by younesmln** [comment]
Any news on this one? would be very helpful to support relative paths.

**Comment by antonmedv** [comment]
Fixed with 5f54045ec3ea4c7d7a7be5a67e01a197de132515
