### ISSUE TITLE
const str = 'git pull' ;$`${str}`;  Does not meet expectations

### ISSUE THREAD

**Issue by achuanVVVVV** [google/zx#224]
## Expected Behavior
```js
const str = 'git pull'
$`${str}`; 
// I think he should execute "git pull"
```
## Actual Behavior
stdout:
//But in fact it didn’t execute and threw an error 
/bin/bash: git pull: command not found

## Steps to Reproduce the Problem

![image](https://user-images.githubusercontent.com/72929561/132680140-8f0bf506-3ede-47af-9e94-6e2fdfe4eff2.png)

## Specifications

- Version:node 12
- Platform: macos (drawin)

**Comment by antonmedv** [comment]
https://github.com/google/zx/blob/main/docs/quotes.md

**Comment by ricardodantas** [comment]
@achuanVVVVV how did you solve that?

**Comment by ptrxyz** [comment]
Also interested. Can it be done somehow?

**Comment by antonmedv** [comment]
const str = 'git pull'
$`${str.split(‘ ‘)}`;

**Comment by ptrxyz** [comment]
> Question: why do you need it for?

I wanted to parse a file that contains shell commands to be executed. So I read the file line by line, do some operation on the lines (simple string replacement) and then execute them one by one. :man_shrugging:

**Comment by antonmedv** [comment]
Zx can print commands on its own.
