### ISSUE TITLE
how to iterate over multi-line string?

### ISSUE THREAD

**Issue by iphpdonthitme** [google/zx#226]
This may be a simple question, but I wasn't able to find a similar example.

A common thing for me to do is to use the AWS cli for various tasks, for example, get some s3 bucket names and then check attributes on those buckets. Bash looks like

```
BUCKETS=$( aws s3 ls | grep subset | awk '{print $3}' )
for b in $BUCKETS; do
  BUCKET_REGION=$(aws s3api get-bucket-location --bucket ${b} | jq -r '.LocationConstraint)
  if [[ $BUCKET_REGION == "null" ]] ; then
     BUCKET_REGION=us-east-1
  fi
  echo "$b $BUCKET_REGION"
done
```

How would I do the equivalent in zx? This works but seems kinda verbose.
```
import 'zx/globals'
$.verbose = false

let BUCKETS_OUTPUT = await $` aws s3 ls | grep subset | awk '{print $3}' `
let buckets = BUCKETS_OUTPUT.stdout.match(/.+/g) // also works but equally verbose: .split(/\r?\n/).filter(n => n)
for(const b of buckets) {
    let BUCKET_REGION_OUTPUT = await $` aws s3api get-bucket-location --bucket ${b} | jq -r '.LocationConstraint' `
    let bucketRegion = 'us-east-1'
    if ( BUCKET_REGION_OUTPUT.stdout !== 'null\n' ) {
        bucketRegion = BUCKET_REGION_OUTPUT.stdout.match(/.+/g)
    }
    console.log(`${b},${bucketRegion}`)
}
```

At https://blog.mastykarz.nl/create-scripts-javascript-zx/, I saw an example using JSON.parse so tried that, and it works with a different kind of verbosity.

```
import 'zx/globals'
$.verbose = false

let buckets = JSON.parse( await $`aws s3api list-buckets --output json | jq -r '.Buckets | .[] | select (.Name|test("subset")) | .Name' | jq -s -R -r 'split("\n")|map(select(. != ""))'` )

for(const b of buckets) {
    let BUCKET_REGION_OUTPUT = await $` aws s3api get-bucket-location --bucket ${b} | jq -r '.LocationConstraint' `
    let bucketRegion = 'us-east-1'
    if ( BUCKET_REGION_OUTPUT.stdout !== 'null\n' ) {
        bucketRegion = BUCKET_REGION_OUTPUT.stdout.match(/.+/g)
    }
    console.log(`${b},${bucketRegion}`)
}
```

Is there a less verbose way to grab and iterate through the s3 buckets?

**Comment by antonmedv** [comment]
Both ways are valid. Choose whatever your prefer.

**Comment by iphpdonthitme** [comment]
Thought about this some more, and I think the real question is the trailing newline in `$command`. Many moons ago I saw the 
"10.5 Capturing a commands output" example at https://tldp.org/HOWTO/Bash-Prog-Intro-HOWTO-10.html#ss10.5 
```
        #!/bin/bash
        DBS=`mysql -uroot  -e"show databases"`
        for b in $DBS ;
        do
                mysql -uroot -e"show tables from $b"
        done
```
Only now have I realized that bash deletes the trailing newline of command substitutions https://www.gnu.org/software/bash/manual/html_node/Command-Substitution.html#Command-Substitution

By contrast, child_process.spawn() retains the trailing newline https://nodejs.org/dist/latest-v14.x/docs/api/child_process.html#child_process_child_process_spawn_command_args_options.

I don't think in my experience of using bash I have ever missed the trailing newline, and I think generally it's better to delete it. Perhaps there should be a new boolean setting $.trailingnewline ?

**Comment by antonmedv** [comment]
I think keeping unmodified output of program is preferable. 

And zx also do command substitution:

```js
let p = await $`echo Hello`  // With newline and the ned.
await $`echo ${p}, world!` // The zx understands what new line should be trimmed.
```

And it's really easy to get rid of `\n` if you need it in JS:

```js
let str = p.stdout.trim()
```
