### ISSUE TITLE
Refactor zx.mjs internal utils to utils.mjs

### ISSUE THREAD

**Issue by linonetwo** [google/zx#229]
## Expected Behavior

Users can use these utils to call zx programmatically.

## Actual Behavior

zx.mjs can not be `require()`, so its dependencies can't be properly bundled into an electron app.

## Steps to Reproduce the Problem

1. In an electron app, try `child_process.fork(locationOfZxMjsFile)`
1. where locationOfZxMjsFile is in electron's resources folder, we copy zx from node_modules to bundled electron app's resource folder just before release.
1. it errors `fs-extra` not found

The solution can be let user require utils in `zx.mjs` and call them programmatically, instead of using `fork`

**Comment by linonetwo** [comment]
Use 

```bash
cd node_modules/zx && npm i --legacy-building
cd node_modules/zx/node_modules/globby && npm i --legacy-building
```

fixes this.

**Comment by linonetwo** [comment]
Reopen，if this gets solved, we can solve https://github.com/google/zx/issues/231

**Comment by antonmedv** [comment]
Refactor what? Purpose?

**Comment by linonetwo** [comment]
I want to write my custom logic to implement #231 in my electron app, so I hope I can import functions currently inside `zx.mjs` file.

**Comment by antonmedv** [comment]
Suggest changes.

**Comment by linonetwo** [comment]
Oh, I see you close my 2 issue and 1 PR , can you leave comment why?

**Comment by antonmedv** [comment]
Yes, I decided not to merge it.

**Comment by linonetwo** [comment]
Okay, that is your right, but maybe you can leave some reason so we can improve it.

**Comment by antonmedv** [comment]
I think it will complicate things a lot. 
Also, I’m planning to refactor zx.mjs significantly, so it will break deps on it.
