### ISSUE TITLE
command not found if zx is executed inside an electron app

### ISSUE THREAD

**Issue by linonetwo** [google/zx#230]
```js
await $`cd ~ && ls`;
await $`ls`;
await $`cd ~ && adb install /Users/linonetwo/Downloads/cdda-android-x64-2021-09-06-1709.apk`;
```

output is

```shell
$ cd ~ && ls

Applications Applications (Parallels) Desktop Documents Downloads Dropbox Library Movies Music OneDrive Parallels Pictures Public Sync Zotero go repo

$ ls

Applications Library System Users Volumes bin cores dev etc home opt private sbin tmp usr var

$ cd ~ && adb install /Users/linonetwo/Downloads/cdda-android-x64-2021-09-06-1709.apk

/bin/bash: adb: command not found

Error: /bin/bash: adb: command not found at file:///private/var/folders/qj/7j0zx32d0l75zmnrl1w3m3b80000gn/T/8oDT81/aaa.mjs:3:8 exit code: 127 (Command not found)

child process exited with code 1
```

But if I execute this script in my desktop with zx, it works fine, and adb can be found. And

```js
await $`/usr/local/bin/adb install`
```

works.

## Expected Behavior

1. uses zsh to execute script
2. binarys in PATH can be found by script, even script is inside a tmp folder.

## Actual Behavior

/bin/bash: adb: command not found

## Steps to Reproduce the Problem

1. create a .mjs file with content above
1. mv this file to macos temp folder
1. zx this file

## Specifications

- Version: 4.2.0
- Platform: MacOS

**Comment by antonmedv** [comment]
Echo PATh. Looks like problem with your bashrc files.

**Comment by linonetwo** [comment]
The output is this when the electron is packaged

```
$ > echo $PATH >

/usr/bin:/bin:/usr/sbin:/sbin

$ > pwd >

/

$ > adb install /Users/linonetwo/Downloads/cdda-android-x64-2021-09-06-1709.apk >

/bin/bash: line 1: adb: command not found
```

---

And it works fine when electron is not packaged...

```sh
$ > echo $PATH >

/Users/Desktop/github/TiddlyGit-Desktop/node_modules/.bin:/Users/Desktop/github/node_modules/.bin:/Users/Desktop/node_modules/.bin:.........

$ > pwd >

/Users/Desktop/github/TiddlyGit-Desktop

$ > adb >

Android Debug Bridge version 1.0.41 Version 31.0.2-7242960 Installed as /usr/local/bin/adb

global options: -a listen on all network interfaces,
```

 so the problem might be `child_process.fork` is letting `zx` using wrong pwd after electron is packaged. Do you have any idea to solve this?

**Comment by antonmedv** [comment]
Nope. Not zx related.

**Comment by linonetwo** [comment]
Solution: use https://github.com/sindresorhus/fix-path if you are inside a GUI app.
