### ISSUE TITLE
Error if I call it with directory name instead of file name (Windows)

### ISSUE THREAD

**Issue by frederikhors** [google/zx#235]
## Expected Behavior

I'm on Windows 10, using PowershellCore (latest).

I would like to call my scripts with:

```shell
zx .\scripts\
```

In that dir there is a file `index.mjs` with your example readme code.

## Actual Behavior

It throws with:

```shell
internal/process/esm_loader.js:74
    internalBinding('errors').triggerUncaughtException(
                              ^

[Error: EISDIR: illegal operation on a directory, read] {
  errno: -4068,
  code: 'EISDIR',
  syscall: 'read'
}
```

If I call it with:

```shell
zx .\scripts\index.mjs
```

it works.

## Specifications

- Version: zx@4.2.0
- Platform: Windows 10 21H1

**Comment by antonmedv** [comment]
This is expected nodejs behaviour. Read about ESM.

**Comment by frederikhors** [comment]
So, what I should read? Is there a way to call `zx .\scripts\` and make it work?

**Comment by antonmedv** [comment]
```
zx .\scripts\index.mjs
```

**Comment by frederikhors** [comment]
@antonmedv I don’t want the final index.mjs.

**Comment by antonmedv** [comment]
Try this zx .@scripts

**Comment by frederikhors** [comment]
> Try this zx .@scripts

It doesn't work.

Can you please re-open this?

**Comment by antonmedv** [comment]
Nope.

**Comment by frederikhors** [comment]
I don't understand. If I wanna use it instead of `Make` in a project I should call each time `index.mjs` in each sub-dir? And this is not important for you to address?

**Comment by antonmedv** [comment]
Instead of Make?

**Comment by frederikhors** [comment]
Yep. I'm writing some scripts to do things.

**Comment by antonmedv** [comment]
I don't understand why you need to call zx on a dir instead of file?

**Comment by frederikhors** [comment]
Because I call it many times during a day and I would like to call it immediately from keyboard, I don't want to call useless index.mjs.

**Comment by antonmedv** [comment]
alias run="zx .\scripts\index.mjs" or package.json scripts?
