### ISSUE TITLE
How to execute an .mjs file in Powershell calling it by name like in bash?

### ISSUE THREAD

**Issue by frederikhors** [google/zx#239]
## Expected Behavior

I'm using for the first time https://github.com/google/zx. It's amazing!

If I execute the .mjs files on bash (on linux or mac) it's enough to only call them by name with:

```
./script.mjs
```

after

```
chmod +x ./script.mjs
```

because of the first line (shebang) I suppose: `#!/usr/bin/env zx`.

Now I wanna use it on Windows 10 with PowershellCore.

If I call the file with `./script.mjs` it opens an IDE for editing the file.

Is there a way to let know Powershell to launch the file with `zx` like in bash?

**Comment by antonmedv** [comment]
I think it’s related to powershell. Not zx.
