### ISSUE TITLE
README on npm incorrectly requires Node.js >= 14.13.0

### ISSUE THREAD

**Issue by simonplend** [google/zx#244]
## Expected Behavior

The [README for zx on npm](https://www.npmjs.com/package/zx) should state that the minimum required version is 14.13.1.

This was resolved in this repository in #220 and could probably be pushed out in a patch release.

## Actual Behavior

If you create a script which uses `zx` and try and run it under 14.13.0 you receive the following error:

```
internal/process/esm_loader.js:74
    internalBinding('errors').triggerUncaughtException(
                              ^

Error [ERR_UNSUPPORTED_ESM_URL_SCHEME]: Only file and data URLs are supported by the default ESM loader. Received protocol 'node:'
    at Loader.defaultResolve [as _resolve] (internal/modules/esm/resolve.js:782:11)
    at Loader.resolve (internal/modules/esm/loader.js:85:40)
    at Loader.getModuleJob (internal/modules/esm/loader.js:229:28)
    at ModuleWrap.<anonymous> (internal/modules/esm/module_job.js:51:40)
    at link (internal/modules/esm/module_job.js:50:36) {
  code: 'ERR_UNSUPPORTED_ESM_URL_SCHEME'
}
```

## Steps to Reproduce the Problem

1. Install node@14.13.0
1. `import { $ } from "zx"` in a script
1. Run the script

## Specifications

- Version: 4.2.0
- Platform: Pop_OS! Linux running Node.js v14.13.0

**Comment by hashiqi12138** [comment]
i tried node 14.9.0, there is the same error,

with node 15.0.0, i dont have any errors
