### ISSUE TITLE
shebang scripts work only when called in specific way

### ISSUE THREAD

**Issue by hlolli** [google/zx#248]
I may be missing out on some nuances with shebang scripts using nodejs interpreter, and I hope there's a solution for this.

As I do with nodejs shebangs I use the path to the binary $(which node), and it works wherever and however I call it.

## Expected Behavior

with `hello-world.mjs` (assume +x permissions):

```js
#!/Users/hlolli/.npm-global/bin/zx
console.log("hello world");
```
should

```sh
$ ./hello-world.mjs
=> hello world
```

as should

```js
#!/usr/bin/node /Users/hlolli/.npm-global/lib/node_modules/zx.mjs
console.log("hello world");
```

This here *does* work

```js
#!/usr/bin/env /Users/hlolli/.npm-global/bin/zx
console.log("hello world");
```
(working)

```sh
$ ./hello-world.mjs
=> hello world
```

but not (say hello-world.mjs was on echo $PATH)

```sh
$ which hello-world.mjs | sh
```

## Actual Behavior

```sh
hello-world.mjs: line 2: syntax error near unexpected token `'hello world''
```

## Specifications

- Version: 4.2.0
- Platform: osx/nodejs-16

**Comment by antonmedv** [comment]
This is not zx related issue. Please read: https://tldp.org/LDP/abs/html/sha-bang.html

**Comment by hlolli** [comment]
Thanks, but I solved my particular issue.

```sh
$ sh $(which hello-world.mjs)  | egrep "hello world"
```

fails but

```sh
$ echo $(which hello-world.mjs) | sh | egrep "hello world"
```

works.
