### ISSUE TITLE
Advice: Framework for testing

### ISSUE THREAD

**Issue by malys** [google/zx#250]
Hi,
I have developped different zx scripts. I would create integration tests to detect regression.

have you any advice ( framework, technics, ...) to make easier testing?

@antongolub suggests https://github.com/bats-core/bats-core

I have used testcontainer for this kind of integration tests.

Have you any feedback?

Thanks

**Comment by antonmedv** [comment]
You can swap $.shell with simple echo and test your scripts. Or simply run script to test it)

**Comment by malys** [comment]
"echo" tip  is very interesting but with this strategy,  you will test zx flow implemented in the script but you are not testing shell commands (integration tests). 
I will try "echo" proposal.
Thanks
