### ISSUE TITLE
zx can't be used simultaneously by several asynchronous functions.

### ISSUE THREAD

**Issue by eraviart** [google/zx#252]
## Expected Behavior

zx should allow several asynchronous functions to use it in parallel.

## Actual Behavior

Since $ is global, $.cwd is shared. If several asynchronous functions call `cd()` in parallel they may conflict.

## Steps to Reproduce the Problem

The following code:
```js
import assert from "assert"

async function f(dir) {
  await $`mkdir -p ${dir}`
  cd(dir)
  await sleep(1)
  const currentDir = (await $`pwd`).stdout.trim()
  assert.strictEqual(currentDir, dir)
}

// Call f several times asynchronously:
f("/tmp/dir1")
f("/tmp/dir2")
```
fails with the following output:
```
$ mkdir -p /tmp/dir1
$ mkdir -p /tmp/dir2
$ cd /tmp/dir1
$ cd /tmp/dir2
$ pwd
$ pwd
/tmp/dir2
node:internal/process/promises:246
          triggerUncaughtException(err, true /* fromPromise */);
          ^

AssertionError [ERR_ASSERTION]: Expected values to be strictly equal:
+ actual - expected

+ '/tmp/dir2'
- '/tmp/dir1'
           ^
    at f (file:///tmp/zx-test/index.mjs:10:10) {
  generatedMessage: true,
  code: 'ERR_ASSERTION',
  actual: '/tmp/dir2',
  expected: '/tmp/dir1',
  operator: 'strictEqual'
}
```

## Specifications

- Version: 4.2.0
- Platform: Linux

**Comment by antonmedv** [comment]
This is by design. In JS you can't determine what context current execution is running in. 

How do you check what $.cmd should belong to one or another?

This is possible only from user's land code, ie from function f.

**Comment by eraviart** [comment]
Instead of having a single $ object, zx could be modified to allow multiple instances of $. In the example above, f function would be modified to begin with :
```js
async function f(dir) {
  const $ = make$()
  await $`mkdir -p ${dir}`
  ...
}
...

**Comment by antonmedv** [comment]
This looks odd and not nice api. Better to just manage cwd yourself. No code changes needed.

**Comment by eraviart** [comment]
My need: Im I using zx on an [express](https://expressjs.com/)-based web server => each request is running in its own asynchronous function.
If several users are using my server concurrently, since $ is a single shared object, the sequence of zx commands the server executes may conflict (one user may cd to a directory another user to another one, etc).
For example if a request does :
```js
cd(dir1)
$`command1`
$`command2`
```

and another simulaneous request does:
```js
cd(dir2)
$`command3`
$`command4`
```
sometimes command2 is running in dir2 or command4 in dir 1 => server fails.

So to solve this kind of problem, I believe that ZX needs to be optionally able to have multiple contexts, one per request.

I have started a DRAFT pull request (#253)  that shows a way to do it without changing the current API when this feature is not needed.

**Comment by antonmedv** [comment]
I understand why do you need this. But I don’t what to provide such API in zx. As the maintainer, it’s my responsibility to say no to features. This is the case. From my perspective this will complete things. For example, why fetch also context scoped?  So, at the moment let’s not merge this feature.

**Comment by eraviart** [comment]
So, since I am a big fan of zx, and I want to use its features on my web server project, I made a [fork named yzx](https://github.com/eraviart/yzx) that supports concurrency. Let's hope this fork will be temporary.

**Comment by linonetwo** [comment]
Why  not Promise .all?

**Comment by eraviart** [comment]
Using `Promise.all` and calling `cd()` in some of the promises is a good way to encounter the bug. When one of the promises is changing its current working directory it is also changing the current working directory of all of its siblings.
