### ISSUE TITLE
How to handle Ctrl-C?

### ISSUE THREAD

**Issue by sanfilippopablo** [google/zx#256]
## Expected Behavior
I have this code block:
```js
#!/usr/bin/env zx

process.on("SIGINT", () => {
  console.log("Caught interrupt signal");
});

await $`sleep 1000`;
await $`sleep 2000`;
```

I expected Ctrl-C to either print the message and continue or to stop the first process, show the message and then continue with the second.

## Actual Behavior

No matter what I do, Ctrl-C always stops everything. It shows the message though.

**Comment by antonmedv** [comment]
Node.js is not exactly bash replacement. In zx there is no such expected behaviour. But what about adding it in PR?

**Comment by christian102094** [comment]
Both answers [here](https://stackoverflow.com/questions/44788013/node-child-processes-how-to-intercept-signals-like-sigint) are useful to understand why this happens.

Here is one way (according to the second answer in the Stackoverflow post) to intercept a signal and continue execution of a process.

``` node
#!/usr/bin/env zx

process.on("SIGINT", () => {
  console.log("Caught interrupt signal");
});

await $`trap '' INT; sleep 5`; // Note the trap to intercept SIGINT in the child process
await $`sleep 4`; // If Ctrl+C here, the process is interrupted
```
