### ISSUE TITLE
How to execute mysql command with special character argument without additionall '$'

### ISSUE THREAD

**Issue by ilivss** [google/zx#257]
## Expected Behavior
`sudo mysql -e "CREATE USER 'user'@'%' IDENTIFIED WITH mysql_native_password BY 'ptSPV7b3#PHHg9';"` 

## Actual Behavior
`sudo mysql -e "CREATE USER 'user'@'%' IDENTIFIED WITH mysql_native_password BY $'ptSPV7b3#PHHg9';"` 

## Steps to Reproduce the Problem

1. ``await $`sudo mysql -e "CREATE USER '${database_user}'@'%' IDENTIFIED WITH mysql_native_password BY '${database_password}';"` ``

I've read all the other issues about this 'problem' and tried a few suggestions. Unfortunately I didn't get it to work... How can I get the expected behavior?

## Specifications

- Version: 4.2.0
- Platform: nodejs v16.13.0 LTS

**Comment by antonmedv** [comment]
This is expected. Read https://github.com/google/zx/blob/main/docs/quotes.md
