### ISSUE TITLE
Transforming to bash code

### ISSUE THREAD

**Issue by lprc** [google/zx#264]
Is it possible to generate bash code from zx code? Like transforming a .mjs script into an ordinary .sh script.

I think it would be a nice feature so you can share your scripts with other people who don't use zx or for deploying scripts on remote machines that don't have zx installed. What do you think?

**Comment by antonmedv** [comment]
It will be extremely difficult to do. Two other possibilities:
- bundle nodejs
- use docker

**Comment by VladPetriv** [comment]
I think this is good idea but realization will be hard
