### ISSUE TITLE
Is there any way to write scripts with type suggestions in VsCode or other editors?

### ISSUE THREAD

**Issue by ExcitedSpider** [google/zx#266]
## Expected Behavior

Built-in method can have type suggestions.

## Actual Behavior

![image](https://user-images.githubusercontent.com/35751871/148913734-680bda5b-9d0c-4337-b495-343096a59c09.png)

## Steps to Reproduce the Problem

1.
1.
1.

## Specifications

- Version:
- Platform:

**Comment by antonmedv** [comment]
Add import zx/globals

**Comment by ExcitedSpider** [comment]
> Add import zx/globals

Thanks ! @antonmedv
