### ISSUE TITLE
Split is not a function

### ISSUE THREAD

**Issue by phifa** [google/zx#268]
## Expected Behavior
I expected a string to be split. 

## Actual Behavior
error is thrown 
`TypeError: current.split is not a function`

## Steps to Reproduce the Problem

```
#!/usr/bin/env zx

let current = await $`echo $(gh release list) | cut -d' ' -f1`;
let split = current.split('.');
```

## Specifications

- Version: 4.2.0
- Platform: Mac

**Comment by antonmedv** [comment]
The `await $` returns ProcessOutput, not string.

https://github.com/google/zx/blob/main/index.d.ts#L25-L33

**Comment by phifa** [comment]
ok, @antonmedv  i tried a few things, but how how would you do the above?

**Comment by antonmedv** [comment]
By reading the manual.

**Comment by phifa** [comment]
got it, i was irritated with the top level await. 

```
let current = (await $`echo $(gh release list) | cut -d' ' -f1`).stdout
```

**Comment by antonmedv** [comment]
I got an idea on how to simplify and also allow to call it without brackets. 

Will implement it later today .
