### ISSUE TITLE
Make bash-specifics customizable

### ISSUE THREAD

**Issue by Artoria2e5** [google/zx#27]
## Test script
```js
$.shell = '/usr/local/bin/fish'
let bar = "\\\\a'a"
assert((await $`echo ${bar}`).stdout.trim() === bar)
```

## Expected Behavior
Assert passess

## Actual Behavior
Fails at bash-specific `set` command. Removing that command causes fail due to quoting.

## Steps to Reproduce the Problem

1. Add test script to test.mjs.
1. `yarn test` (get prepend problem)
2. Remove `set` command.
3. Remove the `cat /dev/not_found | sort` test by prepending `if (0)`, as it depends on the `set` thing.
3. `yarn test` (get quote problem)

## Specifications

- Version: current git HEAD (1.1.1)
- Platform: macOS 11

## Suggested fix
* Turn the prepended part into `$.prepend`.
* Turn the quoting function into `$.quote`, as in #10's README change.

Otherwise there really isn't much point in `$.shell`, except for using a newer version of bash. (Is there a point in using another shell? I think so! Just think about why we are using bash instead of splitting the words ourselves and doing a `spawn`. Also consider shells with "special power", such as how `spawn` cannot handle `*.bat` and how powershell commands poke into the system.)

**Comment by antonmedv** [comment]
Done ✅

**Comment by Artoria2e5** [comment]
Now you just bought into my evil plan of
```js
$.shell = '/usr/bin/python'
$.prefix = 'import math\n'
// writing a $.quote is too much effort for this joke
$`math.floor(1.5)`
```
😛
