### ISSUE TITLE
Add a helper for running process and returning their output directly

### ISSUE THREAD

**Issue by henrycunh** [google/zx#281]
## why
most of the time, you have to extract the `stdout` of a process in order to use it, it would be helpful if there was a shortcut for this approach.

## how
I have a couple suggestions:

### using `$$` to deconstruct `stdout` directly
```ts
const message = await $$`
  echo my-message
`

console.log(message) // "my-message"
```
| ✅ pros | 🛑 cons |
|-|-|
| really short! | not intuitive |
|elaborates on the `$` shorthand form for processes | is quite limited to string output |

### using `$.str` to desconstruct encoding with the type specified
```ts
const message = await $.str`
  echo my-message
`
console.log(message) // "my-message"

const myObject = await $.json`
  echo "{ \"my\": \"content\"}"
`
console.log(myObject) // { my: "content" }
```
| ✅ pros | 🛑 cons |
|-|-|
| more intuitive | not that short |
| allows for multiple encodings | string template methods could become visible, creating DX noise |

**Comment by antonmedv** [comment]
So, what is your use case? 
Returned ProcessOutput has `toString()` method. So now you can do:
```js
let branch = await $`git branch --show-current`
let comment = `Deploying ${branch} branch.`
```

Of pass it in another call:
```js
let branch = await $`git branch --show-current`
await $`dep deploy --branch=${branch}`
```

**Comment by henrycunh** [comment]
something like this
```ts
const api = JSON.parse((await $`cat spec.json`).toString())
```
could be more readable like this
```ts
const api = JSON.parse(await $$`cat spec.json`)
```
or even
```ts
const api = await $.json`cat spec.json`
```

**Comment by antonmedv** [comment]
The second example is not really readable. $$ difficult to distinguish from $. Also, it's difficult to guess what it does. Third one is better but adds unnecessary complexity. And the first one can be rewritten to:
```js
const api = JSON.parse(`${await $`cat spec.json`}`)
```

**Comment by henrycunh** [comment]
I think interpolating in template strings just to take advantage is precisely why a shorthand approach for encoding the output is needed!

I agree it adds complexity, but it's **optional**, just a quality of life feature.
I also thought about writing it like this, for improved extensibility, but looks ugly...
```ts
const api = await $('json')`cat spec.json`
```

**Comment by henrycunh** [comment]
My main use case is actually quickly destructuring yaml/json content from files, something like this would make `zx` scripts really sexy
```ts
const { environment } = await $.yaml`cat config.yml`
```
As an alternative to
```ts
const { environment } = YAML.parse(`${await `cat config.yml`}`)
```
But I also appreciate your concern about adding too much arbitrary complexity :]

**Comment by henrycunh** [comment]
just found out @antfu actually did a package to do this
https://github.com/antfu/fsxx
