### ISSUE TITLE
Drop CJS in v5

### ISSUE THREAD

**Issue by antonmedv** [google/zx#282]
I suggest dropping the build step of the CJS version in v5.

Build process is error-prone, fails constantly. 

As well as "native" support of .ts files in zx. (With the suggestion to use `node --loader ts-node/esm` instead).

**Comment by cspotcode** [comment]
If anyone else hits problems with the removal of the CJS build, I published v5 w/CJS support here: https://www.npmjs.com/package/@cspotcode/zx
