### ISSUE TITLE
execute bash form string will fail when the command include space

### ISSUE THREAD

**Issue by tangdingga1** [google/zx#284]
I want to execute command form someone input, like this:
```javascript
const command = await question('waiting for your command:');
await $`${command}`;
```
If the input include space the command will execute fail.
For example, if you input `git`, it will execute ok.But if you input `git status`, it will execute fail.

## Expected Behavior
execute success.

## Actual Behavior
report error:
```bash
$ $'git status'
/bin/bash: git status: command not found
Error: /bin/bash: git status: command not found
    at file:///Users/tang/Desktop/web/code/epeius-zx/zx-ci/index.mjs:6:8
    exit code: 127 (Command not found)
```

## Steps to Reproduce the Problem
try just like this:
```javascript
const demoCommand = 'git status';
await $`${demoCommand}`;
```
## Specifications

- Version:
  - node: v14.15.1
  - zx: 4.3.0
- Platform:MacOS Big Sur 11.6.1

**Comment by antonmedv** [comment]
https://github.com/google/zx/blob/main/docs/quotes.md

**Comment by tangdingga1** [comment]
> 
Thanks a lot.
ok, I see.The doc doesn't point out it directly, so I miss it.
now I use this way to do it.
```javascript
let demo = `git log`;
await $`${demo.split(' ')}`;
```
It's just not very cool, does it?

**Comment by antonmedv** [comment]
Main idea for `$` to be safe. If you what to execute commands directly probably you should use `exec()` directly.
