### ISSUE TITLE
[docs] Testing zx programs with Jasmine

### ISSUE THREAD

**Issue by dotnetCarpenter** [google/zx#291]
## Motivation

I have been thinking about how I can write unit test of zx programs with [Jasmine] 4.0 and today I came up with a solution. I want to post it here to get feedback. Perhaps I missed something obvious to make my solution simpler or perhaps my solution will introduce problems that I am unaware of. If my solution is sound, then perhaps we could add it to the docs as a way to test zx programs with [Jasmine]. In the latter case, these examples should probably be more idiomatic zx code.

## Solution

This code uses [Fluture](https://github.com/fluture-js/Fluture) as `F` and [Sanctuary](https://sanctuary.js.org/) as `S`, but those details are not important. What I want to show is, how to `import` zx global functions to be used both when [Jasmine] is initiating and running the code and when zx is running the code.

`__dirname` is only set on `globalThis`  when `importPath` is used. E.g. When a program is run with either `zx program.mjs` or a SHEBANG is set and the program is run with `./program.mjs`.

_utils.mjs_ is a module that we want to test and use in zx code. _utils.spec.mjs_ is our [Jasmine] unit test and finally _t.mjs_ some zx code that uses _utils.mjs_.

_utils.spec.mjs_ is invoked with `jasmine spec/*.mjs` from npm's _package.json_ and _t.mjs_ is invoked with `./t.mjs` in the terminal.

_utils.mjs_
```js
import sanctuary         from 'sanctuary'
import * as F            from 'fluture'
import { fileURLToPath } from 'url'
import 'zx/globals' // When Jasmine is running this code, we have to assign zx globals to globalThis by importing.

//  __dirname is not defined when Jasmine runs this code.
// Since __dirname is defined on the globalThis object only when zx is running our code,
// we can still use const here to defined it in this scope, even when zx is running our code.
const __dirname = path.dirname( fileURLToPath (import.meta.url))

const S = await createSanctuary (process.env['NODE_ENV'] === 'production')

//    getAllCampaigns :: Future e Json
const getAllCampaigns = (
  F.node (done => fs.readFile (
    path.join (__dirname, 'firefund-production/allCampaigns.json'),
    'utf8',
    done))
  .pipe (S.chain (F.encase (JSON.parse)))
)

export {
  S,
  F,
  getAllCampaigns
}
```

_spec/utils.spec.mjs_
```js
import {
  F,
  S,
  getAllCampaigns,
} from '../utils.mjs'

// describe, it, expect and fail are all Jasmine globals

describe ('getAllCampaigns', () => {
  it ('returns a Future', () => {
    expect (F.isFuture (getAllCampaigns)).toBe (true)
  })

  it ('returns a Future that resolves to an Object of campaigns', () => {
    F.fork (fail)
           (json => {
             const rebuildkobane = json['rebuildkobane']

             expect (rebuildkobane).toEqual ({
               name: 'rebuildkobane',
               title: 'REBUILD KOBANÊ',
               description: 'In 2015, hundreds of people pledged more than 50.000 € in support of the reconstruction of Kobanê. We did not reach the target within the timeframe, and the campaign failed. ',
               currency: 'eur',
               startDate: '2015-07-19',
               endDate: '2015-08-20',
               status: 'failed',
               goal: 130000,
               organization: 'Kobane Reconstruction Board',
               byline: 'Kobane Reconstruction Board',
               acceptCrypto: true,
               bitcoin: '16m6RiKNsBUAMiBn9kejfiu2vGadaBnCiE',
               ether: '',
               type: 'normal'
            })
           })
           (getAllCampaigns)
  })
})
```

_t.mjs_
```js
#!/usr/bin/env zx

import {
  F,
  S,
  getAllCampaigns,
} from './utils.mjs'


getAllCampaigns
.pipe (F.map (S.prop ('rebuildkobane')))
.pipe (F.fork (console.error)
              (console.log))

console.warn (__filename) // /home/dotnet/projects/t.mjs
console.warn (__dirname)  // /home/dotnet/projects/

```

## Specifications

- Version: 5.0.0
- Platform: WSL2 Ubuntu 21.04 hirsute

NOTE: updated after upgrading to zx 5.0.0

[Jasmine]: https://jasmine.github.io/index.html

**Comment by antonmedv** [comment]
Good. But I didn’t get it. What do you trying to test?
