### ISSUE TITLE
How to perform `fs` tasks

### ISSUE THREAD

**Issue by mikeerickson** [google/zx#292]
I am very intrigued by this as I use either shell scripts or standard js scripts

Assuming I want to perform some `fs` related task, must I import the standard `fs` package, or is there another approach?

For example, let's assume I want to get an array of files/folders in the current path?  How would I go about doing this with `zx`?

**Comment by antonmedv** [comment]
There are two options. for example, if we want to create a dir:
```js
await fs.mkdir(...)
```
Or 
```js
await $`mkdir ...`
```

If you're using zx executable - no need to import anything!
