### ISSUE TITLE
use triple slash reference for autocomplete

### ISSUE THREAD

**Issue by HomyeeKing** [google/zx#296]
## Expected Behavior

with  `/// <reference  />`, we can excute remote script directly while `import  'zx/globals'` will cause denpendecy find error

## Steps to Reproduce the Problem

1.
1.
1.

## Specifications

- Version:
- Platform:

**Comment by antonmedv** [comment]
I think better to suggest import. As in this case no func/const will be available if running as node.

**Comment by HomyeeKing** [comment]
so this is an option, not replace the import statement, just as somebody run w/ `node`, others may run w/ `zx`
and with running as node, you need to ensure there's zx node_modules installed in the `CWD`

while you run `zx https://someremote.mjs`, you can get the benifit from `/// <reference>` and  just need the local shell can 
recognize `zx`

**Comment by antonmedv** [comment]
Hmm, not though about this use case. Make sense.

**Comment by HomyeeKing** [comment]
the use case is  excute remote scripts just as https://github.com/google/zx#executing-remote-scripts says

take this repo https://github.com/HomyeeKing/remote-upstream as example,
I want to run `zx https://raw.githubusercontent.com/HomyeeKing/remote-upstream/main/get-upstream.mjs` to excute the script, so in this case `/// <reference />` is a better choice
