### ISSUE TITLE
Question: choices for tab autocompletion, not working

### ISSUE THREAD

**Issue by oliverhr** [google/zx#301]
## Expected Behavior
Display choices array contents for Tab autocompletion

## Actual Behavior
normal question behavior

## Steps to Reproduce the Problem

1. Follow example from https://github.com/google/zx#question
2. execute the script

```
#!/usr/bin/env zx

const selection = await question('Choose: ', {
  choices: Object.keys(process.env)
})
```

## Specifications

- Version: 5.1.0
- Platform: node 16.13.2 / MacOS monterrey

**Comment by antonmedv** [comment]
Press Tab two times.

**Comment by oliverhr** [comment]
thank you @antonmedv, that did the trick
