### ISSUE TITLE
Feature request: Silent command $$

### ISSUE THREAD

**Issue by Whoaa512** [google/zx#312]
Sometimes you want to run a command quietly in the background for a user. Maybe to ls a directory to get a list of options or check the user ID, etc.

I currently have a helper like this, but would be nice if it was included in the default set
```js
export const $$ = async (...args) => {
  $.verbose = false
  const result = await $(...args)
  $.verbose = true
  return result
}

```

**Comment by antonmedv** [comment]
What about this?
```js
await quiet($`cmd`)
```

Same as [`nothrow()`](https://github.com/google/zx#nothrow).
