### ISSUE TITLE
Issue with text substitution

### ISSUE THREAD

**Issue by OlaoluwaM** [google/zx#320]
## Expected Behavior
Command 
```js
  $`rm ${flags} ${path}
```` 
to run successfully as `rm -rf <path>`

## Actual Behavior
![image](https://user-images.githubusercontent.com/37044906/155976089-46a74ce1-2e1f-43ca-b0bd-71f864bc1c54.png)

Even if it is 
```js
  $`rm ${flags} ${[path]}
```` 
## Steps to Reproduce the Problem

1. Create a function that deletes entities at a path with the pass being a template literal variable
1. run the function with a valid path
1. You will notice the screenshot above in the output

## Specifications

- Version: 5.0.0
- Platform: Linux (Fedora 35)

**Comment by antonmedv** [comment]
https://ï.at/zx-quotes

**Comment by xucongli1989** [comment]
I have a similar problem, it's so strange.
