### ISSUE TITLE
The string is wrapped by $'...' when using space (on windows)

### ISSUE THREAD

**Issue by 3201623169** [google/zx#325]
## Expected Behavior

```
// git log output: 
update-zx-config
update zx config
```

## Actual Behavior

```
// git log output:
update-zx-config
$'update zx config'
```

## Steps to Reproduce the Problem

```
const msg = 'update-zx-config'
await $`git commit -m ${msg}`
```

```
const msg = 'update zx config'
await $`git commit -m ${msg}` 
```

## Specifications

- Version:5.2.0
- Platform:Node v17.0.0 on Windows

**Comment by dolphin0618** [comment]
os上同样的问题
```js
const commit = 'feat: xxxx'
await $`git commit -m '{commit}'`
```
![image](https://user-images.githubusercontent.com/8371743/157384613-db214741-84b5-40fd-acf1-a65cb27892f8.png)
 git log output: 
 git commit -m '$'feat: xxxx''

**Comment by antonmedv** [comment]
Use bash.
