### ISSUE TITLE
Add stdout stream

### ISSUE THREAD

**Issue by svennergr** [google/zx#329]
## Description

This is not a bug, but more of a feature request/enhancement. 
I would like to user the stream of the default NodeJS `stdout` channel, returned from `$` calls. 

Is there anything I missed or is this currently not possible with zx?

If it is not possible, I am willing to create a PR for that.

This could either utilize generator functions or observables.

## Example usecase

I would like to monitor a log file with `$"tail -f test.log"`. With that I would like to react on certain log entries beeing added to the file. For example:
```js
(await $"tail -f test.log").stdout.on("data", (logEntry) =>{
  if(logEntry.includes("error")){
    sendMail()
  }
});
```

**Comment by svennergr** [comment]
Just a sidethough: this is basically a question, where "zx"'s features stop and basic Node features kick in. I think it's also fine to have such things developed using the standard `spawn` functionality within Node's `child_process`.

**Comment by antonmedv** [comment]
Zx already supports this. Just drop await keyword.

**Comment by svennergr** [comment]
Awesome, thanks and sorry for not seeing that in the README.

**Comment by antonmedv** [comment]
Also here’s an example of stdout/stdin usage within zx: https://github.com/google/zx/blob/main/examples/interactive.mjs
