### ISSUE TITLE
Support for passing environment variables

### ISSUE THREAD

**Issue by tdeekens** [google/zx#33]
👋🏼 Thanks for the library. Such a job to use!

I was wondering if there is any support to extend or pass environment variable when executing a command. Node.js `spawn` function has support for it as an option. Something which libraries such as `execa` support. I was wondering how this would or is supported by zx. 

🙇🏼 Thanks.

**Comment by antonmedv** [comment]
https://github.com/google/zx#passing-env-variables

```js
process.env.FOO = 'bar'
await $`echo $FOO`
```

**Comment by tdeekens** [comment]
Thanks! Overlooked that.
