### ISSUE TITLE
FormData from node-fetch made available as a global

### ISSUE THREAD

**Issue by javascriptjedi** [google/zx#330]
## Proposal

_zx_ doesn't seem to have a way to use `FormData` with a fetch request. _node-fetch_ provides a polyfill already. Would it be possible to also make `FormData` a global?

## Actual Behavior

Can't use `FormData` easily in _zx_ CI scripts.

**Comment by antonmedv** [comment]
Please, share an example.

**Comment by javascriptjedi** [comment]
I'm working in GitLab and their api supports `multipart/form-data` requests.

Two quick usage examples of this content type in a request from their docs:

https://docs.gitlab.com/ee/development/documentation/restful_api_styleguide.html#post-data-using-form-data
https://docs.gitlab.com/ee/api/wikis.html#upload-an-attachment-to-the-wiki-repository

From _node-fetch_ docs:

>  node-fetch comes with a spec-compliant [FormData](https://developer.mozilla.org/en-US/docs/Web/API/FormData) implementations for posting multipart/form-data payloads

```
import fetch, { FormData, File, fileFrom } from 'node-fetch'

const httpbin = 'https://httpbin.org/post'
const formData = new FormData()
const binary = new Uint8Array([ 97, 98, 99 ])
const abc = new File([binary], 'abc.txt'), { type: 'text/plain' })

formData.set('greeting', 'Hello, world!')
formData.set('file-upload', abc, 'new name.txt')

const response = await fetch(httpbin, { method: 'POST', body: formData })
const data = await response.json()
```

All I was saying is if _zx_ is already using _node-fetch_ under the hood, could _node-fetch_'s `FormData` also be made available for this and other potential use cases of _zx_ in CI/CD environments.

**Comment by antonmedv** [comment]
You can use 

    import { FormData, File, fileFrom } from 'node-fetch'

**Comment by javascriptjedi** [comment]
Sounds good and sounds like it is just a problem with the Docker image configuration we have that brings in _zx_ then. I tried that already and `node-fetch` wasn't available in my script, it couldn't be found. I'll try to fix the pathing/resolution. Thanks for the response.
