### ISSUE TITLE
/bin/bash: nvm: command not found

### ISSUE THREAD

**Issue by Qi728** [google/zx#341]
## Expected Behavior
┌[einson☮Bdian.local]-(/Users)
└> nvm -v
0.38.0
┌[einson☮Bdian.local]-(/Users)
└> 

## Actual Behavior
/bin/bash: nvm: command not found

## Steps to Reproduce the Problem

1.await $` nvm use 10.24.0 `

## Specifications

- Version:4.2.0
- Platform:mac m1

**Comment by Qi728** [comment]
einson@Bdian:~ % cat ~/.bash_profile
export LC_ALL=en_US.UTF-8
export LANG=en_US.UTF-8



export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion

einson@Bdian:~ %

**Comment by Qi728** [comment]
input in terminal it's useful

bug in mjs command not found

**Comment by antongolub** [comment]
https://github.com/nodejs/node/issues/3916

**Comment by Qi728** [comment]
> 

thanks a lot

**Comment by Qi728** [comment]
> nvm.sh
> 
> ```
> # Node Version Manager
> # Implemented as a POSIX-compliant function
> # Should work on sh, dash, bash, ksh, zsh
> # To use source this file from your bash profile
> ```
> 
> [nodejs/node#3916](https://github.com/nodejs/node/issues/3916)

thanks a lot

**Comment by antongolub** [comment]
@Qi728,

But there's a workaround:
```
child_process.execSync('export NVM_DIR=$HOME/.nvm && source $NVM_DIR/nvm.sh && nvm -v').toString()
'0.37.2\n'
```
so you can perform smth like below with `zx` too:
```
{
  $.prefix = 'export NVM_DIR=$HOME/.nvm; source $NVM_DIR/nvm.sh; set -e;'
  await $`nvm -v`
}
```

**Comment by Qi728** [comment]
> 



> @Qi728,
> 
> But there's a workaround:
> 
> ```js
> child_process.execSync('export NVM_DIR=$HOME/.nvm && source $NVM_DIR/nvm.sh && nvm -v').toString()
> // '0.37.2\n'
> ```
> 
> so you can perform smth like this with `zx` too:
> 
> ```js
> {
>   $.prefix = 'export NVM_DIR=$HOME/.nvm; source $NVM_DIR/nvm.sh; set -e;'
>   await $`nvm -v`
> }
> // $ nvm -v
> // 0.37.2
> ```

I love U , bro

**Comment by romanlex** [comment]
@antongolub Sorry but why this not work properly?
```
        $.prefix = 'export NVM_DIR=$HOME/.nvm; source $NVM_DIR/nvm.sh; set -e;'
        await $`nvm -v`
        await $`nvm use`
        await $`node --version`
        await $`npm --version`
 ```
 output
 

> $ nvm -v
0.39.4
$ nvm use
Found '/home/wsl/Development/@foxford/flowtype-migrate/tmp/client/.nvmrc' with version <14.21>
Now using node v14.21.3 (npm v6.14.18)
$ node --version
v18.17.1
$ npm --version
10.1.0

May be you can help me

**Comment by antongolub** [comment]
Each `$` statement spawns its own process, so you need to move node v switch to the prefix.
`export NVM_DIR=$HOME/.nvm; source $NVM_DIR/nvm.sh; nvm use 14; set -e;`

**Comment by romanlex** [comment]
@antongolub thanks for the explanation

**Comment by romanlex** [comment]
hmm, but with `within` it doesn't work(
```
await within(async () => {
            $.prefix +=
                'export NVM_DIR=$HOME/.nvm; source $NVM_DIR/nvm.sh; nvm use; set -e;'

            cd(this.workingDir)

            await $`pwd`

            await $`node --version`
            await $`npm --version`

            await $`npm ci`
        })
        ```
