### ISSUE TITLE
Define `timeout` for spawned processes

### ISSUE THREAD

**Issue by antongolub** [google/zx#349]
The curr impl allows to trigger `p.kill` by hand. Let's introduce a new syntax sugar for this.

1.  
```ts
const timeout = (p, delay) => setTimeot(() => p.pending && p.kill(), delay)
const p = $`cmd args`
timeout(p, 1000)
await p
```
2.
```ts
$.timeout(1000)`cmd arg`
```
3. 
```ts
timeout($, 1000)`cmd arg`
```
4.
```ts
// like $.quiet
$.timeout = 1000
await $`cmd arg`
delete $.timeout
```

**Comment by antonmedv** [comment]
I’m afraid timeout name can be confused with setTimeout.

**Comment by antongolub** [comment]
zx bases on child_process. For me, the context is clear: timeout is related to cmd invokes.

**Comment by antonmedv** [comment]
Agree, but people who use it may think differently, and why will for sure.

**Comment by antongolub** [comment]
`timer` / `timelimit` as alternative?

**Comment by antonmedv** [comment]
```js
let p = $`long-running-operation`
await killAfterTimeout(p, 10e3)
```

**Comment by antonmedv** [comment]
Let's put it under experimental features?

**Comment by antongolub** [comment]
How about?
```ts
withTimeout(1000)`cmd arg`
```

**Comment by antonmedv** [comment]
Yes, this will work.

**Comment by antongolub** [comment]
Deal. I'll push a PR a bit later.
