### ISSUE TITLE
Add prompts npm package for command line prompt

### ISSUE THREAD

**Issue by OptimBro** [google/zx#379]
Hi,

Like we have 

`minimist` as global `argv `for command-line arguments, and other useful packages like `which `and `os`, I think [prompts](https://www.npmjs.com/package/prompts) will be a nice add.

Current question() command is limited, where prompt package has many use cases, and features. And looks very good and interactive in terminal. 

![image](https://github.com/terkelg/prompts/raw/master/media/toggle.gif)

![image](https://user-images.githubusercontent.com/52219366/162574915-7deb6d34-a555-42b0-b2e7-db7100261ff3.png)

Thanks :)

**Comment by antonmedv** [comment]
Let's not add another dep for now.
