### ISSUE TITLE
Proposal: chain api

### ISSUE THREAD

**Issue by antonmedv** [google/zx#385]
Idea: instead of nothrow() and quiet() helpers, add methods to ProcessPromise.

So instead of 
```js
await quiet(nothrow($`cmd`))
```
it will be
```js
await $`cmd`.nothrow().quiet()
```

Also, timeout() can be added to ProcessPromise as well (but not retry() which actually should just be a general retry of any promise).

**Comment by antongolub** [comment]
We can support both.

**Comment by antonmedv** [comment]
Yes, but hide old from documentation and only promote chain api.
