### ISSUE TITLE
Move globals to root dir

### ISSUE THREAD

**Issue by antonmedv** [google/zx#386]
Looks like VS Code does not work great with package.json "exports" right now. 

So it will be nice to move globals.* to root dir, so autocomplete in VSCode works.

**Comment by antonmedv** [comment]
@antongolub what do you think?

**Comment by antongolub** [comment]
It's suprising. I'll install VSCode and take a closer look.

**Comment by antongolub** [comment]
Confirmed. Fix proposal: https://github.com/antongolub/zx/commit/f879f3e3a2fbf100323f67b97dc5871ed596be27
