### ISSUE TITLE
Auto await?

### ISSUE THREAD

**Issue by midzelis** [google/zx#39]
Adding ‘await’ to everything is what you want most of the time, but is quite tedious to have to write out. 

Have you considered automatically transforming the imported JavaScript to automatically insert await statements? This is quite simple to do with Babel… see https://github.com/ziolko/babel-plugin-auto-await. 

The downside is that sometimes you may actually want async behavior, so maybe it can be combined with some escape hatch (a decorator, or perhaps a special comment like ‘ // @zx:no-auto-await. ‘)

**Comment by antonmedv** [comment]
I’d like zx not depends on babel. Also this is auto await will be really confusing for most of people.  

Why don’t you create another lib like zx-auto-await?

**Comment by SilurianYang** [comment]
> 我希望zx不依赖babel。同样，对于大多数人来说，自动等待确实会让您感到困惑。
> 
> 为什么不创建另一个像zx-auto-await之类的库？

I think so too +1

**Comment by antonmedv** [comment]
I think this is out of the scope of the zx project. Closing.
