### ISSUE TITLE
interpolation example not in docs?

### ISSUE THREAD

**Issue by Morriz** [google/zx#394]
## Expected Behavior
...
  const cmd = 'ls -als /tmp' # predefined in other context
  const res = await $`${cmd}`

## Actual Behavior
```
/usr/bin/bash: ls -als /tmp: command not found
```

I did find that if I split the cmd by space it works:
```
  const res = await $`${cmd.split(' ')}`
```

I lost some time finding this out. I will try to find some time for a doc PR.

**Comment by antonmedv** [comment]
https://github.com/google/zx/blob/main/docs/quotes.md

**Comment by Morriz** [comment]
Can we re-open this? I get errors here:
```ts
const cmd = 'pwd && ls -als .'
```
which gives this error:

```
/usr/local/bin/bash: pwd && ls -als .: command not found
```
because, well, reasons...so we try the next:
```ts
...
const res = await $`${cmd.split(' ')}`
```
which translates to `pwd '&&' ls -als .`, so that is also not possible.

How on earth can we create commands up front so that zx doesn't escape special constructs like `&&` or `||` etc etc etc?

**Comment by antonmedv** [comment]
On earth:
```js
await $`pwd && ls -als .`
```

**Comment by Morriz** [comment]
But you are not paying attention to the fact that the command is created and stored in a variable. You are most of the time too quick to conclude. And rude

**Comment by antonmedv** [comment]
It is not valid. Zx, by design, escapes everything that is passed in ${ }. For security reasons. 

If you need to construct a command entirely you should use child_process directly, as zx does not provide such feature (this is intentional).

Of course, there is plenty of work arounds, if you must use zx for this. Split the cmd string `split(' ')` pass cmd as param to shell ``await $`/bin/sh -c ${cmd}` ``

**Comment by Morriz** [comment]
Intentional? Not configurable because you oppose it. How is this usable when we need to be able to provide commands via config into code? This is becoming more like a joke

**Comment by Morriz** [comment]
I am sorry for not rooting deep enough, but I found out later that we can just remove the quoting functionality altogether, which works wonders! Why did you not mention it once?

```ts
    const q = $.quote
    $.quote = (v) => v
```

**Comment by Morriz** [comment]
All our problems are solved. If people ask for it I recommend you give them what they need. Maybe I did not search for it hard enough in the docs, so I will check once again.

**Comment by antonmedv** [comment]
¯\\\_(ツ)_/¯ 

https://github.com/antonmedv/tinysh
