### ISSUE TITLE
Subcommand Prompts are Invisible

### ISSUE THREAD

**Issue by wrynegade** [google/zx#395]
## Expected Behavior
Be able to see when a sub-command prompts for user input.

## Actual Behavior
If a line-end character is not hit, the output is never flushed. Typical prompts for user input in sub-commands will not show up.

## Steps to Reproduce the Problem
```javascript
#!/usr/bin/env zx
await $`printf 'input your name: '; read`
```

## Specifications

- Version: 6.0.3
- Platform: Linux w/node 17.9.0

**Comment by antonmedv** [comment]
```
let p = await $`printf "name:"; read line; echo $line`
console.log(p)
```

```
$ printf "name:"; read line; echo $line
name:anton
anton
ProcessOutput {
  stdout: 'name:anton\n',
  stderr: '',
  signal: null,
  exitCode: 0
}
```
