### ISSUE TITLE
Error in markdown script on first run.

### ISSUE THREAD

**Issue by jp-96** [google/zx#406]
If I run a script written in markdown after zx installation or after saving the md file, it fails only the first time.

## Expected Behavior

The zx can execute scripts written in markdown.

> ```
> $ npx zx markdown.md
> (no errors)
> ```

## Actual Behavior

The first time:

> ```
> $ npx zx markdown.md
> node:internal/process/esm_loader:94
>     internalBinding('errors').triggerUncaughtException(
>                               ^
> 
> [Error: ENOENT: no such file or directory, fstat] {
>   errno: -2,
>   code: 'ENOENT',
>   syscall: 'fstat'
> }
> $ 
> ```

Nonetheless, it succeeds the second time around:

> ```
> $ npx zx markdown.md
> $ whoami
> node
> $ echo /workspaces/vscode-remote-try-node
> /workspaces/vscode-remote-try-node
> /workspaces/vscode-remote-try-node/markdown.md
> $ 
> > VAR=$(date)
> > echo "$VAR" | wc -c
> > 
> 32
> $ 
> ```

## Steps to Reproduce the Problem

1. Start [vscode-remote-try-node](https://github.com/microsoft/vscode-remote-try-node).
1. Create `markdown.md` file.
1. Install zx, `npm install --save-dev zx`.
1. Run, `npx zx markdown.md`

## Specifications

- Version: 6.1.0
- Platform: [vscode-remote-try-node](https://github.com/microsoft/vscode-remote-try-node)

## Memo

Why is `importPath()` not called immediately but after `fs.rm()`  at `writeAndImport()` in the `zx.mjs` file?

```
// zx.mjs
async function writeAndImport(script, filepath, origin = filepath) {
  await fs.writeFile(filepath, script)
  let wait = importPath(filepath, origin)
  await fs.rm(filepath)
  await wait
}
```

**Comment by antonmedv** [comment]
Can't reporduce. ¯\\\_(ツ)_/¯
