### ISSUE TITLE
cmd.exe support

### ISSUE THREAD

**Issue by xmclark** [google/zx#42]
## Expected Behavior

`zx` works with any common shell on windows OS.

## Actual Behavior

In cmd, powershell, and git bash, a typical usage of `zx` fails.

<details>
  <summary>Output from running test in <code>cmd.exe</code></summary>
  <pre>
    <code>
C:\Users\macke>npm i -g -f zx
npm WARN using --force I sure hope you know what you are doing.
C:\Users\macke\AppData\Roaming\npm\zx -> C:\Users\macke\AppData\Roaming\npm\node_modules\zx\zx.mjs
+ zx@1.2.2
updated 1 package in 0.63s
C:\Users\macke>zx -h
'command' is not recognized as an internal or external command,
operable program or batch file.
'which' is not recognized as an internal or external command,
operable program or batch file.
The system cannot find the file specified.
Error occurred while processing: -p.
The system cannot find the file specified.
Error occurred while processing: bash.
child_process.js:616
    err = new Error(msg);
          ^
Error: Command failed: command -v bash || which bash || type -p bash
'command' is not recognized as an internal or external command,
operable program or batch file.
'which' is not recognized as an internal or external command,
operable program or batch file.
The system cannot find the file specified.
Error occurred while processing: -p.
The system cannot find the file specified.
Error occurred while processing: bash.
    at checkExecSyncError (child_process.js:616:11)
    at execSync (child_process.js:652:15)
    at file:///C:/Users/macke/AppData/Roaming/npm/node_modules/zx/index.mjs:75:14
    at ModuleJob.run (internal/modules/esm/module_job.js:152:23)
    at async Loader.import (internal/modules/esm/loader.js:166:24)
    at async Object.loadESM (internal/process/esm_loader.js:68:5) {
  status: 1,
  signal: null,
  output: [
    null,
    Buffer(0) [Uint8Array] [],
    Buffer(360) [Uint8Array] [
       39,  99, 111, 109, 109,  97, 110, 100,  39,  32, 105, 115,
       32, 110, 111, 116,  32, 114, 101,  99, 111, 103, 110, 105,
      122, 101, 100,  32,  97, 115,  32,  97, 110,  32, 105, 110,
      116, 101, 114, 110,  97, 108,  32, 111, 114,  32, 101, 120,
      116, 101, 114, 110,  97, 108,  32,  99, 111, 109, 109,  97,
      110, 100,  44,  13,  10, 111, 112, 101, 114,  97,  98, 108,
      101,  32, 112, 114, 111, 103, 114,  97, 109,  32, 111, 114,
       32,  98,  97, 116,  99, 104,  32, 102, 105, 108, 101,  46,
       13,  10,  39, 119,
      ... 260 more items
    ]
  ],
  pid: 2628,
  stdout: Buffer(0) [Uint8Array] [],
  stderr: Buffer(360) [Uint8Array] [
     39,  99, 111, 109, 109,  97, 110, 100,  39,  32, 105, 115,
     32, 110, 111, 116,  32, 114, 101,  99, 111, 103, 110, 105,
    122, 101, 100,  32,  97, 115,  32,  97, 110,  32, 105, 110,
    116, 101, 114, 110,  97, 108,  32, 111, 114,  32, 101, 120,
    116, 101, 114, 110,  97, 108,  32,  99, 111, 109, 109,  97,
    110, 100,  44,  13,  10, 111, 112, 101, 114,  97,  98, 108,
    101,  32, 112, 114, 111, 103, 114,  97, 109,  32, 111, 114,
     32,  98,  97, 116,  99, 104,  32, 102, 105, 108, 101,  46,
     13,  10,  39, 119,
    ... 260 more items
  ]
}
    </code>
  </pre>
</details>

<details>
  <summary>Output from running test in <code>pwsh.exe</code> (powershell core 7) </summary>
  <pre>
    <code>
PS C:\Users\macke> npm i -g -f zx
npm WARN using --force I sure hope you know what you are doing.
C:\Users\macke\AppData\Roaming\npm\zx -> C:\Users\macke\AppData\Roaming\npm\node_modules\zx\zx.mjs
+ zx@1.2.2
updated 1 package in 0.594s
PS C:\Users\macke> zx -h
'command' is not recognized as an internal or external command,
operable program or batch file.
'which' is not recognized as an internal or external command,
operable program or batch file.
The system cannot find the file specified.
Error occurred while processing: -p.
The system cannot find the file specified.
Error occurred while processing: bash.
child_process.js:616
    err = new Error(msg);
          ^
Error: Command failed: command -v bash || which bash || type -p bash
'command' is not recognized as an internal or external command,
operable program or batch file.
'which' is not recognized as an internal or external command,
operable program or batch file.
The system cannot find the file specified.
Error occurred while processing: -p.
The system cannot find the file specified.
Error occurred while processing: bash.
    at checkExecSyncError (child_process.js:616:11)
    at execSync (child_process.js:652:15)
    at file:///C:/Users/macke/AppData/Roaming/npm/node_modules/zx/index.mjs:75:14
    at ModuleJob.run (internal/modules/esm/module_job.js:152:23)
    at async Loader.import (internal/modules/esm/loader.js:166:24)
    at async Object.loadESM (internal/process/esm_loader.js:68:5) {
  status: 1,
  signal: null,
  output: [
    null,
    Buffer(0) [Uint8Array] [],
    Buffer(360) [Uint8Array] [
       39,  99, 111, 109, 109,  97, 110, 100,  39,  32, 105, 115,
       32, 110, 111, 116,  32, 114, 101,  99, 111, 103, 110, 105,
      122, 101, 100,  32,  97, 115,  32,  97, 110,  32, 105, 110,
      116, 101, 114, 110,  97, 108,  32, 111, 114,  32, 101, 120,
      116, 101, 114, 110,  97, 108,  32,  99, 111, 109, 109,  97,
      110, 100,  44,  13,  10, 111, 112, 101, 114,  97,  98, 108,
      101,  32, 112, 114, 111, 103, 114,  97, 109,  32, 111, 114,
       32,  98,  97, 116,  99, 104,  32, 102, 105, 108, 101,  46,
       13,  10,  39, 119,
      ... 260 more items
    ]
  ],
  pid: 21584,
  stdout: Buffer(0) [Uint8Array] [],
  stderr: Buffer(360) [Uint8Array] [
     39,  99, 111, 109, 109,  97, 110, 100,  39,  32, 105, 115,
     32, 110, 111, 116,  32, 114, 101,  99, 111, 103, 110, 105,
    122, 101, 100,  32,  97, 115,  32,  97, 110,  32, 105, 110,
    116, 101, 114, 110,  97, 108,  32, 111, 114,  32, 101, 120,
    116, 101, 114, 110,  97, 108,  32,  99, 111, 109, 109,  97,
    110, 100,  44,  13,  10, 111, 112, 101, 114,  97,  98, 108,
    101,  32, 112, 114, 111, 103, 114,  97, 109,  32, 111, 114,
     32,  98,  97, 116,  99, 104,  32, 102, 105, 108, 101,  46,
     13,  10,  39, 119,
    ... 260 more items
  ]
}
    </code>
  </pre>
</details>

<details>
  <summary>Output from running test in <code>bash.exe</code> (git bash) </summary>
  <pre>
    <code>
macke@DESKTOP-B1AO5HR MINGW64 ~
$ npm i -g -f zx
npm WARN using --force I sure hope you know what you are doing.
C:\Users\macke\AppData\Roaming\npm\zx -> C:\Users\macke\AppData\Roaming\npm\node_modules\zx\zx.mjs
+ zx@1.2.2
updated 1 package in 0.726s
macke@DESKTOP-B1AO5HR MINGW64 ~
$ zx -h
'command' is not recognized as an internal or external command,
operable program or batch file.
internal/process/esm_loader.js:74
    internalBinding('errors').triggerUncaughtException(
                              ^
Error [ERR_UNSUPPORTED_ESM_URL_SCHEME]: Only file and data URLs are supported by the default ESM loader. On Windows, absolute paths must be valid file:// URLs. Received protocol 'c:'
    at Loader.defaultResolve [as _resolve] (internal/modules/esm/resolve.js:782:11)
    at Loader.resolve (internal/modules/esm/loader.js:86:40)
    at Loader.getModuleJob (internal/modules/esm/loader.js:230:28)
    at Loader.import (internal/modules/esm/loader.js:165:28)
    at importModuleDynamically (internal/modules/esm/translators.js:114:35)
    at exports.importModuleDynamicallyCallback (internal/process/esm_loader.js:30:14)
    at file:///C:/Users/macke/AppData/Roaming/npm/node_modules/zx/zx.mjs:57:5
    at ModuleJob.run (internal/modules/esm/module_job.js:152:23)
    at async Loader.import (internal/modules/esm/loader.js:166:24)
    at async Object.loadESM (internal/process/esm_loader.js:68:5) {
  code: 'ERR_UNSUPPORTED_ESM_URL_SCHEME'
}
    </code>
  </pre>
</details>

## Steps to Reproduce the Problem

Into any common windows shell:

1. type `npm i -g -f zx` 
1. type `xz -h`

## Specifications

- Version: 1.2.2
- Platform: Windows 10 OS

**Comment by antonmedv** [comment]
For now use WSL.

**Comment by xmclark** [comment]
> 
> 
> For now use WSL.

OK. Is actual windows host support a goal for this project?

**Comment by antonmedv** [comment]
Yes

**Comment by antonmedv** [comment]
But I don’t have enough windows experience to figure out best solution.

**Comment by gugadev** [comment]
Maybe you can add a "Need help" label to this issue or add it to the README.

**Comment by pi0** [comment]
Two options for cross-os shell support worth trying:

- https://github.com/shelljs/shelljs (/cc @nfischer @arturadib)
- https://github.com/yarnpkg/berry/tree/master/packages/yarnpkg-shell (/cc @arcanis @merceyz @paul-soporan)

Related RFC with bare win support: #45
