### ISSUE TITLE
The typing for `$.verbose` has changed in v6.2.0

### ISSUE THREAD

**Issue by somombo** [google/zx#421]
@antongolub @antonmedv as a result of PR https://github.com/google/zx/pull/417 for zx v6.2.0, `$.verbose` now has type number rather than `boolean` as implied Readme.md (so `$.verbose = false` nolonger works unless you hack the typescript).

**Comment by antongolub** [comment]
Hmm...
<img width="281" alt="image" src="https://user-images.githubusercontent.com/5288046/171687242-625aa95b-9754-4971-a633-6e76e7d46949.png">

I'll check this.
