### ISSUE TITLE
Feature suggestion: per command verbosity

### ISSUE THREAD

**Issue by Contextualist** [google/zx#43]
Being able to turn verbosity on/off for individual command.

### Use case

```js
let [_, result2] = await Promise.all([
    $`command-with-progress-bar`,
    $`command-to-be-muted`,
])
// do something else with `result2`
```

I want to monitor some commands' output (e.g. it has a progress bar) and not display the others' (while still keep them for further calculation).  If the commands are executed synchronously, I can change the global `$.verbose` setting in between. However, for parallel async executions, it is currently impossible to have different setting for each command.

**Comment by quantumsheep** [comment]
We could do something like `` $.silent`command-to-be-muted` ``?

**Comment by Contextualist** [comment]
Adding a new template literal tag `$.silent` could be a solution, but I felt that it complicates the API. Since this is probably not a widely sought feature, it's fine if it does not have a shortcut.

An alternative way without changing the current API is to make the global `$.verbose` setting "scope local". Here's a slightly involved example:

```js

let [_, result2] = await Promise.all([
    $`command-with-progress-bar`,
    (async () => {
        $.verbose = false
        await $`command-to-be-muted`
    })(),
])
await $`another-verbose-command`
```

If the settings (e.g. cd, verbose) are local to the scope (inner scope inherits but not overrides the settings from outer scope), it might be more intuitive. I'm not sure how could this be implemented in js, but a similar thing can be achieved in python with module [`contextvar`](https://docs.python.org/3/library/contextvars.html#asyncio-support).

**Comment by antonmedv** [comment]
As `$` just a wrapper around child_process we can always use exec too.

```js
import {exec} from 'child_process'
import {promisify} from 'util'

await Promise.all([
  $`echo verbose`,
  promisify(exec)(`say "I'm hidden command"`),
])
await $`echo after`
```

**Comment by Nomyfan** [comment]
I like the idea of *scope local*. I think we can capture the global flags as local flags and provide a mechanism to override the captured local flags. Each command should use its local flags instead because **shared** flags aren't safe if commands run "concurrently".

**Comment by antonmedv** [comment]
I decided not to add this functionality.
