### ISSUE TITLE
sleep() test seems to be flaky

### ISSUE THREAD

**Issue by antonmedv** [google/zx#441]
SBF

**Comment by antonmedv** [comment]
Fixed.

**Comment by antonmedv** [comment]
Nope. Not fixed. Any volunteers to fix it?)

**Comment by H4TIEL** [comment]
Here available to provide a fix

**Comment by antonmedv** [comment]
Cool, PR are welcome.

**Comment by YashishDua** [comment]
@H4TIEL Are you working on this?

@antonmedv I am up for working on this, in case @H4TIEL got occupied or need help.

**Comment by antongolub** [comment]
Fix proposal: https://github.com/google/zx/pull/498/commits/3930acf61dd84d1e86d1ba6fe46cf8fd30dff47b

**Comment by antonmedv** [comment]
Cool 😎
