### ISSUE TITLE
Provide asdf recipe

### ISSUE THREAD

**Issue by airtonix** [google/zx#454]
https://asdf-vm.com/plugins/create.html

## Expected Behavior

```
$ cat .tool-versions

nodejs 18.4.0
zx 7.0.2

$ asdf install 

... snip 

$ node -v 
18.4.0

$ zx --version
7.0.2

$ cat Justfile

# JUSTFILE
# https://github.com/casey/just
#
DEFAULT_TARGET := "http://lmf.ao"

default:
    @just --choose

help:
    @just --list

ping:
    #!/usr/bin/env zx
    await fetch({{DEFAULT_TARGET}})
    
```

## Actual Behavior

have to isntall nodejs, yarn/pnpm/npm, make a package.json, or globally install zx :(

**Comment by airtonix** [comment]
So where the zx recipe for ASDF?

**Comment by antonmedv** [comment]
There is no such recipe.

**Comment by airtonix** [comment]
Then why close the ticket?

**Comment by antonmedv** [comment]
Not an issue.

**Comment by airtonix** [comment]
of course it is!

I gotta say you response to this whole request has been pretty rude and dismissive.
