### ISSUE TITLE
Suggestion to use chalk colors directly with echo

### ISSUE THREAD

**Issue by jeremyben** [google/zx#455]
## Expected Behavior

It would be nice to have a terse way of colorizing `echo` output:

```ts
echo.blue`hello ${processOutput}`
```

As `echo` is already a convenient wrapper of `console.log` for ProcessOutput, it could be even more convenient.

## Actual Behavior

Right now, this is how you have to do:

```ts
echo`${chalk.blue(`hello ${processOutput}`)}`
// or
echo(chalk.blue(`hello ${processOutput}`))
```

TypeScript compiler is not even ok with the second way, as the `echo` signature is missing an overload for regular invokation (which is another issue).

**Comment by antonmedv** [comment]
I’m not sure if we can to extend exho to do this kind of things. Let’s keep echo simple.

**Comment by antonmedv** [comment]
I suggest to use if needed this approach:

```js
import color from 'chalk-template'

echo(color`
CPU: {red ${cpu.totalPercent}%}
RAM: {green ${ram.used / ram.total * 100}%}
DISK: {rgb(255,131,0) ${disk.used / disk.total * 100}%}
`);

**Comment by jeremyben** [comment]
Interesting use of the templating feature.

We can overload echo as a namespace, but I get that this would "pollute" and complicate things by having all the colors as sub functions.

Nevermind, thank you for your consideration.
