### ISSUE TITLE
Test failures trying to access example.com

### ISSUE THREAD

**Issue by bryceharrington** [google/zx#462]
We're seeing test failures building in Ubuntu's build environment.  The package builds and tests fine locally for me.  I suspect the issue is a test case that attempts to fetch from example.com.  In the build environment, network access is denied to the package's build system, so these kinds of tests commonly fail.

    https://launchpadlibrarian.net/609417606/buildlog_ubuntu-kinetic-amd64.node-zx_6.1.0+~cs5.6.21-1_BUILDING.txt.gz

Debian also sees a build failure, guessing it's the same problem?

    https://salsa.debian.org/js-team/node-zx/-/jobs/2694437

(Btw, it would be helpful if the testsuite was configured to print a clear 'FAIL' or 'nak' next to test failures, or a summary with list of the failed test cases.  It wasn't clear to me at first that it was the FetchError.)

## Specifications

- Version: 6.1.0+~cs5.6.21
- Platform: Ubuntu 22.04

**Comment by antonmedv** [comment]
I didn’t get it. What build?

**Comment by antonmedv** [comment]
I'm still not getting it) what build. In which project?
