### ISSUE TITLE
Adds $ sign

### ISSUE THREAD

**Issue by geoffreysamper** [google/zx#471]
In the version 7.0.5 of zx there is an issue with escaping bash variables when there is a js var with a : character in it. This bug introduced in zx 7.0.4. when running version 7.0.3 there is no issue when going to 7.0.4 there is an issue

## Expected Behavior
expected output: special/var:iable
actual output: special/var:iable

## Actual Behavior
expected output: special/var:iable
actual ouput: $special/var:iable

__whats wrong: the $ sign should not be there__

## Steps to Reproduce the Problem
- create a file test.mjs
-  add follow script 
```
const variable  ="special/var:iable"
await $`echo ${variable}`;
```
- run npx zx@7.0.5 test.mjs

see repo  https://github.com/geoffreysamper/zx-issue-7.05-escaping-vars

## Specifications

- Version: 7.0.5
- Platform: ubuntu 22.04

**Comment by antonmedv** [comment]
Please read https://ï.at/zx-quotes

**Comment by antonmedv** [comment]
I tested both versions - results the same.

**Comment by geoffreysamper** [comment]
Sorry to bother you again there is a difference. I don't understand why on the for the white text there is for 7.0.3 `special/var:iable` and for the 7.0.4 there is `$special/var:iable` . Will the quote help to remove the $ from the 7.0.4


 when I run it  on 7.0.4 

![image](https://user-images.githubusercontent.com/232120/176868701-cb8a561e-1b5d-445a-9f7f-821be5ae46c5.png)


Here when I run it on 7.0.3

![image](https://user-images.githubusercontent.com/232120/176869252-631a3671-3e53-4fd6-9922-e58a830a465b.png)

**Comment by antonmedv** [comment]
This is really strange. Try to use different computer or clean vm.

**Comment by nickrabaey** [comment]
@antonmedv can you share the same screenshots of your tests?  (zx -v + zx test.mjs)  
I have the same problem, v7.0.3 OK, v7.0.4/5 adds an extra $ in the output

<img width="443" alt="zx" src="https://user-images.githubusercontent.com/108523345/176884334-d6c09c52-5440-44dd-bb87-38766a4514ed.png">

**Comment by antonmedv** [comment]
I think I figured it out. 

You use it with some bash (git-bash, cgwyn, etc) on Windows OS? 

What changed: now on windows default shell is cmd.exe/pwsh.exe (as nodejs does). So you need to specify $.shell.

**Comment by nickrabaey** [comment]
Hi Anton, I think you are on to something.  However running Ubuntu (not cygwin/git-bash) in WSLv2.
See screenshot with now added $SHELL and uname outpu
<img width="1494" alt="unames" src="https://user-images.githubusercontent.com/108523345/176887638-5be4d8fa-431f-4150-9869-c7f3906b73cc.png">
t

**Comment by antonmedv** [comment]
What is in `$.shell`?

**Comment by geoffreysamper** [comment]
@antonmedv I try to run it on fedora 36 then  the 7.0.5. So test on some other distro. 
Ubuntu 22 & zx 7.0.5: __has the issue__
Fedora 36 & ZX 7.0.5: no issue
Ubuntu 22 & zx 7.0.3:  no issue

### Fedora
![image](https://user-images.githubusercontent.com/232120/176887110-6ab15238-1ce1-4662-9cc9-aa42dc15aacf.png)

### Ubuntu 22
![image](https://user-images.githubusercontent.com/232120/176887523-7d5f8521-c8dc-452c-b7f0-d35178f90628.png)

### Ubuntu 20

![image](https://user-images.githubusercontent.com/232120/176889570-f923d46f-a52c-4835-b5ce-78482f2942b4.png)

**Comment by geoffreysamper** [comment]
@antonmedv for both fedora and ubuntu the `$.shell` contains the value __true__

**Comment by nickrabaey** [comment]
@antonmedv $.shell returns true
<img width="896" alt="shell" src="https://user-images.githubusercontent.com/108523345/176890735-78520e53-2400-4c34-9759-1ac88ecebaa4.png">

**Comment by antonmedv** [comment]
I see, so please print which shell is used by zx?

**Comment by antonmedv** [comment]
It also looks like no bash on those systems was installed. The `$'..'` is only bash-related.

**Comment by geoffreysamper** [comment]
@antonmedv you can I know this because when i do $.shell i got true

**Comment by nickrabaey** [comment]
/bin/bash is used:

![test_bash](https://user-images.githubusercontent.com/108523345/176892540-0d4334f3-d7fe-4568-8994-1eab748911d7.jpg)

**Comment by nickrabaey** [comment]
When we add $.shell ="/bin/bash" on top in our mjs script, the behaviour of ZX 7.04/5 is back to normal.

**Comment by antonmedv** [comment]
What's in `process.platform`?

**Comment by geoffreysamper** [comment]
value is linux
![image](https://user-images.githubusercontent.com/232120/176898561-23096757-71d7-4d15-bf41-ed1dd2f354e5.png)

**Comment by nickrabaey** [comment]
Yep, here too: 
Process.platform: linux

**Comment by antonmedv** [comment]
Can you debug this part of code: https://github.com/google/zx/blob/main/src/core.ts#L73-L80

This is what changed and probably causing issues.

**Comment by nickrabaey** [comment]
Don't know how to debug this from source code.  Looks indeed like the commit that broke it for us.

**Comment by antonmedv** [comment]
Awesome 👍 thanks

I wonder if it is possible to add a test to catch this kind of issue?

**Comment by geoffreysamper** [comment]
The issue with this bug is that it will be very difficult to detect. The  code worked except when the __variable__ contains a special character and in a specific distro in my case Ubuntu or Debian (did a test). Due the fact that it contained a try-catch the error is suppressed. Personally, I try to avoid using a try catch to hide the error. Sometimes you don't have any other choice, if this is the case I use something like [node DEBUG package](https://github.com/debug-js). The advantage is, I can enable env. Variable and it could help you for knowing what goes wrong and give some clues.

In any case, thank you for this awesome package because it made my dev life a lot easier and certainly when I can avoid using bash.  I always need to look up how to write an _if statement_.

**Comment by antonmedv** [comment]
> This is my last day before my 3-week holiday.

Have a nice holiday) Going on 1 week holiday myself next week)

The problem is cycle dependency. Gonna add eslint to catch it.

**Comment by antonmedv** [comment]
Added madge to check for circular deps. And fixed the issue will publish the fix.
