### ISSUE TITLE
Request: Add tree-slash type references into `index.mjs` and `mod.mjs` that points to `index.d.ts`

### ISSUE THREAD

**Issue by KSXGitHub** [google/zx#480]
Add the line below to the top of `index.mjs` and `mod.mjs` please:

```javascript
/// <reference types="./index.d.ts" />
```

Doing so to make Deno recognizes TypeScript signatures.

**Comment by antonmedv** [comment]
I doubt that deno supports all features from nodejs zx uses.

**Comment by KSXGitHub** [comment]
Wait a minute, I just noticed that [this](https://github.com/Minigugus/zx-deno) should have been the repo to open this issue. But it lacks an issue tag, and I somehow found myself here unknowingly.
