### ISSUE TITLE
Include the websocket library

### ISSUE THREAD

**Issue by onedr0p** [google/zx#485]
## Expected Behavior

Hi 👋🏼 

I am writing a script that requires connection to a websocket server to execute commands. It would be nice to include the [ws](https://github.com/websockets/ws) or a related package to connect to a websocket server.

Thanks!

**Comment by onedr0p** [comment]
IMO I find the appeal of xz is not having to manage deps in a package.json but I guess it's inevitable if you want to to keep it lightweight. `ws` is just like `fetch` in that you are interacting with external APIs over the web, it would be nice :/

**Comment by antonmedv** [comment]
I'm thinknig of adding npm() func for zx:
```js
const WebSocket = await npm('ws')
```

**Comment by antonmedv** [comment]
Don’t know. Probably install it every time. Npm has cache on its own.
