### ISSUE TITLE
cd still not work(with "import "zx/globals") 

### ISSUE THREAD

**Issue by xtutu** [google/zx#488]
#444 

@antonmedv still not work on mac
```mjs
import "zx/globals"
await $`mkdir -p temp/a`
cd(`temp`)
await $`mv ./a ./b`

```

output
```bash
mv: rename ./a to ./b: No such file or directory
ProcessOutput {
  stdout: '',
  stderr: 'mv: rename ./a to ./b: No such file or directory\n',
  exitCode: 1
}
```

## Specifications
- nodejs 16.15.1
- Version: 7.0.7
- Platform: mac

**Comment by antonmedv** [comment]
Strange. Works for me. 

But I'm trying on node18.7. Please, verify what this is not node issue ))

**Comment by xtutu** [comment]
I know...
I have a global zx(the lastest version) , and a local zx in package.json(which is not the lastest version).
when i use
```bash
zx xxxx.mjs
``` 
it import the  local zx file
