### ISSUE TITLE
makefile like

### ISSUE THREAD

**Issue by mh-cbon** [google/zx#49]
is there good way to work with this like a makefile ?

something that would let me define a file like

```js
test:
   let x = $.args.whatever
   await $`do some ${x}`
build:
  await $`some else`
```

The cli arguments would be parsed automatically, so if i call `zx test --whatever` I can access this value in `$.args.whatever`.

**Comment by antonmedv** [comment]
I think a task runner/build system is out of scope of zx package. But somebody definitely can derive from zx and built it on top of it. 

Arguments parsing will come for sure.

**Comment by dusansimic** [comment]
You can do this using [Just](https://github.com/casey/just#prerequisites). You can specify the shell that will be used to run the script. It's missing argument parsing for now since zx doesn't support it but it's possible to run simple scripts.

**Comment by mh-cbon** [comment]
it is perfect, thank you for that.
