### ISSUE TITLE
No formatting in vscode

### ISSUE THREAD

**Issue by kaihendry** [google/zx#499]
## Expected Behavior

Formatting whilst editing a script

## Actual Behavior

    ["INFO" - 4:22:44 PM] Require config set to true and no config present. Skipping file.

## Steps to Reproduce the Problem

1. Save the initial README's example to foo.mjs
1. Open in VS code
2. Change a line, and notice no auto-formatting

**Comment by antonmedv** [comment]
I think it’s vscode issue. Not zx.

**Comment by antongolub** [comment]
`opt + cmd + L` in IntellyJ works fine. The point goes to JetBrains.

**Comment by kaihendry** [comment]
Assumed you'd be keen on VS code, but tbh after again fllowing the README's

> Or import globals explicitly (for better autocomplete in VS Code).
> import 'zx/globals'

This also fails on my system with:

    Error [ERR_MODULE_NOT_FOUND]: Cannot find package 'zx' imported from /Users/hendry/zx-test/foo.mjs

I installed zx via `npm i -g zx` btw

**Comment by antongolub** [comment]
* https://nodejs.org/api/modules.html#modules_loading_from_the_global_folders
* https://stackoverflow.com/questions/29971572/how-do-i-add-environment-variables-to-launch-json-in-vscode
* https://stackoverflow.com/questions/7970793/how-do-i-import-global-modules-in-node-i-get-error-cannot-find-module-module

One possible workaround:
```js
import {createRequire} from 'module'
import path from 'path'
await import(path.resolve(createRequire(import.meta.url).resolve('zx'), '../globals.js'))

await $`echo test`
```

```shell
NODE_PATH="$(npm root -g)" node test-zx.mjs
```

**Comment by kaihendry** [comment]
This seems like a terrible workaround. And then I need to remember to take out that code when I ship the code? Urgh.

**Comment by antongolub** [comment]
https://docs.npmjs.com/cli/v8/commands/npm-link

**Comment by antonmedv** [comment]
I’m not getting, what is the problem?

**Comment by antonmedv** [comment]
Just use zx and executable binary.

**Comment by antongolub** [comment]
vscode does not provide autocompletions for global packages. Therefore, some actions are required on the user's side. Anyway it does not look like zx impl or docs issue.

<img width="958" alt="image" src="https://user-images.githubusercontent.com/5288046/186938603-414336eb-24c7-4889-b730-ae7874dad225.png">
