### ISSUE TITLE
Escape args in command?

### ISSUE THREAD

**Issue by progfay** [google/zx#5]
## Expected Behavior

In shell:

```sh
#!/bin/bash

message='; ls'
echo ${message}
# Output: '; ls'
```

So I think:
```js
#!/usr/bin/env zx

const message = '; ls'
await $`echo ${message}`
// Expect Output: '; ls'
```

## Actual Behavior

- Actual Output: result of `ls`

## Steps to Reproduce the Problem

1. Execute above commands

## Consideration

- On migrate from ShellScript to `zx`, The above case are likely to occur.
- And scripts has potential of Arbitrary Command Execution.
- To prevent, escape args or provide methods for escape variables.

## Specifications

- Version: 1.0.2
- Platform: macOS

**Comment by antonmedv** [comment]
Yes, thanks for your submission. This issue was raised a few times already and I’m going to add proper escaping to it.

**Comment by progfay** [comment]
OK, I'm looking forward to update!

**Comment by antonmedv** [comment]
Done in 1.1.0
```js
let name = 'foo bar'
await $`mkdir /tmp/${name}`
```
