### ISSUE TITLE
Bundle zx package

### ISSUE THREAD

**Issue by pi0** [google/zx#50]
Currently installing `zx` package, costs `~125 files` and `832K` of disk space (401K reported by [packagephobia](https://packagephobia.com/result?p=zx)). Also, it is making zx dependant on `node_modules`. 

By bundling zx package:

- Install cost will be reduced to few files (basically one `zx.mjs`) and `~92KB` as of `v1.2.2`
- `zx` script will be standalone. Can possibly help #25 for embedded solutions or selfupdate
- Using rollup plugins, we can have a chance for deno build from same source (#24)
- Memory footprint will be reduced as a benefit from tree-shaking unused imports (quick test max RSS from `44580kb` to `37628kb` for `test.mjs`
- Easier dist analyzes 
- Possibility to use typescript
- Removing need of cjs hack for importing `version` from `package.json`

PR: #51

**Comment by antonmedv** [comment]
But on other hands it adds completely. Now we need build process, errors will originate from a different source. 

I’m not sure what benefits you described is really worth the hassle.

Install cost? How much it is?
Standalone zx script? What benefits? 
Memory footprint seems small. 
What a dist analysis? It’s easier to no on source without any transformation. 
ts is great, but project really simple. 
hack with cjs is ugly, but will go away with json modules in future.

**Comment by pi0** [comment]
The main reason I thought to bundle was to distribute zx as a standalone js shell that can be embedded or distributed easily for pipelines. (like into a docker image or a `curl` script for automation). While is possible to depend on `npm/npx`, this would increase complexities, edge-cases (dep regressions, npm failure), and considerations for usage environment (npm needs to be installed and non-node runtimes cannot be supported since depending on `node_modules` resolution).

By #51 build happens automatically during `npm publish` and only affects stack-trace of zx internal errors if exist so it is not much more complexity...

Anyway, if goal of zx project is to keep internal simplicity rather than portability and user performance, it is understandable to not bundle `node_modules` :)

I would be happy to continue these changes as a new project keeping credits to your awesome work on zx idea <3

**Comment by antonmedv** [comment]
> to distribute zx as a standalone js shell that can be embedded or distributed easily for pipelines

This is is more reasonable thought.

For know I like it's minimalist design as only a wrapper around a few other libs. 

Let's not introduce premature optimization, and see what real issues users will encounter.

**Comment by antonmedv** [comment]
I decided not to bundle zx.
