### ISSUE TITLE
Suggestion: export dedent template utility

### ISSUE THREAD

**Issue by troywweber7** [google/zx#505]
I just wanted to drop a suggestion to re-export the `dedent` function. It is helpful in writing help strings for a CLI.

```js
import dedent from 'dedent';

const HELP_MESSAGE = dedent`
    Usage: ...
`
```

**Comment by antonmedv** [comment]
This seems useful. But zx is already really big. 

Also in zx@dev you can use 

    zx —install script

**Comment by antonmedv** [comment]
https://github.com/google/zx/pull/522
