### ISSUE TITLE
Allow running a command from a string instead of string template

### ISSUE THREAD

**Issue by vjpr** [google/zx#508]
## Expected Behavior

```
const foo = 'foo'
const cmd = `${foo} bar`
console.log(cmd)
$(cmd)
```

Works.

## Actual Behavior

I doesn't work properly.

---

I want this so I can log commands before I run them.

# Related

https://github.com/google/zx/issues/394

**Comment by antongolub** [comment]
1. How it actually works:
```js
const args = [
    'npm',
    'install',
    '--no-save',
    '--no-audit',
    '--no-fund',
  ]
  const pieces = new Array(args.length + 1).fill(' ')

  await $(pieces as any as TemplateStringsArray, ...args)
  ```

2. [`quotes`](https://github.com/google/zx/blob/main/docs/quotes.md) stands for security reasons.

3. zx logs cmd if `$.verbose` is set to `true`. There's no need to add a custom hook for this.
```
export function log(entry: LogEntry) {
  switch (entry.kind) {
    case 'cmd':
      if (!entry.verbose) return
      process.stderr.write(formatCmd(entry.cmd))
      break
```

4. You can compose zx with any handlers:
https://github.com/qiwi/zx-extra/blob/master/src/main/js/index.mjs#L11
