### ISSUE TITLE
Dead link in README

### ISSUE THREAD

**Issue by ImLunaHey** [google/zx#509]
The "logging function" link goes to a 404. Not sure where this should be updated to since `log.ts` doesn't seem to exist anymore.

https://github.com/google/zx#log

> Specifies a [logging function](https://github.com/google/zx/blob/main/src/log.ts).

**Comment by jose-adalo** [comment]
This link works for me

<img width="747" alt="Screen Shot 2022-09-18 at 14 31 50" src="https://user-images.githubusercontent.com/101581398/190925106-dfb4e2fe-fbd7-4cb9-9996-d0c5e23330b2.png">
