### ISSUE TITLE
using colorette instead of chalk

### ISSUE THREAD

**Issue by pi0** [google/zx#52]
Chalk, however, is quite mature and most widely used package, is adding more Node dependencies, ~100KB install size, memory footprint, and `~36KB` to bundle size (#50, #51) which is ~40% of the entire bundle! One suggestion would be using [colorette](https://github.com/jorgebucaran/colorette) which is basically few lines of code, doing most of the formatting possibilities of chalk, supporting `NO_COLOR` and possibly making Deno support (#24) easier.

**Comment by antonmedv** [comment]
colorette is nice! But chalk is much, much wider used. So it makes chalk a better choice as more people familiar with it API.
