### ISSUE TITLE
Feature Request: Setting shell variables for specific commands

### ISSUE THREAD

**Issue by Ustice** [google/zx#520]
## Current behavior

Currently, if you want to pass in a number of variables, one way to do this is set them globally as environment variables.

```Typescript
process.env.FOO = 'bar'
$`echo $FOO`
```

This has the unfortunate effect of affecting other commands, which is a potential problem when running async processes.

Alternatively, If we know the environment variable names at runtime, we can also use this shell variables.

```typescript
const foo = 'bar'
$`FOO=${ bar } echo $FOO`
```

The problem is that if you do not know the names of the variables at compile-time, you can not add them to the shell variables due to how the strings are escaped.

```typescript
const fooName = 'FOO'
const fooValue = 'bar'
$`${ fooName }=${ fooValue }` // DOES NOT WORK
```

## Proposal

I propose adding a function under `$` that will be able to inject arbitrary variables into the shell environment for the single command. Perhaps something like this.

```typescript
const commandVariables = { FOO: 'bar' }
$.withVars(commandVariables)`echo $FOO`
```

Alternatively, maybe something more general to send options to the `$` function would be best. 

```typescript
const $$ = $.withOptions({
  verbose: false,
  variables: { FOO, 'bar' },
})
$$`echo $FOO`
```

**Comment by antonmedv** [comment]
You can use within():
```js
await within(async () => {
  $.env.FOO = 'bar'
  await $`echo $FOO`
})
```
The within() creates an async context so only stuff inside will be affected.
