### ISSUE TITLE
How to use `question` without feedback

### ISSUE THREAD

**Issue by banool** [google/zx#521]
## Expected Behavior
I'd like to be able to use the `question()` function add when I type, nothing appears, similar to `read -s`.

## Actual Behavior
It seems like this isn't possible today, all you can do is specify choices, no other options.

## Steps to Reproduce the Problem
```
question('Enter super private information: ');
```

## Specifications

- Version: 7.0.8
- Platform: MacOS 12.6, Node 18.9

**Comment by cyntler** [comment]
I am currently working on adding such a feature to this project. ;)
