### ISSUE TITLE
After upgrading to 7.1.0, zx start powershell as shell instead of Bash

### ISSUE THREAD

**Issue by budarin** [google/zx#523]
## Expected Behavior
run Bash as shell

we share the project between Windows, MacOs and Linux platforms, and we can't write scripts for Windows and Linux separately (we have a lot of them)!

## Actual Behavior
starts powerShell instead

## Steps to Reproduce the Problem

1. write code
```js
import { $ } from 'zx/core';

await $`rm -rf ./dist/client/assets.json`;
```
2. run the code
```bash
zx script.mjs
```
3. get the error
```
$ yarn zx ./script.mjs
yarn run v1.22.15
$ D:\Projects\raketa\raketa-web-app-boilerplate\node_modules\.bin\zx ./script.mjs
$ rm -rf ./dist/client/assets.json
Remove-Item : A parameter cannot be found that matches parameter name 'rf'.
At line:1 char:4
+ rm -rf ./dist/client/assets.json
+    ~~~
    + CategoryInfo          : InvalidArgument: (:) [Remove-Item], ParameterBindingException
    + FullyQualifiedErrorId : NamedParameterNotFound,Microsoft.PowerShell.Commands.RemoveItemCommand
 
Error: Remove-Item : A parameter cannot be found that matches parameter name 'rf'.
At line:1 char:4
+ rm -rf ./dist/client/assets.json
+    ~~~
    + CategoryInfo          : InvalidArgument: (:) [Remove-Item], ParameterBindingException
    + FullyQualifiedErrorId : NamedParameterNotFound,Microsoft.PowerShell.Commands.RemoveItemCommand
 
    at file:///D:/Projects/raketa/raketa-web-app-boilerplate/script.mjs:3:8
    exit code: 1
```

while with zx@7.0.8 everything works well
```
$ yarn run v1.22.15
$ D:\Projects\raketa\raketa-web-app-boilerplate\node_modules\.bin\zx ./script.mjs
$ rm -rf ./dist/client/assets.json
Done in 1.11s.
```

## Specifications

- Version: 7.1.0
- Platform: Windows 10

**Comment by budarin** [comment]
maybe still try to fix the problems with the "dollar" sign in sh/bash instead of simply replacing the execution environment with powershell?

**Comment by antonmedv** [comment]
>  to fix the problems with the "dollar" sign

$ is not an error. It's bash special syntax for strings. Apparently, you used cmd.exe. For me it's much easier to add support for pwsh. Excaping in cmd.exe is bad.

**Comment by budarin** [comment]
I wrote this after reading the contents of the last release, where this reason was given as the reason for switching to PowerShell

**Comment by ZiiMakc** [comment]
Same issue, how to switch to bash forcibly?

**Comment by budarin** [comment]
> Same issue, how to switch to bash forcibly?

in every script write by hand

```js
if (os.platform === 'win32) $.shell = 'bash'
```

**Comment by antonmedv** [comment]
Actually we can check for bash on windows automatically too!

**Comment by antonmedv** [comment]
Will do it.

**Comment by budarin** [comment]
> > Same issue, how to switch to bash forcibly?
> 
> in every script write by hand
> 
> ```js
> if ( os.platform === 'win32' ) $.shell = 'bash'
> ```

unfortunately this doesn't work :(

**Comment by antonmedv** [comment]
Fix https://github.com/google/zx/actions/runs/3202574452/jobs/5231685644

Try it:
```
npm i zx@dev
```

**Comment by budarin** [comment]
> zx@dev

it works!

**Comment by louisgv** [comment]
FYI, the new patch doesn't check if the bash is WSL or a TTY sim (like git bash). In my case, `bash` points to WSL environment which has its own file system, thus screwed up the pathing of my script.

**Comment by antonmedv** [comment]
> check if the bash is WSL or a TTY sim (like git bash).

Is there a way to check it? We dan update the logic.

**Comment by louisgv** [comment]
> > check if the bash is WSL or a TTY sim (like git bash).
> 
> Is there a way to check it? We dan update the logic. 

We can check if the user is running under wsl by using https://github.com/microsoft/WSL/issues/423#issuecomment-844417136

What's tricky is that there are several run cases:
- Invoking wsl under windows mounted system 
- Invoking wsl under WSL VM

Most user don't want the first, but they would want the 2nd. So it's really is a pairs checking for WSL and for maybe:

- cwd: the mount point on each system might be diff
- windows specific shell cmd: "get-command bash" and look at the source might give us a indicator that it's either git bash vs wsl

**Comment by antonmedv** [comment]
> Invoking wsl under WSL VM

zx will use bash in wsl right now.

**Comment by louisgv** [comment]
> > Invoking wsl under WSL VM
> 
> zx will use bash in wsl right now.

Just to illustrate the difference between the cases I mentioned above, here's a specific example:

0. git introduced fsmonitor
1. host user has git-window installed (with fsmonitor enabled)
2. host user also have WSL installed, and inside the WSL shell, also have git, with fsmonitor enabled
3. when host use zx to run git, it uses the wsl's bash env, which uses the wsl's git, which points fsmonitor to its own cache instead of the host's git-window's fsmonitor's cache -> resulting in mismatching cache. This causes tools to not recognize that file has been checked in (bc the fsmonitor cache is separated) -> git status shows wrong result (bc it's using fsmonitor cache from wsl)

**Comment by antonmedv** [comment]
I see. Let’s try to fix it. Maybe you can create a PR?

**Comment by Maikel-Nait** [comment]
After upgrading to 7.1.1, seems I'm hitting this problem.  zx then uses my WSL bash shell by default, and doing a simple "yarn" command yields the error `/mnt/c/Program Files/nodejs/yarn: 11: exec: node: not found`

In other words, I still have to resort to the original hack ...  :-D

**Comment by antonmedv** [comment]
And what zx should us in this case? Powershell?

**Comment by Maikel-Nait** [comment]
Honestly, I'm not familiar with all this WSL / bash paths entanglement. **louisgv** seems much more clear about it. For me the hack is good enough.  I'm just using Windows for development, but the final code will run on a Linux machine, so no big issues for me.

**Comment by mnpenner** [comment]
> The Linux world does not have posershell, and the commands in powershell and bash are different.
> 

I don't know what posershell is, but PowerShell is very much supported on linux, just FYI

**Comment by rxliuli** [comment]
Is there any progress? I expect to go to git bash by default on windows to run as a shell, most developers will install and use git, after all github needs it

**Comment by antonmedv** [comment]
Well, windows does not have bash by default. Only powershell.

**Comment by JenieX** [comment]
Man, I almost lost my mind trying to figure it out. Thank you [budarin](https://github.com/budarin), that did solve it for me.
```js
$.shell = 'C:\\Program Files\\Git\\bin\\bash.exe';
```
I think it must be at least noted in the main readme file that this package doesn't use bash. It would be better to set bash by default though.

**Comment by antonmedv** [comment]
Bash is default by default. Unfortunately on windows everybody install bash in different ways.

**Comment by JenieX** [comment]
> Bash is default by default. Unfortunately on windows everybody install bash in different ways.

Never mind. I just noticed it is noted in the [main page](https://github.com/google/zx#shell). 😄

**Comment by kcaswick** [comment]
What about checking what platform bash is built for, and skipping it if it is a Linux version when `process.platform === 'win32'`?

It would require 1 extra invocation of bash. Only using bash when `bash -c '[[ $OSTYPE != "linux"* ]]'` ([per SO](https://stackoverflow.com/questions/394230/how-to-detect-the-os-from-a-bash-script)) is true seems simplest, though a reasonable alternative would be `bash -c '[[ $OSTYPE == msys* || $OSTYPE == cygwin* || $OSTYPE == win32* ]]'`. Anyone know a reason one of these would fail, but not the other?

```ps1
PS> gcm -all bash

CommandType     Name                                               Version    Source
-----------     ----                                               -------    ------
Application     bash.exe                                           10.0.1904… C:\WINDOWS\system32\bash.exe

PS> C:\WINDOWS\system32\bash.exe --version
GNU bash, version 5.1.16(1)-release (x86_64-redhat-linux-gnu)
Copyright (C) 2020 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>

This is free software; you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
PS> C:\WINDOWS\system32\bash.exe -c 'echo $OSTYPE'
linux-gnu
PS> C:\WINDOWS\system32\bash.exe -c '[[ $OSTYPE != "linux"* ]]' ; $?                            
False
PS> C:\WINDOWS\system32\bash.exe -c '[[ $OSTYPE == msys* || $OSTYPE == cygwin* || $OSTYPE == win32* ]]' ; $?
False
PS> & $env:USERPROFILE\AppData\Local\Programs\Git\bin\bash --version
GNU bash, version 5.1.16(1)-release (x86_64-pc-msys)
Copyright (C) 2020 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>

This is free software; you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
PS> & $env:USERPROFILE\AppData\Local\Programs\Git\bin\bash -c 'echo $OSTYPE'  
msys
PS> & $env:USERPROFILE\AppData\Local\Programs\Git\bin\bash -c '[[ $OSTYPE != "linux"* ]]' ; $? 
True
PS> & $env:USERPROFILE\AppData\Local\Programs\Git\bin\bash -c '[[ $OSTYPE == msys* || $OSTYPE == cygwin* || $OSTYPE == win32* ]]' ; $?
True
PS> & $env:USERPROFILE\AppData\Local\Programs\Git\usr\bin\bash --version
GNU bash, version 5.1.16(1)-release (x86_64-pc-msys)
Copyright (C) 2020 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>

This is free software; you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
PS> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      7.2.9
PSEdition                      Core
GitCommitId                    7.2.9
OS                             Microsoft Windows 10.0.19045
Platform                       Win32NT
```

**Comment by kcaswick** [comment]
@Sojaner How do you handle the quoting issues with using `\`, `^`, `&`, `"`, etc.? 

It looks like Process X let an issue about how to include newlines go stale and get auto-closed. At a glance, it looks like they just ignore that `cmd` and `bash` handle escaping differently.

**Comment by Sojaner** [comment]
@kcaswick You are correct! That's a big problem with cmd and it makes the scenarios for windows very limited. But that's the same with batch scripts!
I don't write scripts for windows that often, but almost every time I end up with a "batch script" with some JavaScript goods from zx to make life a little easier!
