### ISSUE TITLE
After upgrading to 7.1  No quote function is defined: https://ï.at/no-quote-func

### ISSUE THREAD

**Issue by geoffreysamper** [google/zx#524]
## Expected Behavior
when running a command below expect that the command it echo the hostname. 
```
await $`echo ${process.env.HOSTNAME}`
````
## Actual Behavior
```
Error: No quote function is defined: https://ï.at/no-quote-func
    at Proxy.quote (file:///usr/local/lib/node_modules/zx/build/core.js:38:15)
    at Proxy.set (file:///usr/local/lib/node_modules/zx/build/core.js:74:19)
    at file:///entrypoint.mjs:1:8
    at ModuleJob.run (node:internal/modules/esm/module_job:198:25)
    at async Promise.all (index 0)
    at async ESMLoader.import (node:internal/modules/esm/loader:385:24)
    at async importPath (file:///usr/local/lib/node_modules/zx/build/cli.js:164:5)
    at async main (file:///usr/local/lib/node_modules/zx/build/cli.js:95:5)
```

If i go to the prev version of zx 7.0.8 everything works

## Steps to Reproduce the Problem
- when you run zx  on an linux alpine image
- created a small docker sample you can do by run `docker run  geoffreysamper/zx-alpine-issue`  the git repo for the sample is https://github.com/geoffreysamper/zx-issue-no-quote
## Specifications

- Version: zx 7.1.0
- Platform: alpine

**Comment by cyntler** [comment]
@geoffreysamper I wonder what's the difference between your code:

```ts
await $`echo ${process.env.HOSTNAME}`
```

and the one in readme (https://github.com/google/zx#passing-env-variables):

```ts
await $`echo $FOO`
```

The effect is probably the same, but I'm just wondering because I haven't tested it.

----

What is the effect when you use it like below?

```ts
await $`echo $HOSTNAME`
```

**Comment by antonmedv** [comment]
Alpine does not have bash. Only sh (csh probably?)  Zx doesn't have a quote function for csh, as zx uses $ escape bash feature. 

You can fix it by adding bash:

```docker
RUN apk update && apk add bash
```

**Comment by geoffreysamper** [comment]
when adding bash to it alpine image it works

**Comment by geoffreysamper** [comment]
When running using the bash variable instead of the process it works
```
await $`echo $HOSTNAME`
```
```
output: b972da089044
```

**Comment by antonmedv** [comment]
> When running using the bash variable instead of the process it works

Didn't get it.

**Comment by geoffreysamper** [comment]
when running  **await $`echo $FOO`** zx on run the command without error.

So changing the statement from
```
await $` echo ${process.env.FOO}` 
```
to 
```
await $`echo $FOO`
```

**Comment by geoffreysamper** [comment]
Is there a reason why bash is a requirement for zx. The puprose of the ZX is to use javascript and bash statement together. Isn't the quote function the same for most linux shells?

**Comment by antonmedv** [comment]
Unfortunately no. Bash has this nice quote C strings: https://www.gnu.org/software/bash/manual/html_node/ANSI_002dC-Quoting.html

**Comment by antonmedv** [comment]
https://unix.stackexchange.com/questions/371827/which-shells-support-ansi-c-quoting-e-g-string

**Comment by maitrungduc1410** [comment]
> Alpine does not have bash. Only sh (csh probably?) Zx doesn't have a quote function for csh, as zx uses $ escape bash feature.
> 
> You can fix it by adding bash:
> 
> ```
> RUN apk update && apk add bash
> ```

you saved me. This definitely needs to be specified in README

**Comment by svenjacobs** [comment]
I have a similar problem. I currently try to write a [Raycast script](https://github.com/raycast/script-commands) with `zx`. Unfortunately Raycast launches scripts in a non-login `/bin/sh` shell, so I get the same error (`No quote function is defined`). I currently struggle in finding the right shebang to launch the script in Bash and execute `zx`.

```
#!/bin/bash -l -c zx
```

doesn't work as it just executes the `zx` command without passing the scripts contents. Any idea?

**Comment by atsu85** [comment]
Probably the safest option is to still install and use bash to avoid issues when quoting is actually needed, but i thought i'll share my findings as well.

I managed to get it working on alpine with following patch for ash shell:
```patch
diff --git a/node_modules/zx/build/core.js b/node_modules/zx/build/core.js
index 6de412b..3354f76 100644
--- a/node_modules/zx/build/core.js
+++ b/node_modules/zx/build/core.js
@@ -49,6 +49,17 @@ catch (err) {
     if (process.platform == 'win32') {
         defaults.shell = which.sync('powershell.exe');
         defaults.quote = quotePowerShell;
+    } else {
+        if (process.platform == 'linux') {
+            try {
+                defaults.shell = which.sync('ash');
+                defaults.prefix = 'set -euo pipefail;';
+                defaults.quote = quote;
+            }
+            catch (err) {
+                // ignore - unknown linux shell
+            }
+        }
     }
 }
 function getStore() {
```
but i haven't tested it it also works if quoting would actually be needed (my use-case doesn't actually need quoting).

To make it backwards compatible with v7.0.8, better solution would be to modify [default quote implementation](https://github.com/google/zx/blob/b3fb79f49117c77000cc4872d6018500534315d5/src/core.ts#L70-L72), so it wouldn't fail if quoting is needed. @antonmedv, what do you think?

**Comment by antonmedv** [comment]
Let's stick with the bash.

**Comment by andrewmclagan** [comment]
Supporting `sh` and alpine would be pretty great for docker builds

**Comment by antonmedv** [comment]
sh in alpine uses variant of https://linux.die.net/man/1/ash which does not support bash `` $`...` `` syntax. And zx relies on this escape mechanism. 

But you can install bash in the docker container in a separate layer. It should be straightforward.
