### ISSUE TITLE
Feature: Abort controller support

### ISSUE THREAD

**Issue by vitalics** [google/zx#527]
As a part of node.js 16. Abort signal stable feature. I would like to propose [Abort signal](https://nodejs.org/dist/latest-v16.x/docs/api/globals.html#class-abortsignal) and [Abort Controller](https://nodejs.org/dist/latest-v16.x/docs/api/globals.html#class-abortcontroller) support.

API:
``` js
import { $ } from 'zx';
const controller = new AbortController();

$('some long command', {signal: controller.signal});

if(somethingHapens){ // e.g. ctrl+c
controller.abort();
}
// some long command will be halted.
```

**Comment by antonmedv** [comment]
What about kill() method? It already works.

**Comment by vitalics** [comment]
yes, that's worked, but the reason is resources. When signal comes for promises, it's not stops actually. and resources are not flushed. I mean what's happens when do the snippet:

```ts
function delay(ms: number){
	return new Promise(res => setTimeout(res, ms)})
}

await Promise.race([
delay(1000),
asyncFnLessThan1000ms(),
])
```
set timeout will not stops actually, results will be ignored (it takes machine time)

But if we use the signal to stop any async code(`setTimeout` in this case) - nodejs will real stop setTimeout fn and flush resources.

The same behavior for the child process, This feature will reduce process memory/time management

**Comment by gajus** [comment]
Native intertop with signal would make the API a lot nicer to use.

Now the API feels awkward:

```ts
handle: async ({ signal }) => {
  const promise = $`sleep 30`;

  const kill = () => {
    promise.kill();
  };

  signal.addEventListener('abort', kill, { once: true });

  await promise;

  signal.removeEventListener('abort', kill);
},
```

**Comment by antonmedv** [comment]
Please show an example with usage with signal vs kill()

**Comment by gajus** [comment]
Updated
