### ISSUE TITLE
Separate environment per invoked subprocesses

### ISSUE THREAD

**Issue by franky47** [google/zx#531]
## Expected Behavior

I use zx to automate some processes in a repository, which involves starting server subprocesses with different configurations, coming from the environment.

## Actual Behavior

Zx can only provide a single environment context to all subprocesses running in parallel, and cannot inject different values for a common environment variable name (eg: `PORT`).

## Steps to Reproduce the Problem

```js
process.env.FOO = 'common'

const common = () => $`echo common: $FOO`

const a = () => {
  $.env.FOO = 'a'
  return $`echo a: $FOO`
}

const b = () => {
  $.env.FOO = 'b'
  return $`echo b: $FOO`
}

// Expecting to see:
// common: common
// a: a
// b: b
await Promise.all([common(), a(), b()])

// But actually getting:
// common: b
// a: b
// b: b
```

The code above does not work as expected, as $.env is an alias of process.env, which is global and passed on as-is to all subprocesses.

It would be great to be able to override the env (or Options in general) used by `$`, for example:
```js
const $$ = $.withOptions({
  env: {
    FOO: 'c'
  }
})

$$`echo $FOO`

// or as a shorthand:
$.withOptions({
  env: {
    FOO: 'c'
  }
})`echo $FOO`
```

## Specifications

- Version: 7.0.8
- Platform: macOS 10.14.6, Node.js v16.14.0

**Comment by antonmedv** [comment]
Zx has a special func just for this case: within()

See https://github.com/google/zx#within

**Comment by franky47** [comment]
Perfect, thanks! I must have missed it in the docs.
