### ISSUE TITLE
7.1.1 broken on Windows 11 

### ISSUE THREAD

**Issue by srmagura** [google/zx#532]
## Expected Behavior

`npx zx test.mjs` works on Windows where `test.mjs` is:

```
$`echo 1`;
```

## Actual Behavior

```text
$ echo 1
Please enable the Virtual Machine Platform Windows feature and ensure virtualization is enabled in the BIOS.
For information please visit https://aka.ms/wsl2-install
```

This happens because `bash` points to `C:\Windows\system32\bash.exe`, which is not the real Bash, but rather some sort of "advertisement" for WSL.

## Specifications

- Version: 7.1.1
- Platform: Windows 11

**Comment by srmagura** [comment]
This was discussed in the comments of https://github.com/google/zx/issues/523 by the way.

**Comment by budarin** [comment]
Just install Git - it must be installed for development! :)
