### ISSUE TITLE
\x1B[2K\x1B[1G in stdout

### ISSUE THREAD

**Issue by edwardlaw2021** [google/zx#538]
## Expected Behavior

witout ANSI escape code in stdout

## Actual Behavior
run
```
await $`yarn config get registry`
```
output
```
ProcessOutput {
  stdout: '\x1B[2K\x1B[1Ghttps://npm-registry.xyz.net/\n',
  stderr: '',
  exitCode: 0
}
```

## Specifications

- Version: 4.3.0
- Platform: macOS 11.4

**Comment by antonmedv** [comment]
Try to upgrade to v7.
