### ISSUE TITLE
Provide out of the box experience for parsing cmd arguments passed to a zx script

### ISSUE THREAD

**Issue by IgnusG** [google/zx#549]
## Expected Behavior
When I pass it command arguments to a zx scripts like so `zx script.js --doMagic=true`. I would be great to have an easy way to parse these inside the script. There are plenty of libraries already available for this - similar to how zx bundles chalk it would be great if it provided something similar for cmd arguments as well.

## Actual Behavior
Currently you have to bring your own parser, use process.argv for simple parsing or build your own around it.

## Specifications

- Version: 7.1.1
- Platform: Linux - Node.js 19.0.0

**Comment by zloirock** [comment]
```js
echo(argv.doMagic) // => true
```
