### ISSUE TITLE
[Windows] URLs have appended $ character in front of them

### ISSUE THREAD

**Issue by folmert** [google/zx#551]
## Expected Behavior

```
await $`echo ${'https://www.google.com/'}`
await $`echo ${'string'}`
```

should result in

```
$ echo 'https://www.google.com/'
$'https://www.google.com/'
$ echo string
string
```

## Actual Behavior

```
await $`echo ${'https://www.google.com/'}`
await $`echo ${'string'}`
```

results in

```
$ echo $'https://www.google.com/'
$'https://www.google.com/'
$ echo string
string
```
Please notice:
 $ echo **$**'https://www.google.com/' - redundant $ in front of URL, it breaks most of commands where URLs are passed

## Steps to Reproduce the Problem

Just copy-paste the code and run on Windows.

## Specifications

- Version: 4.3.0
- Platform: Windows 10

**Comment by antonmedv** [comment]
https://github.com/google/zx/blob/main/docs/quotes.md

**Comment by folmert** [comment]
@antonmedv I don't see how it's related to the problem of URLs prefixed with dollar signs, it makes no difference if I pass a variable or a string with quotes.

**Comment by antonmedv** [comment]
https://ï.at/zx-quotes

**Comment by lostpebble** [comment]
![image](https://user-images.githubusercontent.com/1508863/206165231-530bb3d1-168c-4880-aaa7-702838cd4699.png)


![image](https://user-images.githubusercontent.com/1508863/206165043-d8348e20-844a-45dd-9a0d-975a051db8c6.png)

Having the same issue and the documentation there doesn't really demystify things for me.

As you can see doing this:

```ts
await $`git clone --branch ${branch} --depth 1 --filter=blob:none --sparse ${sourceGitRepo} ${targetGitDir}`
```

is outputting this:

```
git clone --branch master --depth 1 --filter=blob:none --sparse https://github.com/tamagui/tamagui.git $'C:\\Users\\paulm\\.tamagui\\tamagui'
```

When I do a `console.log(targetGitDir)` I get `C:\Users\paulm\.tamagui\tamagui` - so its a pretty normal string going into the command.

**Comment by timzaak** [comment]
use `execSync` to replace `$`.
```typescript
import {execSync} from 'node'

execSync(`xx "${path}"`)
```

**Comment by engina** [comment]
This issue persists

**Comment by Visual-Dawg** [comment]
I am on Linux and also get this behavior.
