### ISSUE TITLE
Feature request: Configuration of minimist

### ISSUE THREAD

**Issue by sstendal** [google/zx#553]
It is currently difficult to use the minimist integration if you have a combination of boolean arguments and unnamed arguments.

This example script will fail if the -h option is placed before the filename parameter

```
#!/usr/bin/env zx

$.verbose = false

const header = argv.header || argv.h
const filename = argv._[0]

if (header) {
  console.log('Filename: ', filename)
}

$`cat ${filename}`.pipe(process.stdout)
```

```
// This will fail, since 'myfile.txt' will be interpreted as the value of -h
myscript.mjs -h myfile.txt

// This will work as expected
myscript.mjs myfile.txt -h 
```

A solution to this would be either:

A) A possibility to provide a configuration for minimist.

B) Expose the minimist package to the script, so that the script writer may call it directly and provide a configuration

I believe A) would be better, while B) would be easier to implement

**Comment by antonmedv** [comment]
> B) Expose the minimist package to the script, so that the script writer may call it directly and provide a configuration

This option is already available. Just import minimist.

**Comment by sstendal** [comment]
Maybe I misunderstand this, but importing minimist as an external package will require that minimist is available as an external package for everyone that should run the script, or run zx with the --install parameter.

If I just add this line to the script above, and does not run zx with --install, then I get an error.

```
import minimist from 'minimist'
```

The error message (as expected, I believe)

```
Error [ERR_MODULE_NOT_FOUND]: Cannot find package 'minimist' ...
```

Since minimist is already imported by zx, maybe it would be possible to expose minimist to the script as a global variable in the same way as chalk, which, YAML etc.?

**Comment by antonmedv** [comment]
I see, script out of node_modules folder. Yes, this will require -install flag.

**Comment by aarondill** [comment]
A few ideas on how to implement this:
1. Expose the minimist module as a global minimist
2. Expose the minimist.parseArgs function as a global parseArgs
3. Modify the updateArgv function in src/goods.ts to accept an optional options argument and expose it.

**Comment by ReeganExE** [comment]
Since we need to configure our program to accept both long and short arguments (`-e/--expression`), it would be helpful if `updateArgv` accepted minimist options, allowing us to add aliases to minimist.

https://github.com/google/zx/blob/101b810df1874cef6adbdea7d1e91bc206ff7818/src/goods.ts#L33-L36

Alternatively, developers can import 'minimist' and parse arguments themselves, but it can result in another issue with ES Modules: https://github.com/google/zx/issues/595#issuecomment-1465181746. So `import minimist from 'minimist'` will not work (at runtime) in ES Module mode as mentioned in the referenced comment.

**Comment by antonmedv** [comment]
Good point. Let’s expose minimist.

**Comment by alpap** [comment]
Any update on this?
is the package exposed now?

**Comment by antonmedv** [comment]
No update.
