### ISSUE TITLE
Exception object not displayed in echo

### ISSUE THREAD

**Issue by corporateuser** [google/zx#567]
## Expected Behavior
`try {....} catch (e) {console.log(e); echo(e)}` should print exception information twice, but `echo(e)` prints nothing.

## Actual Behavior
`echo(error)` where `error` is exception object prints nothing

## Steps to Reproduce the Problem

1. create 123.mjs file:
```JS
#!/usr/bin/env zx
$.verbose = false;
try {
    const str = 'aa';
    await $`grep ${str}${str} 123.mjs`
} catch (error) {
    console.log(error);
    echo(error)
}
```
2. Execute it with `zx 123.mjs`
1.

## Specifications

- Version: 7.1.1
- Platform: MacOS 12.6.1, node 18.12.1

**Comment by antongolub** [comment]
`echo`API  is not suitable for raw object printing and focuses on tpl literals.

```ts
export function echo(pieces: TemplateStringsArray, ...args: any[]) {
  let msg
  const lastIdx = pieces.length - 1
  if (
    Array.isArray(pieces) &&
    pieces.every(isString) &&
    lastIdx === args.length
  ) {
    msg =
      args.map((a, i) => pieces[i] + stringify(a)).join('') + pieces[lastIdx]
  } else {
    msg = [pieces, ...args].map(stringify).join(' ')
  }
  console.log(msg)
}
```

So you can try smth like this instead:
```
echo`${error}`
```

**Comment by antonmedv** [comment]
Should we make echo(x) also work?

**Comment by corporateuser** [comment]
Changing function to template literal does not change anything, it still prints nothing for Error object.

**Comment by corporateuser** [comment]
Another acceptable solution could be a change of the documentation. Currently it states: 

> echo()
> A console.log() alternative which can take [ProcessOutput](https://github.com/google/zx#processoutput).

Which is not completely true.
