### ISSUE TITLE
Update node-fetch to native fetch

### ISSUE THREAD

**Issue by njfamirm** [google/zx#568]
Hi!

Node support [fetch](https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API) natively from 18.0.0 version, Is it time to use Fetch natively?

**Comment by njfamirm** [comment]
I can do this

**Comment by antonmedv** [comment]
Well. A lot of users still on node16. GitHub Actions for example.

**Comment by njfamirm** [comment]
ok!

**Comment by njfamirm** [comment]
#589 & #619 🎉
