### ISSUE TITLE
Support ~~~ syntax in md

### ISSUE THREAD

**Issue by nichtich** [google/zx#578]
## Expected Behavior

[Fenced Code blocks](https://spec.commonmark.org/0.30/#fenced-code-blocks) in Markdown should be executed as documented no matter which markup variant is used. 

## Actual Behavior

Only <code>```</code> is detected to start a code block (implemented in `transformMarkdown`).

## Steps to Reproduce the Problem

Execute this file with `zx`:

~~~~~~

````js
echo("code block with more then three `")
````

~~~js
echo("code block with ~")
~~~

~~~~~~

## Solution

Add a `markup` variable to `transformMarkdown` storing the markup style. Replace ` ``` ` with Regexp capturing group ` (```+|~~~+) ` to get the current markup style.

## Version

- Version: 7.1.1

**Comment by HwangTaehyun** [comment]
Can I fix this? That's good support!
