### ISSUE TITLE
Why to replace my command?

### ISSUE THREAD

**Issue by classmatewu** [google/zx#584]
```
import { $ } from 'zx'

const arg = 'echo /dev/vdb /data ext4 defaults 0 0 >> /etc/fstab'

await $`ssh root@1.1.1.1 -p 22 ${arg}`
```

## Expected Behavior
ssh root@1.1.1.1 -p 22 echo /dev/vdb /data ext4 defaults 0 0 >> /etc/fstab

## Actual Behavior
ssh root@1.1.1.1 -p 22 $'echo /dev/vdb /data ext4 defaults 0 0 >> /etc/fstab'

## Desc
Why to replace my command?
<img width="455" alt="image" src="https://user-images.githubusercontent.com/44048381/220362763-8fe7fbc0-cd83-4b0d-b514-7add02f22845.png">

- Version: 7.1.1
- Platform: MacOS Catalina

**Comment by antonmedv** [comment]
Documentation on why zx is doing this: https://xn--gda.at/zx-quotes

If you want an ssh command, you can use my new tool [Webpod](https://github.com/webpod/webpod)

```js
import {ssh} from 'webpod'

const $ = ssh('1.1.1.1')
await $`echo /dev/vdb /data ext4 defaults 0 0 >> /etc/fstab`
```

Works both on node & deno!

**Comment by classmatewu** [comment]
It's cool, does it support setting port?

**Comment by antonmedv** [comment]
It will be. It's under development.
