### ISSUE TITLE
Feature request: accept a minimist-like object of arguments in $`command`

### ISSUE THREAD

**Issue by pizzafroide** [google/zx#592]
Up to now, <code>$\`command ${arg}\`</code> processes:

- arrays (by substituting and quoting each of its items, then joining them using space characters), 
- objects with a `stdout` property (by substituting them with the value of `stdout`, then quoting it), 
- and any other value is "stringified" and quoted. 

It would be interesting to also have a special treatment for objects that don't have a `stdout` property and which don't override `toString` (as in `o.toString !== Object.prototype.toString`). This kind of objects could be seen as minimist-like objects, and would be substituted like so:

```js
$`command ${{
  _: ['foo', 'bar'],
  a: true,
  bc: true,
  d: 'value',
  e: ['value1', 'value2'],
  '-f': 'value',
  '--': {
    g: true
  }
}}`
// $ command -a -bc --d value --e value1 --e value2 -f value foo bar -- -g
```

**Comment by antonmedv** [comment]
Interesting idea. Let me think about it.

**Comment by Kikobeats** [comment]
Dropping this for inspiration purpose: https://github.com/vercel/edge-functions/pull/556

**Comment by RavenColEvol** [comment]
@antonmedv I would like to take this up looks interesting.

**Comment by antonmedv** [comment]
I’m still not sure we need this.
