### ISSUE TITLE
$.nothrow is not a function

### ISSUE THREAD

**Issue by Kikobeats** [google/zx#594]
## Expected Behavior

The deprecation message is saying `use $.nothrow instead of nothrow` but actually `$.nothrow` is not exported properly

## Actual Behavior

The zx version is the latest:

```
cat node_modules/zx/package.json | grep version
"version": "7.2.0"
```

```
> const { $ } = await import('zx')
> $.nothrow
undefined
```

**Comment by antonmedv** [comment]
$ return ProcessPromise class. Call a method on it.

```
const { $ } = await import('zx')
await $`exit 1`.nothorw()
```

**Comment by Kikobeats** [comment]
oh, makes sense!
