### ISSUE TITLE
Error on script with shebang but without file extension

### ISSUE THREAD

**Issue by brandonpittman** [google/zx#60]
## Expected Behavior

When including `#!/usr/bin/env zx` at the top of a file, it just runs.

## Actual Behavior

If the script has no file extension this error occurs:

```
node:internal/process/esm_loader:74
    internalBinding('errors').triggerUncaughtException(
                              ^

TypeError [ERR_UNKNOWN_FILE_EXTENSION]: Unknown file extension "" for /Users/xxx/.git/hooks/pre-push
    at new NodeError (node:internal/errors:329:5)
    at Loader.defaultGetFormat [as _getFormat] (node:internal/modules/esm/get_format:71:15)
    at Loader.getFormat (node:internal/modules/esm/loader:102:42)
    at Loader.getModuleJob (node:internal/modules/esm/loader:231:31)
    at async Loader.import (node:internal/modules/esm/loader:165:17)
    at async file:///Users/blp/.fnm/node-versions/v15.12.0/installation/lib/node_modules/zx/zx.mjs:57:5 {
  code: 'ERR_UNKNOWN_FILE_EXTENSION'
}
```

I expected any script with the shebang to work, as any other shell script would. Requiring a file extension restricts where zx scripts can be run from.

Is this a limitation of ESM?

## Steps to Reproduce the Problem

1. create zx script in `.git/hooks/pre-push`
1. push to repo

## Specifications

- Version: 1.2.2
- Platform: darwin

**Comment by SirWindfield** [comment]
Nop, top-level async/await requires the file to me an ESM file. IIRC there are two ways to tell node the file is one:

1. Through a key inside the `package.json` file (which scripts don't have)
2. Through the `.mjs` file extension
