### ISSUE TITLE
Allow to initialize $

### ISSUE THREAD

**Issue by gajus** [google/zx#600]
The current API feels awkward, whereby settings are applied after the command, i.e.

```ts
$`date`
  .nothrow()
  .quiet();
```

I'd like to be able to do something like

```ts
const $ = createZx({
  nothrow: true,
  queit: true,
});

$`date`
```

**Comment by antongolub** [comment]
I believe v8 will bring smth similar. Here's a proposal: https://github.com/qiwi/zx-extra/blob/master/src/main/js/index.mjs#L40

**Comment by antonmedv** [comment]
Yes, I'd like to refactor the api to allow more easy customizations. 
```js
$({nothrow: true})`cmd`
```
