### ISSUE TITLE
Feature Request: Allow `cd` to be used silently

### ISSUE THREAD

**Issue by Wyatt-Stanke** [google/zx#605]
## Feature Request
`cd` should have some sort of way to be used silently because it is pretty much the only way to change the directory.
Example API:
```js
cd("src/", { quiet: true })
```
I would be willing to implement this if you think that this is a good idea.

## Specifications

- Version: 7.2.1
- Platform: MacOS Monterey

**Comment by JAForbes** [comment]
Be nice if it was `cd(...).quiet()` to be consistent with ProcessPromise
