### ISSUE TITLE
Feature Request: Add support for multiple spinners

### ISSUE THREAD

**Issue by invakid404** [google/zx#606]
## Feature Request

It would be very useful to be able to use `spinner` in parallel. I have multiple long-running commands that are independent from each other, and I want to run them in parallel and visually show which ones are running using `spinner`, but currently, that doesn't seem to be possible, as I can only see one spinner at a time.

In terms of how it should look like, I just imagine the exact same spinners stacked on top of each other, although I wouldn't be opposed to something fancier.

**Comment by antonmedv** [comment]
Well, this will be pretty challenging to do. Maybe with an api change, where spinner takes a few parallel items.

**Comment by invakid404** [comment]
If I'm imagining the same API as you, it would probably cover my use case fully, as long as I have control over the content of the spinner so that I can change its text as I go so that I can reuse the same spinner for two long running commands that depend on each other.

What would you say is the biggest challenge about implementing it in a way that it "just works", i.e. you just call `spinner` twice and two spinners appear on top of each other? If that's not intended to work, should calling `spinner` in parallel result in an error?

**Comment by antonmedv** [comment]
Can you share an example of how you are using the spinner? 

I actually have an idea on how to implement it.

**Comment by invakid404** [comment]
What I tried and realized it didn't work looked a bit like this:

```ts
const longRunningTask1 = async () => {
  await spinner('Performing long running task 1', () => $`sleep 15`)
}

const longRunningTask2 = async () => {
  await spinner('Performing long running task 2 (step 1)', () => $`sleep 5`)

  await spinner('Performing long running task 2 (step 2)', () => $`sleep 5`)
}

await Promise.all([longRunningTask1(), longRunningTask2()])
```

When I run this, I see the second spinner come up. When it finishes, the third one comes up. And when the third one finishes, the first one takes over.

What I was imagining was that I should get two spinners initially, and after the second one completes, it would disappear and the third one would effectively take its place. On second thought, it would be kind of tricky to implement indeed, especially if spinners aren't the only thing that are outputting things (although I have no clue what the behavior is currently even with a single spinner).

**Comment by antonmedv** [comment]
> (although I have no clue what the behavior is currently even with a single spinner)

Just clear one line and print the spinner.

**Comment by invakid404** [comment]
I see, the reason that other things can kind of output things as a spinner is running is that the spinner always leaves the cursor at the beginning of the line, meaning that when something else outputs something, it will just push the spinner to the next line and things will continue to work as normal. The only downside being, of course, is that if your output isn't long enough to cover the entire space that the spinner used to take on that line, part of the spinner will be left behind, but at least the output isn't majorly screwed up.

As long as we can agree that this is a reasonable behavior, I think it wouldn't be too hard to support multiple spinners on multiple lines, as long as each update of these spinners leaves the cursor before the uppermost one.

**Comment by invakid404** [comment]
I think I managed to write something that supports multiple spinners at once: [gist](https://gist.github.com/invakid404/60b69ff654d0173a07ac3bf86609c79b).

Here's a recording of it in action: [asciinema link](https://asciinema.org/a/571773).

It does exactly what I suspected would work: each iteration, it filters out only the spinners that are still running, and prints their text, after which it goes and cleans up the lines that were previously occupied by spinners that are now done. In the end, it just snaps the cursor back up before the first spinner. This way, when something else is printing at the same time, it works the same way it currently does in zx: it writes over the spinners. Spinners are then redrawn the next time `updateSpinners` is called.

I'm not sure if I've covered all tough cases in the sample program, but it successfully handles spinners with different durations and spinners that are added in the process of execution, while preserving the other stuff that was outputted.

**Comment by invakid404** [comment]
@antonmedv I'd appreciate getting some feedback on the sample I sent in the last comment. If you think it's good enough, and if it suits the project, I'd love to move this forward by putting together a PR. If not, let's discuss alternatives :^)

I'm not sure what the cross-platform compatibility requirements of zx are, i.e. if it's okay to use ANSI escape codes, which my implementation relies heavily on. The only users who might suffer are people who use Windows Console on old versions of Windows (pre-Windows 10 version 1511). Windows Terminal, which Microsoft seems to be pushing as the new default, supports them.

**Comment by antonmedv** [comment]
I'm already started my own solution) Same with multiline spanners.

**Comment by invakid404** [comment]
Good to know you're invested in this :^) Would love to see it finished soon.

**Comment by antonmedv** [comment]
😉 https://github.com/sponsors/antonmedv
