### ISSUE TITLE
readline() is not defined

### ISSUE THREAD

**Issue by Siddhant-K-code** [google/zx#61]
## Expected Behavior
Take Input from User

## Actual Behavior
```bash
ReferenceError: `readline` is not defined
    at ModuleJob.run (node:internal/modules/esm/module_job:175:25)
    at async Loader.import (node:internal/modules/esm/loader:178:24)
    at async file:///usr/local/lib/node_modules/zx/zx.mjs:58:5
```

## Steps to Reproduce the Problem

- While Running this Script
```javascript
#!/usr/bin/env zx

const a = readline();
const b = readline();
const sum = a + b;
console.log("Sum is: " + sum);

```

**_I have created a [zx-examples](https://github.com/Siddhant-K-code/zx-examples) for all uses cases of this amazing script_** 

## Specifications

- Version: 1.4.0
- Platform: VSCode, Ubuntu

**Comment by quantumsheep** [comment]
You might want to use `question()` as a substitute:
```js
#!/usr/bin/env zx

const a = await question('');
const b = await question('');
const sum = a + b;
console.log("Sum is: " + sum);
```

**Comment by Siddhant-K-code** [comment]
> Also considering your code, you may want convert `a` and `b` to numbers as `a` and `b` will be strings.

yeah, that's why it will be good if we can take integers as input also.
