### ISSUE TITLE
pipe is not available when using ssh

### ISSUE THREAD

**Issue by chetan24d** [google/zx#612]
## Expected Behavior
The .pipe() should be available when ssh is used.

```
import { ssh } from 'zx'

await ssh('user@host')`echo Hello, world!`.pipe()

```
## Actual Behavior
.pipe() is not available

## Steps to Reproduce the Problem

1. 
1.
1.

## Specifications

- Version: 7.2.1
- Platform: Mac terminal

**Comment by nazrul7711** [comment]
hey @chetan24d i wanna work on this problem
