### ISSUE TITLE
zx --install do not install dependencies

### ISSUE THREAD

**Issue by pawelmidur** [google/zx#618]
## Expected Behavior
It should install all the dependencies that are included in the file, version 7.2.0 has no problem but version 7.2.2 installs nothing and show error

## Actual Behavior
```
$ node -v
v16.20.0
$ npm i zx --location=global
added 56 packages, and audited 57 packages in 5s
10 packages are looking for funding
$ zx -v
7.2.2
$ zx --install ./.deploy/deployer.mjs -e front
Error [ERR_MODULE_NOT_FOUND]: Cannot find package 'node-ssh' imported from /builds/......ployer.mjs
    at new NodeError (node:internal/errors:387:5)
    at packageResolve (node:internal/modules/esm/resolve:852:9)
    at moduleResolve (node:internal/modules/esm/resolve:901:20)
    at defaultResolve (node:internal/modules/esm/resolve:1115:11)
    at nextResolve (node:internal/modules/esm/loader:163:28)
    at ESMLoader.resolve (node:internal/modules/esm/loader:841:30)
    at ESMLoader.getModuleJob (node:internal/modules/esm/loader:424:18)
    at ModuleWrap.<anonymous> (node:internal/modules/esm/module_job:76:40)
    at link (node:internal/modules/esm/module_job:[75](https://gitlab.com/........139#L75):36) {
  code: 'ERR_MODULE_NOT_FOUND'
}
```

Version 7.2.0 has no such problems and the whole script works fine, I have not checked version 7.2.1 but it seems to me that it works, because the problems started to occur 4 days ago

## Specifications

- Version: 7.2.2
- Platform: node v16.20.0

**Comment by ronitsharma03** [comment]
@pawelmidur  Is this assigned to someone. If not i would like to work on this issue !

**Comment by pawelmidur** [comment]
> @pawelmidur Is this assigned to someone. If not i would like to work on this issue !

no one is assigned, so go ahead 👍

**Comment by ronitsharma03** [comment]
@pawelmidur thanks a lot!

**Comment by ronitsharma03** [comment]
@pawelmidur Can you give me more information on the error.
I tried some methods like by changing the permissions of the script to make it executable by running the following command in the terminal:-  chmod +x my-script.sh
and even sudo my-script.sh but not doing anything

**Comment by pawelmidur** [comment]
I checked and it only occurs when the files are import:

`script.mjs`
```
#!/usr/bin/env zx

import 'zx/globals';

import { dep } from './dep.mjs';

dep();
await $`echo START!`;
```
`dep.mjs`
```
import chalk from 'chalk';

export const dep = async () => {
  console.log(chalk.greenBright('Test dependencies on other file'));
};
```

and run `zx --install ./script.mjs` 

I don't know if this is the correct use flag --install, but it works on version 7.2.1

**Comment by ronitsharma03** [comment]
@pawelmidur I think i got the fix ! :)

**Comment by ronitsharma03** [comment]
@pawelmidur In this command zx --install ./.deploy/deployer.mjs -e front it is looking for deployer.mjs file in .deploy directory but it is missing. Maybe it's got deleted accidentally! Can you check please?

**Comment by pawelmidur** [comment]
> @pawelmidur In this command zx --install ./.deploy/deployer.mjs -e front it is looking for deployer.mjs file in .deploy directory but it is missing. Maybe it's got deleted accidentally! Can you check please?

I don't think it's a problem with any package inside ZX, I just think it's a problem with parsing dependencies and pasting them into the command line that need to be installed when using the `--install` flag

so install `node-ssh` inside ZX will not help

**Comment by jianwu** [comment]
Seems the @dev version works. `npm i -g zx@dev`
