### ISSUE TITLE
Property 'nothrow' does not exist on type 'Shell & Options'

### ISSUE THREAD

**Issue by p10** [google/zx#622]
## Expected Behavior

Type declaration for function nothrow

## Actual Behavior

no type declaration

## Steps to Reproduce the Problem

```
// in typescript file
import { $ } from 'zx';
$.nothrow($`git status`);
```

## Specifications

- Version: 7.2.2
- Platform: macOS

**Comment by antongolub** [comment]
Seems like a typo deprecation notice.
```
$`git status`.nothrow()
```
