### ISSUE TITLE
log function writes to process.stderr instead of process.stdout when no error occurs

### ISSUE THREAD

**Issue by javadkh2** [google/zx#623]
## Expected Behavior
The **log** function should write its output to **process.stdout** if there is no error.

## Actual Behavior

The **log** function currently writes its output to **process.stderr** even when there is no error, which causes a process supervisor app to treat it as a warning, even if the script exits normally.

## Steps to Reproduce the Problem

1. Create a script file and name **ls.mjs**
```javascript
#!/usr/bin/env zx
$`ls`;
```
2. Run the script and write the stderr to an error file 
```bash
./ls.mjs 2> error.log
```
3. **error.log**  contains the output of the ls function, whereas it should be empty as there were no errors or warnings

## Specifications

- Version: 7.2.2
- Platform: MacOs Ventura, nodeJs 18.16.0

**Comment by antongolub** [comment]
There's no _right_ answer as to where output should be placed and which format is preferable. You can switch logs forwarding from `stderr` to `stdout` via [$.log option customization](https://github.com/google/zx#log).
https://github.com/google/zx/blob/main/src/core.ts#L227
https://github.com/google/zx/blob/main/src/core.ts#L479

**Comment by antonmedv** [comment]
For next zx version:

**Comment by antonmedv** [comment]
For the next version, I think to change this little bit.

1. STDOUT output will be "quiet" mode. The stdout output will be collected, but not re-printed.
2. STDERR will be redirected to stderr by default. And also collected.

**Comment by javadkh2** [comment]
> zx log is a kind of `debug`. There's no _right_ answer as to where output should be placed and which format is preferable. Similar discussion about winston: [winstonjs/winston#927](https://github.com/winstonjs/winston/issues/927)
> 
> Anyway, you can switch logs forwarding from `stderr` to `stdout` via [$.log option customization](https://github.com/google/zx#log).
> 
> https://github.com/google/zx/blob/main/src/core.ts#L227 https://github.com/google/zx/blob/main/src/core.ts#L479

Yes, Eventually I fixed it by using the custom log. I think it would be be beneficial to mention this behaviour in the documentation. finding the root cause of the issue was not clear at all.
Actually, I have replaced a shell script with a zx script and then it broke my ci as zx sends everything to STDERR and the ci considered that as a warning. I think this behavior is quite common, and many developers set the fail level to warning to ensure higher quality.
