### ISSUE TITLE
color mismatching when we hover both the buttons

### ISSUE THREAD

**Issue by Nitishupkr** [google/zx#624]
## Expected Behavior
when we hover to both the buttonss try runkit and  report malware
when we hover try runkit it changes from light green to dark green
when we hover report malware button it changes from red to black   so both the buttons looking  odd when we hover

## screenshot

https://github.com/google/zx/assets/95420063/0deb003e-f1dd-4673-8035-7ba41d426c92

when we hover report malware  button  it should be  from light red to dark red just like try runkit

## Steps to Reproduce the Problem

1.https://www.npmjs.com/package/zx

## Specifications
I m working on it
- Version:
- Platform:

**Comment by Nitishupkr** [comment]
@antonmedv please see it

**Comment by antonmedv** [comment]
Sure. Sure. Will fix it.
