### ISSUE TITLE
Feature Request: shell/zx polyglot

### ISSUE THREAD

**Issue by midzelis** [google/zx#631]
Using here docs is really powerful way to have zx execute embedded code from within scripts. 

i.e. this trivial script will install all the dependencies needed to launch the rest of the script
```
#!/bin/bash
curl -s https://get.volta.sh | bash
volta install node
volta install zx
zx << 'EOF'
console.log("Script execution a success!")
EOF
```

However, if you try to launch this script via zx, it will fail, since it doesn't "understand" the shell script. 

Idea: allow zx to support polyglot shell/.mjs files. When launched via shell, it will run and install the dependencies for zx - and then launch zx. When launched with zx - zx will look for special markers to understand where the start/end of the zx code is. 

The above example becomes: 

```
#!/bin/bash
curl -s https://get.volta.sh | bash
volta install node
volta install zx
zx << 'EOF'
~~~~~zx start~~~~~
console.log("Script execution a success!")
~~~~~zx end~~~~~
EOF
```

and it can be launched via `/bin/bash demo` or `zx demo` or even `zx http://example.com/demo`

This is similar to how the .md parsing support works, but .md files aren't interpretable by most shells ;-) 

The main purpose of this is to allow a file to self-install the prereqs to launch itself.

**Comment by RokkuCode** [comment]
jm2c: i don't like the extra markers for the zx approach. there are markers "zx << 'EOF'". why can't zx look for them? then there is no need for the wormy lines.
