### ISSUE TITLE
kill() should only resolve when the process exits

### ISSUE THREAD

**Issue by gajus** [google/zx#639]
## Expected Behavior

```ts
kill().then(() => { console.log('expect this to be called only when process exist'); })
```

## Actual Behavior

```ts
kill().then(() => { console.log('not clear when this is called, but the process is still up'); })
```

## Specifications

- Version: v7.2.1
- Platform: macOS

**Comment by gajus** [comment]
Something like this https://github.com/gajus/turbowatch/commit/f9966be788c21c60fb7d12af6c1543e0724449a9

**Comment by antongolub** [comment]
The current impl just emits `resolved` when all associated processes have received the signal. Perhaps, sometimes we should wait for all these signals to be processed, but status polling via `cp.spawn` requires configurable timings, debounces, etc. I suggest providing this externally if necessary: `$.kill = async () => {}`
