### ISSUE TITLE
Add GitHub release?

### ISSUE THREAD

**Issue by OmgImAlexis** [google/zx#64]
It'd make it easier to find the current version, etc. if GitHub release were to be used.

Even better would be to add an automated GitHub actions workflow to handle this.

**Comment by Nixinova** [comment]
Was just about to suggest this, the project has no tags and no changelog currently.

**Comment by antonmedv** [comment]
Can somebody implement it?

**Comment by Nixinova** [comment]
Only those with write access can create tags and releases

**Comment by antongolub** [comment]
@antonmedv, what's about `semantic-release`?

* conventional commits
* auto-generated changelog
* release commits and tags
* npm publishing

**Comment by FarazzShaikh** [comment]
@antongolub are you still working on this? I too have an GitHub Actions setup with those features I can quickly add.

**Comment by antonmedv** [comment]
Sure, send a PR.

**Comment by antongolub** [comment]
@FarazzShaikh, @antonmedv,

Is it ok, that release action would be added before autotests? https://github.com/google/zx/pull/69

**Comment by FarazzShaikh** [comment]
@antongolub i think it would be better if the release is made only after tests pass, what do you think?

**Comment by antonmedv** [comment]
Just add npm test before.

**Comment by antonmedv** [comment]
Done!
