### ISSUE TITLE
Docker build command (with multiple -t option) doesn't work for unknonw reason

### ISSUE THREAD

**Issue by pillsilly** [google/zx#643]
## Expected Behavior

A docker build command wrapped by zx should have exact the same behavior as without it.

## Actual Behavior

$ $'sudo docker build -t memlab:0.1 -t memlab:latest -f ./Dockerfile . '
/usr/bin/bash: sudo docker build -t memlab:0.1 -t memlab:latest -f ./Dockerfile . : No such file or directory
Error: /usr/bin/bash: sudo docker build -t memlab:0.1 -t memlab:latest -f ./Dockerfile . : No such file or directory

If I copy the printed command, e.g `sudo docker build -t memlab:0.1 -t memlab:latest -f ./Dockerfile`
it got executed perfectly

the build command is composed with zx as below
```
const latestTag = latest ? `-t memlab:latest`: '';
const buildCommand = `sudo docker build -t memlab:${v} ${latestTag} -f ./Dockerfile . `;
await $`${buildCommand}`
```

but if I don't try to append the 2nd -t option 
e.g
`const buildCommand = `sudo docker build -t memlab:${v} -f ./Dockerfile . `;`
everything works well too.

## Steps to Reproduce the Problem

1. have ax implmenetation as above
```
const latestTag = latest ? `-t memlab:latest`: '';
const buildCommand = `sudo docker build -t memlab:${v} ${latestTag} -f ./Dockerfile . `;
await $`${buildCommand}`
```
2. execu it.

## Specifications

- Version: 7.2.2
- Platform: `uname -a
Linux controller 5.4.0-113-generic #127-Ubuntu SMP Wed May 18 14:30:56 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux`

**Comment by antonmedv** [comment]
Please read https://ï.at/zx-quotes
