### ISSUE TITLE
feat: Add a progress bar package like 'progress' or 'cli-progress'

### ISSUE THREAD

**Issue by redsuperbat** [google/zx#644]
Sometimes you are downloading large files or running cpu intensive jobs in a script. 

In those cases it would be nice to show a progress bar in the terminal without having to install extra packages.

**Comment by antonmedv** [comment]
Yeap. I'm not working on a new pool functionality. The progress bar also will be added.

**Comment by dominikj111** [comment]
Just wondering about this too  @antonmedv
