### ISSUE TITLE
new ProcessOutput throw error,  at "zx\build\core.js:146"

### ISSUE THREAD

**Issue by gaoyujin** [google/zx#652]
## Expected Behavior

exec pnpm run dev ，we can open the web

## Actual Behavior

now，the error throw

## Steps to Reproduce the Problem
1. environment：

- mac is ok
- window 10 is error

2.  my script code：
![image](https://github.com/google/zx/assets/58320600/0ca9d99f-175e-493a-b1e9-053812ce1d15)
3. package.json setting:   "dev": "./script/dev.ts",
4.  Command failed with exit code 1：
![image](https://github.com/google/zx/assets/58320600/7b346171-0b7f-496b-a154-93886fb44be0)

## Specifications

- Version:  nodejs 18.16.0 、 pnpm 8.6.10  、zx 7.2.2
- Platform:  window 10

**Comment by Jacky-Summer** [comment]
Can anyone help me? I am also facing this unresolved issue.Why closed it? @antonmedv
