### ISSUE TITLE
Setting env variable is not working for me using `within`

### ISSUE THREAD

**Issue by GuillaumedesPommareSAP** [google/zx#656]
Hello,

I am implementing some nice scripts using zx but one feature is not working at all in my case, setting an environment variable (a java classpath, in my case, which can be huge) and using it in further calls.
Note: doing some else like cd("..") is working ! 

## Expected Behavior
```
$ echo $FOO
bar
```
## Actual Behavior
```
$ echo $FOO

```
## Steps to Reproduce the Problem
I am running: 
```
await within(async () => {
  $.env.FOO = 'bar';
  await $`echo $FOO`;
});
```
or 
```
await within(async () => {
  process.env.FOO = 'bar';
  await $`echo $FOO`;
});
```
or even
```
await within(async () => {
  await $`export FOO=bar`;
  await $`echo $FOO`;
});
```
## Specifications

- Version: "zx": "7.2.3"
- Platform: Windows 11 + WSL

I only can find information that it should be working, and I do not know how to debug further to understand what is happening.

**Comment by yiluoegit** [comment]
I had the same problem.
<img width="1492" alt="截屏2023-08-24 11 29 24" src="https://github.com/google/zx/assets/76962284/00620a7e-1be4-4309-8acd-cd9b7028c92f">

**Comment by koshic** [comment]
It works according to [specs](https://nodejs.org/api/async_context.html#class-asynclocalstorage), you just need to replace the whole $.env object like that:
```js
$.env = { ...process.env, FOO: "BAR" };
```
