### ISSUE TITLE
`$.prefix` not work as expected

### ISSUE THREAD

**Issue by nzhl** [google/zx#66]
```
#!/usr/bin/env zx

$.shell = '/usr/local/bin/zsh'
$.prefix = 'echo 122;source ~/.zshrc;'

await $`z test;  pwd` # use on-my-zsh z plugin
```

## got 
> zsh:1: command not found: z

## expect
1. echo 123 first 
2. pwd print somedir of which name contains test

**Comment by nzhl** [comment]
Supplement

if i use source in the same line as the cmd exec
```
#!/usr/bin/env zx

$.shell = '/usr/local/bin/zsh'

await $`source ~/.zshrc;which _z; _z test & pwd`

await $`source ~/.zshrc;which z; z test & pwd`
```

got
```
$ source ~/.zshrc;which _z; _z test; pwd
_z () {
    #  definition of _zh
}  # _z is just a function
/nzhl/test   # work as expected

$ source ~/.zshrc;which z; z test;pwd
z: aliased to _z 2>&1        # z is just alias of _zsh
zsh:1: command not found: z  # question: why does  z command  just disappear ？
```

**Comment by nzhl** [comment]
Just got a saying that 'alias only expand in a interactive shell, not working in scripts'

but  when i wrote a shell script and try exec it
```
#!/usr/local/bin/zsh
source ~/.zshrc
z test;
pwd;
```

what i got 
```
 ./test.sh
/Users/nzhl/test
```

**Comment by antonmedv** [comment]
So what is the zx problem?

**Comment by nzhl** [comment]
> So what is the zx problem?

1. try using echo in prefix, namly  $.prefix = echo 123,  it won't exec right before every command as expected
2. zsh alias not working in zx but did work in pure bash script

**Comment by nzhl** [comment]
sorry bro, just figured out that i have used a very old version 1.0.2.   All those problems blew away when switched to 1.6.0
