### ISSUE TITLE
$ output missing if inside spinner()

### ISSUE THREAD

**Issue by pinko-fowle** [google/zx#665]
## Expected Behavior

Running a `$` command inside a `spinner` should at some point print what the command is. For example, the following would (I'd hope) print `$ long-running foo` at some point.

```
spinner("doing thing", () => $`long-running foo`)
```

(`$` showing the command ran is one of the main reasons I use zx: it makes it clear to people using my scripts what is really happening under the hood. But this capability goes away for anything that is also long running. 😦)

## Actual Behavior

Spinner runs, showing "doing thing". Then the spinner and "doing things" is erased. The command ran is never shown. No evidence of either the spinner or the command ran remains.

# Workaround

```
const thing = $`long-running foo`
spinner("doing thing", thing)
```

## Steps to Reproduce the Problem

Above example should show.

## Specifications

- Version: 7.2.3
- Platform: Debian linux, node 20.5.1

**Comment by antonmedv** [comment]
Well. This is how it designed.  Spinner hides the output.
