### ISSUE TITLE
tons of .mjs files leftover in my bin directory

### ISSUE THREAD

**Issue by deanveloper** [google/zx#673]
I like using zx to write userscripts, but sometimes when executing a zx script, it'll leave a `.mjs` file in my `~/bin` directory (where I keep my userscripts)

## Steps to Reproduce the Problem

1. Put a zx script, no file extension and with a `#!/usr/bin/env zx` shebang, in your PATH
1. Run your zx script
1. Run it again (keep running it, as the issue seems to be intermittent)

## Expected Behavior

No new files should be created

## Actual Behavior

zx sometimes leaves behind a `scriptname.mjs` or `scriptname-randomchars.mjs` file in my bin directory

## Specifications

- Version: 7.2.2
- Platform: macOS 13.5

**Comment by deanveloper** [comment]
I just tried updating to 7.2.3 as well, not sure if the issue still exists but I'll update the issue if it seems to be fixed

**Comment by antonmedv** [comment]
Just add `.mjs` extension to your userscripts.
