### ISSUE TITLE
When executing other processes via await $`command -abc` coloring and formatting can be lost from the output

### ISSUE THREAD

**Issue by joelclimbsthings** [google/zx#684]
## Expected Behavior
When executing other commands, the coloring and formatting from the original process is displayed correctly.

## Actual Behavior
Any coloring and some formatting is lost, in the output. 

## Steps to Reproduce the Problem

1. Run `zx --eval 'await $`ls`'` on your command line.
2. Run `ls` on your command line.
3. Observe that the output is stripped of color and formatting.

## Specifications

- Version: 7.2.1
- Platform: Linux

**Comment by antonmedv** [comment]
https://google.github.io/zx/known-issues#colors-in-subprocess
