### ISSUE TITLE
Feature request: hiding user input

### ISSUE THREAD

**Issue by RMEngels** [google/zx#697]
Hi!

## The problem
When prompting a user for a sensitive piece of data you would not want that piece of data showing up in the terminal. In bash, you would do `read -s PASSWORD`.

Currently, the `question()` function does not support such a thing.

## Proposed Solution
Give the option to hide the user input in the second argument (option object) of the question function.

```ts
await question($`Enter password:`, {
    hideInput: true,
}),
```

Any thoughts on this idea? I can propose a PR if this is functionality you'd like.

**Comment by phukon** [comment]
I think this PR #526  addresses this.

**Comment by RMEngels** [comment]
Thank you!

**Comment by RMEngels** [comment]
Hmm could be me but this does not look completed?

**Comment by antonmedv** [comment]
Looks like not_)

**Comment by palfaro91** [comment]
Looks like that PR was closed without merging it in. Will this feature ever be implemented?
