### ISSUE TITLE
Use undici-fetch rather then node-fetch

### ISSUE THREAD

**Issue by Milo123459** [google/zx#7]
*when it goes stable*

It is more performant then node-fetch

**Comment by OmgImAlexis** [comment]
@Milo123459 unless you're going to give a really good reason for this I can't see this being accepted when the undici-fetch project even states it's only a beta.

> This module is currently in beta. It is not spec compliant yet. v1 will be released when this can be a drop-in replacement for other Node.js fetch implementations.

**Comment by Milo123459** [comment]
Should've said I meant when it went stable. It's more performant. My bad.

**Comment by antonmedv** [comment]
Nope 👎
