### ISSUE TITLE
ssh() is undocumented

### ISSUE THREAD

**Issue by stevage** [google/zx#706]
It looks like `ssh()` was added in #247, and documented [here](https://github.com/google/zx/compare/7.1.1..7.2.0). But somewhere along the line, that documentation didn't make it to [here](https://google.github.io/zx/getting-started).

**Comment by antongolub** [comment]
https://github.com/google/zx/pull/750

**Comment by stevage** [comment]
Wait, what? Please don't remove SSH, I use it in many of my scripts.
