### ISSUE TITLE
Shell variable in args array not expanded

### ISSUE THREAD

**Issue by p3k** [google/zx#708]
## Expected Behavior

The following snippet should output `123 abc abc`:

```js
const { $ } = await import("zx");
const args = ["123", "$foo"];
await $`foo=abc; echo ${args} $foo`
```

## Actual Behavior

The snippet outputs `123 $foo abc`, not expanding the shell variable `$foo`.

## Specifications

- Version: 7.2.3
- Platform: Node.js v18.19.0

**Comment by antonmedv** [comment]
This is due to zx quoting mechanism.  

```js
const args = ["123", "$foo"];
await $`foo=abc; echo ${args} $foo`
```

Transformed into:

```bash
foo=abc; echo '123' '$foo' $foo
```

So first `'$foo'` evaluated by bash as string, and a second `$foo` as variable.

Here you can read more about escaping and quotas in zx: 
 - https://ï.at/zx-quotes

**Comment by p3k** [comment]
Thanks for the pointer, I have seen that – it does not mention what happens if a shell variable is used in an array of arguments. Maybe add this to the example?

Because of zx’s quoting mechanism it is necessary to write a command using an array of arguments *and* a shell variable in an argument like this:

```shell
const args = ["foo, "bar"];
await $`echo args $foobar`
```

– which is not that obvious.
