### ISSUE TITLE
Feature request: Process Promise verbose()

### ISSUE THREAD

**Issue by lquixada** [google/zx#710]
When we set `$.verbose = true`, we can make specific $ calls to go silent with `.quiet()`.
On the flip side, when we set `$.verbose = false`, there isn't a way to make a $ call go verbose.

It would be cool to have a `.verbose()` method for Process Promises.

**Comment by antongolub** [comment]
Seems resolved via https://github.com/google/zx/pull/733

```ts
$.verbose = false
const p = await $({verbose: true})`echo foo`
```

**Comment by wpchen** [comment]
+1 to `.verbose()`

@antongolub's suggestion is functionally equivalent but is significantly less ergonomic (ex: if I'm temporarily adding `.verbose()` during debugging, it's a lot easier to append/comment out `.verbose()` than it is to insert/delete `({verbose: true})`

**Comment by antongolub** [comment]
Ok, just for symmetry with `ProcessPromise.quiet()` :)
