### ISSUE TITLE
Reduce package installation size

### ISSUE THREAD

**Issue by GaelGirodon** [google/zx#712]
The current installation size of the package may discourage its integration into other projects or packages that want to keep their size as low as possible (as mentioned in #687).

The installation size has increased significantly over releases, especially on 2.x, 5.x and 7.x:

| `1.15.2` | `2.1.0` | `3.1.0` | `4.3.0` | `5.3.0` | `6.2.5` | `7.2.3` |
| -------- | ------- | ------- | ------- | ------- | ------- | ------- |
| 1.38 MB  | 3.01 MB | 3.01 MB | 3.89 MB | 10.5 MB | 10.7 MB | 16.3 MB |

→ <https://packagephobia.com/result?p=zx%401.15.2%2Czx%402.1.0%2Czx%403.1.0%2Czx%404.3.0%2Czx%405.3.0%2Czx%406.2.5%2Czx%407.2.3>

98% of the installation size comes from 5 dependencies:

| Dependency        | Install | %    |
| ----------------- | ------: | ---: |
| `node-fetch`      | 7.45 MB | 47 % |
| `@types/node`     | 3.50 MB | 22 % |
| `@types/fs-extra` | 3.45 MB | 22 % |
| `yaml`            | 636 kB  | 4 %  |
| `globby`          | 577 kB  | 4 %  |
| `ps-tree`         | 131 kB  | 1 %  |
| `fs-extra`        | 114 kB  | 1 %  |
| `minimist`        | 53.2 kB | 0 %  |
| `chalk`           | 42.5 kB | 0 %  |
| `fx`              | 19.5 kB | 0 %  |
| `which`           | 17.7 kB | 0 %  |
| `@types/minimist` | 7.17 kB | 0 %  |
| `@types/which`    | 5.26 kB | 0 %  |
| `@types/ps-tree`  | 4.45 kB | 0 %  |
| `webpod`          | 357 B   | 0 %  |

→ <https://packagephobia.com/result?p=@types/fs-extra@11.0.1,@types/minimist@1.2.2,@types/node@18.16.3,@types/ps-tree@1.1.2,@types/which@3.0.0,chalk@5.2.0,fs-extra@11.1.1,fx,globby@13.1.4,minimist@1.2.8,node-fetch@3.3.1,ps-tree@1.2.0,webpod@0.0.0,which@3.0.0,yaml@2.2.2>

The package size could be drastically reduced (-90%) by:

1. [ ] Removing `node-fetch` (#687, #589): **-47%**
2. [ ] Moving `@types/*` to _dev_ (and _optional_?) dependencies: **-44%**
   - These types can still be installed if needed by TypeScript users
3. [ ] Removing `fs-extra` and `@types/fs-extra` (#589): **-22%**

Tasks 1 and 3 are already planned for v8, could you consider the 2nd one as well? Thanks 🙂

**Comment by antonmedv** [comment]
> Moving @types/* to dev (and optional?) dependencies: -44%
> These types can still be installed if needed by TypeScript users

Yeap. We are going to build zx with esbuild and we can build .d.ts as well.

**Comment by antonmedv** [comment]
🎉 Awesome work @antongolub
