### ISSUE TITLE
Template literals function turn numeric 0 into ''

### ISSUE THREAD

**Issue by NHibiki** [google/zx#72]
Hi, all. I found this project very inspiring and tried it out right when I saw it. However, I met some issues when I was trying to create a script to arrange files into folders, like this:

```js
const prefix = './test/'
const parts = 5
for (let i = 0; i < parts; ++i) {
  $`mkdir -p ${prefix}${i}`
}

console.log(chalk.red("Done!"))
```

## Expected Behavior
```bash
$ mkdir -p ./test/0
$ mkdir -p ./test/1
$ mkdir -p ./test/2
$ mkdir -p ./test/3
$ mkdir -p ./test/4
Done!
```

## Actual Behavior
```bash
$ mkdir -p ./test/''
$ mkdir -p ./test/1
$ mkdir -p ./test/2
$ mkdir -p ./test/3
$ mkdir -p ./test/4
Done!
```

## Steps to Reproduce the Problem

1. just create a script using the code above.
2. run it.

## Further Description

When I look into the code, the `$` defined in [index.mjs](https://github.com/google/zx/blob/main/index.mjs#L41) calls `$.quote` which is an alias of `shq` that turns numeric `0` to `''`. I know it is how `shq` handles the *non-string* variable, but I do not think it behaves commonly (or maybe logically) here. If we need to make sure the variables passed into the template literals to be all strings, maybe we need to throw the bad cases. Otherwise, to turn `0` into `''` might not be a good idea?

Thanks.

## Specifications

- Version: 1.5.0
- Platform: Node v16.1.0 on Ubuntu 20.04

**Comment by antonmedv** [comment]
Yes, I think we need to call toString() before.

**Comment by NHibiki** [comment]
@antonmedv cheers 🍺 and I think maybe it depends.

it seems that due to the feature 🤔 of javascript, all `Boolean(arg) === false` will be replaced with `''`.
This sounds great when it comes to values like `null`, `undefined`, `NaN`, .etc. But in terms of `0`, `toString()` is better 👍

**Comment by antonmedv** [comment]
Fixed.
