### ISSUE TITLE
An easy way to specify stdin

### ISSUE THREAD

**Issue by neongreen** [google/zx#720]
Right now, there are (at least?) two ways to specify stdin:

1. **Via pipes:**

   `` $`echo ${input} | command` ``

   This works, but at least on GitHub runners it can suffer from random SIGPIPE (exit code 141) failures that are not reproducible locally. No idea why.

2. **Via `.stdin`:**

   ```ts
   const p = $`command`
   p.stdin.write(input)
   p.stdin.end()
   ```

   This requires giving a name to the command itself, and is a bit cumbersome to use.

I propose pushing the latter pattern into a function or a method, eg. something like

```ts
$`command`.input(input)
```

or perhaps 

```ts
function withInput(cmd: zx.ProcessPromise, input: string): zx.ProcessPromise {
  cmd.stdin.write(input)
  cmd.stdin.end()
  return cmd
}
```

**Comment by antonmedv** [comment]
Nice idea

**Comment by XDuskAshes** [comment]
Not quite familiar with zx or js, but I have played a bit with both as well as other languages. I think this is a good idea, and could cut down on cumbersome-ness.

**Comment by antongolub** [comment]
> $`command`.input(input)

[We're planning](https://github.com/google/zx/issues/589) to introduce smth like <code>$(opts)\`cmd args\`</code> in the netx major release, and the `input` option is definitely adopted.

```ts
const input = '{"name": "foo"}'
const name = await $({input})`jq -r .name` // foo

const stdin = fs.createReadStream(path.join(fixtures, 'foo.json'))
const data = await $({stdin})`jq -r .data` // foo
```
