### ISSUE TITLE
Replacing globby with a lighter alternative

### ISSUE THREAD

**Issue by 43081j** [google/zx#721]
As part of an ongoing ecosystem cleanup project, zx came up in some of our de-bloating efforts

you depend on `globby` which has a rather bloated dependency tree for what it is.

what do you think of replacing this with a lighter alternative?

you do export `globby` in your public interface, but maybe if we kept the same symbol name and replaced the internals, it wouldn't need to be a breaking change?

happy to open a PR if this makes sense

**Comment by 43081j** [comment]
having looked into this more, im going to close this for now until i have a suggestion for an alternative

it may be that we can tackle the deep trees in fast-glob itself rather than making it zx's problem.

i think zx should just use fast-glob directly at least (this is also what prettier does for example). but i'll follow the trail into their repo meanwhile

**Comment by antonmedv** [comment]
We are going to bundle zx into a single js file. So bloat will go away.

**Comment by 43081j** [comment]
thats great news 🥳
