### ISSUE TITLE
Feature suggestion: Typescript support.

### ISSUE THREAD

**Issue by JustFly1984** [google/zx#75]
Write and execute scripts in typescript .ts files

**Comment by antonmedv** [comment]
I think this is out of the scope of the zx project. Closing.
You can y=use something like ts-node to add TypeScript support.

**Comment by Morriz** [comment]
So zx is strict ecmascript? And how would we transpile something to
```
await $`git branch --show-current`
```
?

What would be the input to that? I am curious. Would love to use typescript to use this...don't see the advantage of going back from typescript to es

**Comment by antonmedv** [comment]
What input? zx comes with typescript definitions. Just use whatever build method you prefer.

**Comment by smeijer** [comment]
It does come with typescript definitions, but those don't add types to the `global`.

**Comment by antonmedv** [comment]
Feel free to create a PR with it.
