### ISSUE TITLE
Typo in 8.0 release description

### ISSUE THREAD

**Issue by ShGKme** [google/zx#774]
In the [8.0 release description](https://github.com/google/zx/releases/tag/8.0.0) in breaking changes it's said:

---

1. `$.verbose` is set to false by default, but errors are still printed to stderr. Set `$.quiet = true` to suppress all output.

```js
$.verbose = true // everything works like in v7

$.quite = true // to completelly turn off logging
```

---

Example says `$.quite = true` when it should be `$.quiet = true`. 

It was **quite** annoying during migration 😀 

Also, `completelly` should be `completely`

**Comment by antonmedv** [comment]
Thanks!
