### ISSUE TITLE
Feature request: automatically add a newline after commands that don't end their output with one

### ISSUE THREAD

**Issue by stefansundin** [google/zx#776]
Hello. I'd love it if there was an option to ensure the output printed in the terminal from commands executed have a newline automatically added if the output didn't end with one.

Basically I have this:

```typescript
$.verbose = true;

const commitMessageSummary = (
  await $`git log -1 --pretty=format:%s`
).toString();
console.log({ commitMessageSummary });
```

## Expected Behavior

I would like the output to be this:

```
$ git log -1 --pretty=format:%s
Release 8.0.1
{ commitMessageSummary: 'Release 8.0.1' }
```

## Actual Behavior

This is the actual output:

```
$ git log -1 --pretty=format:%s
Release 8.0.1{ commitMessageSummary: 'Release 8.0.1' }
```

## Workaround

```typescript
$.verbose = true;

const commit_message_summary = (
  await $`git log -1 --pretty=format:%s`
).toString();
console.log(); // Fix newline not added from the previous command
console.log({ commit_message_summary });
```

Right now I have a ton of these scattered in my scripts:

```typescript
console.log(); // Fix newline not added from the previous command
```

I think this is something that `zx` could probably handle automatically.

## Specifications

- Version: 8.0.1
- Platform: macOS 14.4.1

**Comment by antonmedv** [comment]
As zsh does 👌🏻

**Comment by Anonymous961** [comment]
@stefansundin I think this issue has been fixed.

I used the same code 
```
import { $ } from "zx";
const commitMessageSummary = (
  await $`git log -1 --pretty=format:%s`
).toString();
console.log({ commitMessageSummary });
```
Output:
![image](https://github.com/google/zx/assets/96728156/af290e1b-524a-437d-ab94-0baf0f186929)


if this issue still exists. I would like to have more context.

**Comment by stefansundin** [comment]
@Anonymous961 You need to turn on verbose mode in v8 and later.

```
$.verbose = true;
```

Doing so causes zx to automatically print all the `$` shell commands, and their output. Kinda like setting `set -x` in bash. It used to be the default before v8.
