### ISSUE TITLE
Port listening doesn't stop when using `CTRL+C`

### ISSUE THREAD

**Issue by ziimakc** [google/zx#781]
## Expected Behavior
Running and stopping server with `CTRL+C` should stop server from listening on port.

## Actual Behavior
Running and stopping server with `CTRL+C` doesn't stop server from listening on port.

## Steps to Reproduce the Problem

Running this command `node ./server.js` manually 2 times works fine, doing the same using `zx ./scripts/dev.js` fails second time with error about port which server is listening is already in use.

This started to happen after update to v8.

```
#!/usr/bin/env bash

import { $ } from "zx";

await $({ verbose: true})`node ./server.js`;
```

Does anything changed and I need somehow manually kill a process?

## Specifications

- Version: 8.0.1
- Platform: wsl ubuntu 22.04

**Comment by antongolub** [comment]
Ouch, we should make `detached` option configuralble.
https://nodejs.org/api/child_process.html#optionsdetached

**Comment by ziimakc** [comment]
@antongolub my platform is `linux`, will it work fine by default or do I need to specify detached=?

**Comment by antongolub** [comment]
Well, the only purpose for setting `detached=true` by default is to make <code>$\`sleep 999\`</code> abortable.
https://github.com/nodejs/node/issues/37518

@antonmedv, what do you think?

**Comment by antonmedv** [comment]
I did not get this. We want to make detached=true by default?

**Comment by antongolub** [comment]
v7 uses `false`
v8 uses `true` to _handle_ abort controller's corner case.

**Comment by antonmedv** [comment]
Yes, I don't think we should detach process.

> to handle abort controller's corner case.

What corner case?

**Comment by antongolub** [comment]
> corner case?
Technically, detached + abort() kills starter process (bash) only.

**Comment by lorisleiva** [comment]
Hi there,

I've got the same issue. What do I need to do in v8 to make `CTRL+C` kill the child process?

**Comment by antongolub** [comment]
@lorisleiva, @ziimakc 

Could you check the fix?
```bash
npm i zx@8.0.1-dev.b52bcd9
```

**Comment by lorisleiva** [comment]
Works like a charm on my side. Thank you! 🍺

**Comment by ziimakc** [comment]
@antonmedv same, works fine
