### ISSUE TITLE
Why zx instead of Python ?

### ISSUE THREAD

**Issue by adamency** [google/zx#786]
What exactly is `zx` providing in terms of functionality in scripts that Python doesn't already ?

Now that Python has async/await support natively, I seriously wonder how is zx a better alternative in any context. Could you provide some pointers or comparisons ? Thanks in advance

PS: Btw, the presentation paragraph of the project mentioning Javascript being used for complex scripting is absolutely absurd. Python is the most widely used tool, by far, when Bash isn't relevant anymore for a given script. Absolutely no one uses JS as an alternative to Bash script, where does the author has even heard such a thing ?

**Comment by antonmedv** [comment]
Oh boy, I see you've stumbled upon the wild world of zx, but just wait until I tell you about the mystical ancient scrolls of Perl! So, what exactly does zx offer that Python doesn’t? It’s like asking why would anyone use a quill when you have a perfectly good ballpoint pen, right? But then again, why stop there when we can chat about Perl!

Python might have async/await, but zx swoops in with its JavaScript-powered spellbook, where every npm package is a wand just waiting to cast. It’s like choosing between a Swiss Army knife and a wizard's staff. Sure, the knife is practical, but the staff lets you summon dragons... or JSON files, at least.

And now for Perl, ah, the grand sorcerer of scripting! Why would anyone in their right mind pick Python over Perl? It’s the same reason we climb Everest—it’s there, and it has regular expressions that can summon Cthulhu if you're not careful. Python, with its clear syntax and readability? Pfft, where’s the adventure in that? Perl is like scripting in hieroglyphs; nobody knows what you're doing, maybe not even you, but it’s sure to be powerful!

P.S. About that remark on JavaScript replacing Bash—absolutely hilarious, right? It’s like saying people use Latin in everyday conversation. Next, they'll be telling us about folks replacing their morning coffee with a brisk jog. Utter madness!

**Comment by capttrousers** [comment]
Python virtual environment management is a shit show, so for that reason alone I wouldnt use python for glue code / simple / complex scripting needs. Both python and javascript have a lot of problems, there is no great programming language, but at the end of the day we're just trying to get stuff done, and javascript stays out of the way more than python in my experience. If your experience is different, cool, enjoy your python spaghetti while I enjoy my typescript spaghetti.
