### ISSUE TITLE
Add hint for required Node version regarding top-level await usage

### ISSUE THREAD

**Issue by tobilg** [google/zx#8]
## Expected Behavior
There should be a hint in the README regarding the required Node version for the usage of top-level await.

## Actual Behavior
Currently, this is not in the README.

**Comment by antonmedv** [comment]
Maybe it’s better to add check in package.json?

**Comment by tobilg** [comment]
I thought about that as well, but wasn't sure if that would really help as you can use an IIF as workaround for older versions, and the engine property in the package.json is only advisorial unless engine-strict is used (see https://docs.npmjs.com/cli/v7/configuring-npm/package-json#engines). 

So I chose to only add some info to the README. What do you think?

**Comment by antonmedv** [comment]
Done.

**Comment by tobilg** [comment]
@antonmedv I currently don't see a hint in the README.md, and in the package.json there's only a reference to the "wrong" Node version with top-level await support (see https://github.com/google/zx/blob/main/package.json#L11)

**Comment by tobilg** [comment]
It's v14.8.0 according to https://dev.to/mikeesto/top-level-await-in-node-2jad

Please also see my PR https://github.com/google/zx/pull/9/files#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5R35
