### ISSUE TITLE
How to use commands stored in variables?

### ISSUE THREAD

**Issue by Eggwise** [google/zx#81]
Hi, 
Tried this package, looks really nice but i can't seem to understand how i run commands stored in a variable.
Maybe i'm just a noob or is it not supported.?

Example:

`
let url = 'https://example.com'
let testCommand = 'wget ' + url; // a string containing the command.

Now.. how do i use $"runsomecommand"

`

Any help would be very much appreciated, looking forward to use zx in my projects but i need this basic functionallity.

Cheers

**Comment by antonmedv** [comment]
Why do you need to store command name in variable?

**Comment by antonmedv** [comment]
Like this:
```
await Promise.all([
  Promise.all([$`${cmd} ${url}`])
])
```

**Comment by Eggwise** [comment]
@antonmedv Awesome man. Thanks alot!
