### ISSUE TITLE
Is Node.js 12.17.0 supported for zx as a package ?

### ISSUE THREAD

**Issue by Cactusbone** [google/zx#824]
Hello ! 
I've seen the releases notes of 8.1.0 which says 

> Extended Node.js supported versions range: from [12.17.0 to the latest 22.x.x](https://github.com/google/zx/blob/main/.github/workflows/test.yml#L101).

However with Node.js 12.22.12 (the one shipped with alpine 3.20, upon which docker-cli images are built), I'm getting `SyntaxError: Unexpected reserved word` with `import {$, cd} from 'zx';`

What I'm trying to achieve: I'm trying to run mocha tests (using mocha binaries), which starts and stops Docker containers, so I'm using zx as a package. And since I also need docker client, I'm using the docker-cli image, with alpine 3.20, which provides Node.js 12.22.12.

It is expected to work ? Anything I can to do work around it ?

Thanks

### Expected Behavior
```js
import {$, cd} from 'zx'
```
No error

### Actual Behavior
```js
import {$, cd} from 'zx'
```
 `SyntaxError: Unexpected reserved word`
### Steps to Reproduce

1. Use Node.js 12.22.12 (I think all Node.js 12 > 12.17.0 exhibit the issue)
2. simply import zx in a module

### Specifications

- zx version:  8.1.1
- Platform: windows and docker (separately)
- Runtime: Node.js 12.22.12

**Comment by Cactusbone** [comment]
Ok, I've found a workaround for Node.js 12, by using `require`

```js
import {createRequire} from 'node:module';
const require = createRequire(import.meta.url);
const {$, cd} = require('zx');
```

I think the top level await in built index.js is not compatible with Node.js 12, should work starting with Node.js 14.8.

**Comment by antongolub** [comment]
Nice catch, thanks!

**Comment by Cactusbone** [comment]
Fix does not seem to work. According to documentation, `main` entrypoint is for Node.js <= 10

Node.js 12 does support the exports entrypoint, see https://nodejs.org/docs/latest-v12.x/api/packages.html#packages_package_entry_points

**Comment by antongolub** [comment]
@Cactusbone ,

Check another patch plz: [8.1.2-dev.b3fcad2](https://www.npmjs.com/package/zx/v/8.1.2-dev.b3fcad2)

**Comment by Cactusbone** [comment]
> @Cactusbone ,
> 
> Check another patch plz: [8.1.2-dev.b3fcad2](https://www.npmjs.com/package/zx/v/8.1.2-dev.b3fcad2)

It works ! :)

**Comment by Cactusbone** [comment]
Thanks a lot for the quick fixes :)
