### ISSUE TITLE
Variable List of Command Line Args

### ISSUE THREAD

**Issue by Syncytium** [google/zx#83]
## Context

I'm making a small tar shortcut script so that I don't have to remember the right flags when I use it.  One script is tools-tar and another is tools-untar.  I need to pass in a variable number of file and folder names to put in the archive and can't make it work with the $`` syntax.

Usage of the tool: zx  tools-tar.mjs output.tar.gz testfile1 testfile2 testdir1

## Expected Behavior

An output.tar.gz archive containing the files.

## Actual Behavior
```
$ tar czvf output.tar.gz 'testfile1 testfile2 testdir1'
tar: testfile1 testfile2 testdir1: Cannot stat: No such file or directory
```

## Script to Reproduce

```
const args = process.argv.slice(3);
const outputPath = args[0];
const inputs = args.slice(1);

await $`tar czvf ${outputPath} ${inputs.join(" ")}`
```

Actual script is longer with some validation, etc. but that should repro the above output.

The variables in the inputs list are all getting put into 1 string and then I think zx is escaping it (notice the single quotes in the error message around the files/dirs).  Any guidance on a different approach is welcome as well.

**Comment by antonmedv** [comment]
I think we need add support arrays as parameters.

**Comment by antonmedv** [comment]
#47
