### ISSUE TITLE
fetch's document link is wrong

### ISSUE THREAD

**Issue by ClanceyLu** [google/zx#841]
8.0 uses `node-fetch-native`,but the document write it uses `node-fetch`.
They do not implement proxy functions in the same way.
When I upgraded to 8.0, it can't work.

**Comment by antonmedv** [comment]
@antongolub

**Comment by antongolub** [comment]
Hmm, https://github.com/unjs/node-fetch-native/issues/125 maybe?
Anyway, we need a reproducible example to start digging.

**Comment by ClanceyLu** [comment]
> Hmm, [unjs/node-fetch-native#125](https://github.com/unjs/node-fetch-native/issues/125) maybe? Anyway, we need a reproducible example to start digging.


I have already resolved this issue, just wanted to point out that there is an error in the documentation here.
https://google.github.io/zx/api#fetch

**Comment by antongolub** [comment]
Oh. Just a typo in docs))) I'll fix. the link.
