### ISSUE TITLE
bun compatibility: get rid of async_hooks.createHook call

### ISSUE THREAD

**Issue by enzalito** [google/zx#847]
### Expected Behavior
```shell
bunx drizzle-kit studio
```
=> works

### Actual Behavior
As described in https://github.com/drizzle-team/drizzle-orm/issues/2239, the command above doesn't work. A warning is produced when it is run: `[bun] Warning: async_hooks.createHook is not implemented in Bun. Hooks can still be created but will never be called.`. I managed to pin down the issue, it was introduced by this commit: https://github.com/google/zx/commit/1a9ced6bb38a97f2eb6840f9a13c03f2fbc8c063. And comes from from this line: https://github.com/google/zx/blob/cd8b511daee8f1d1df1575f269d18b0dae42ad11/src/core.ts#L87  
zx uses the experimental API [async_hooks.createHook](https://nodejs.org/api/async_hooks.html#async-hooks) that is not supported by bun and not recommended by node (see the warning on the page I linked).  
Drizzle doesn't even use `syncProcessCwd` but its presence in the distributed `bin.cjs` file is enough to make the script crash (it works when I remove it).

### Steps to Reproduce

1. run any project that imports zx with bun

### Specifications

- zx version:  >7.0.0
- Platform: windows / macos / linux
- Runtime: bun

### Possible fix

Just use the [AsyncLocalStorage](https://nodejs.org/api/async_context.html#class-asynclocalstorage) API as recommended on node's website instead.  
I'm not familiar with zx or this particular node API so there might be something that prevents the switch from being done idk. If not, I'd be happy to submit a PR as this issue seem to bug quite a few people including myself :)

**Edit**: I spoke too soon, installing node seems to fix the problems with drizzle, removing `syncProcessCwd` just gets rid of the warning. I still think that this issue makes sense thought so I'll keep it open.

**Comment by enzalito** [comment]
Hey @antongolub,

I'm using bun 1.1.13, the latest version.  
That would suppress the warning if `syncProcessCwd` is not used but the function would still be unusable, not that it matters to me.

**Comment by antongolub** [comment]
Bun is aimed to be a fully compatible drop-in replacement for Node.js. So I believe this feature will be available someday.
