### ISSUE TITLE
cannot concatenate strings with ${}

### ISSUE THREAD

**Issue by freeliujian** [google/zx#850]
use zx create simple eg : 
![image](https://github.com/google/zx/assets/31119150/9d294a50-4419-46e6-a067-8d5a252c5f35)
```js
#!/usr/bin/env zx

(async () => {
  const url = 'https://github.com/freeliujian/learnEnglish.git'
  await $`git clone ${url}`;
})()

```
run `zx example/index.js` or `node example/index.js` or  `zx example/index.mjs` or `node example/index.mjs` 

### Expected Behavior
it should be Cloning into 'learnEnglish'...
```js


```

### Actual Behavior
```js

C:\Users\wei\AppData\Roaming\nvm\v20.12.2\node_modules\zx\build\util.cjs:71
  throw new Error("No quote function is defined: https://\xEF.at/no-quote-func");
        ^

Error: No quote function is defined: https://ï.at/no-quote-func
    at noquote (C:\Users\wei\AppData\Roaming\nvm\v20.12.2\node_modules\zx\build\util.cjs:71:9)
    at buildCmd (C:\Users\wei\AppData\Roaming\nvm\v20.12.2\node_modules\zx\build\vendor.cjs:20141:91)
    at Proxy.set (C:\Users\wei\AppData\Roaming\nvm\v20.12.2\node_modules\zx\build\core.cjs:113:44)
    at file:///D:/other/scaffold/example/index.mjs:7:10
    at file:///D:/other/scaffold/example/index.mjs:8:3
    at ModuleJob.run (node:internal/modules/esm/module_job:222:25)
    at async ModuleLoader.import (node:internal/modules/esm/loader:323:24)

Node.js v20.12.2

```

### Steps to Reproduce

1.
2.
3.

### Specifications

- zx version: 8.1.2
- Platform: windows
- Runtime: node 20.12.2

**Comment by antongolub** [comment]
Hey, @freeliujian,

Windows users may need to perform some additional setup steps. Follow the manual: https://google.github.io/zx/setup#bash

**Comment by antonmedv** [comment]
@antongolub what about adding a warning message here?

https://github.com/google/zx/blob/3931b9dd5bab124224adfc7314c8fc915671605e/src/core.ts#L214-L216

And maybe posting a link to a documentation on how to set this up properly? We can do a small delay to wait for user calls to one of usePwsh/usePowerShell/useBash helpers. 

What do you think?

**Comment by antonmedv** [comment]
Or maybe even better:
https://github.com/google/zx/blob/3931b9dd5bab124224adfc7314c8fc915671605e/src/util.ts#L88-L90

Make this error message more informative. no quote function can only be in bash not found. Lets add a check if $.shell is in place and if note add a detailed error message with a link to How-To.

**Comment by antongolub** [comment]
But how was this state obtained?
https://github.com/google/zx/blob/main/src/core.ts#L159

`$.shell` check goes before `$.quote` call.
