### ISSUE TITLE
Strings are wrapped in quotes

### ISSUE THREAD

**Issue by redcarti** [google/zx#86]
I was doing my script for semantic commits and when I provided commit message, it was wrapped in quotes.

## Expected Behavior
Executes `git commit -m "chore: initial release"` without quotes on commit message

## Actual Behavior
Executes `git commit -m "'chore: initial release'"`

## Steps to Reproduce the Problem

1. Run script below

```mjs
const commitMessage = 'chore: initial release'
await $`git commit -m "${commitMessage}"`
```

2. See the output

```console
$ git add .
$ git commit -m "'chore: initial release'"
```

## Specifications

- Version: 1.6.0
- Platform: Windows 10

**Comment by yashshah1** [comment]
The extra quotes are because you're wrapping them in double quotes in the second line. Removing them should solve your problem: 

```js
const commitMessage = 'chore: initial release'
await $`git commit -m ${commitMessage}`
```

**Comment by redcarti** [comment]
@yashshah1 The output without double quotes:

```console
$ git add .
$ git commit -m 'chore: initial release'
error: pathspec 'initial' did not match any file(s) known to git
error: pathspec 'release'' did not match any file(s) known to git
```

**Comment by redcarti** [comment]
I found where the problem comes from.

zx makes cmd:
```js
let cmd = pieces[0], i = 0
while (i < args.length) cmd += $.quote(substitute(args[i])) + pieces[++i]
```

`$.quote` method is `shq` library.
shq function:
```js
function q(o, x) {
  if (!x) { return (o.empty || "''"); }
  const s = String(x).replace(n, '');
  const m = b.exec(s);
  if (m && (m[0].length === s.length)) {
    const g = (o.gratuitous || '');
    return g + s + g;
  }
  return ("'" + s.replace(p, d) + "'"
  ).replace(/^''/, '').replace(/''$/, '');
}

function shq(x) { return q(false, x); }
```

I replaced `"'" + s.replace(p, d) + "'"` with `s.replace(p, d)` and there wasn't any extra quotes.

**Comment by antonmedv** [comment]
This is not a problem. You using it wrong way.

**Comment by redcarti** [comment]
What way I need to use it?

**Comment by antonmedv** [comment]
Another way. 😅

**Comment by redcarti** [comment]
I just replaced `$.quote` to `shq` package without extra quoting :)
