### ISSUE TITLE
Understanding `zx` roadmap and idea 🙏

### ISSUE THREAD

**Issue by Avivbens** [google/zx#860]
### A Quick Question
Just want to make sure I'm getting you right - the `$` executor would be extracted from [this library](https://github.com/webpod/zurk), so developers would be able to use its powers for production code too, besides scripts (?)

I'm asking because I'm looking for something addressing a lot of the issues it would solve, [see this thread](https://github.com/nearform/sql/issues/204#issuecomment-2165805160)

**Comment by antongolub** [comment]
zurk just builds a flexible abstraction on top of the process spawner.
zx has a broader scope. It is a toolchain that comprehensively improves devx in the tasks of writing scripts for various purposes.

**Comment by Avivbens** [comment]
> zurk just builds a flexible abstraction on top of the process spawner. zx has a broader scope. It is a toolchain that comprehensively improves devx in the tasks of writing scripts for various purposes.

Thanks for the explanation 🙏

So, `zurk` should handle command injection issues?

**Comment by antongolub** [comment]
> So, zurk should handle command injection issues?

Partially. zurk provides basic [script syntax](https://github.com/webpod/zurk/blob/main/src/main/ts/x.ts#L90) and [cmd build logic](https://github.com/webpod/zurk/blob/main/src/main/ts/util.ts#L54). Meanwhile zx has built-in [setups](https://github.com/google/zx/blob/main/src/core.ts#L129) and rich [bundle of utilities](https://github.com/google/zx/blob/main/src/util.ts) for seamless adaptation to different environments, corner cases, etc. These are different levels of instrumentation.

**Comment by Avivbens** [comment]
> > So, zurk should handle command injection issues?
> 
> 
> 
> Partially. zurk provides basic [script syntax](https://github.com/webpod/zurk/blob/main/src/main/ts/x.ts#L90) and [cmd build logic](https://github.com/webpod/zurk/blob/main/src/main/ts/util.ts#L54). Meanwhile zx has built-in [setups](https://github.com/google/zx/blob/main/src/core.ts#L129) and rich [bundle of utilities](https://github.com/google/zx/blob/main/src/util.ts) for seamless adaptation to different environments, corner cases, etc. These are different levels of instrumentation.
> 
> 
> 
> 

But using zurk alone would provide me a safe command execution, without worrying about arbitrary command injection?

**Comment by antongolub** [comment]
It depends. Both zurk and zx use internal `qoute` function to format a cmd for **bash**. Another shells may (theoretically) handle input differently.

https://google.github.io/zx/quotes
https://github.com/google/zx/blob/main/src/util.ts#L89

**Comment by Avivbens** [comment]
> It depends. Both zurk and zx use internal `qoute` function to format cmds for **bash**. Another shells may (theoretically) handle input differently.
> 
> 
> 
> https://google.github.io/zx/quotes
> 
> https://github.com/google/zx/blob/main/src/util.ts#L89
> 
> 
> 
> 

Awesome ✨🎉

Would definitely use both, for command execution & build robust scripts 🥷

I'll suggest featureswen I'll have something in mind 🙏
