### ISSUE TITLE
Provide better out of the box TypeScript support

### ISSUE THREAD

**Issue by lzm0** [google/zx#865]
Currently (as of `8.1.3`), running TypeScript files with zx requires additional setup, such as providing a `package.json` and a `tsconfig.json`.
It would be nice if the zx cli wraps `ts-node` automatically when it detects a `.ts` file.
I would love to create a PR for this feature if it is feasible.

**Comment by antongolub** [comment]
Spoiler: we have a similar feature in our plans :) But we'd like to make some preparatory architectural changes to support this vector (custom transpilations) and other feature extension points. It's great that you're willing to help, but we'd like to ask for a little bit of time on this.

**Comment by lzm0** [comment]
> Spoiler: we have a similar feature in our plans :) But we'd like to make some preparatory architectural changes to support this vector (custom transpilations) and other feature extension points. It's great that you're willing to help, but we'd like to ask for a little bit of time on this.

Glad to hear that. Thank you for this great tool!

**Comment by antonmedv** [comment]
@antongolub thanks!

**Comment by turadg** [comment]
Mind leaving this issue open until it's actually completed? It would make it easier for people to see that it's coming and not to file a new issue about it.
