### ISSUE TITLE
Could not resolve "zx/globals.cjs"

### ISSUE THREAD

**Issue by uladzimirdev** [google/zx#869]
I have a build step that transpiles code for nodejs into cjs format to use it in github actions.

as a build tool I use esbuild like

```
esbuild src/index.ts --bundle --outfile=dist/index.cjs --platform=node --target=node18
```

it works fine until the moment I need to export a fucntion from `index.ts` - I see the next error

```
Could not resolve "zx/globals.cjs"

      2 │ import "zx/globals.cjs";
        ╵        ~~~~~~~~~~~~~~~~

  The path "./globals.cjs" is not exported by package "zx":

    node_modules/zx/package.json:24:13:
      24 │   "exports": {
         ╵              ^

  You can mark the path "zx/globals.cjs" as external to exclude it from the
  bundle, which will remove this error.
```

may it be a problem with `exports` configuration?

in GitHub actions I use it inside the `github-actions/scripts` section

```
- uses: actions/github-script@v7
        with:
          script: | # js
            const { setMilestoneForCommits } = require('${{ github.workspace }}/release/dist/index.cjs');
```

where `release/dist` is a folder from esbuild step.

it may be a wrong configuration though

- zx version:  8.1.4
- Platform: macos
- Runtime: node

**Comment by uladzimirdev** [comment]
@antongolub afaik bundlers like esbuild, webpack etc are able to read exports part of package.json and load correct file based on the target of the builds (esm/cljs/etc), so it seems to be a valid error

**Comment by antongolub** [comment]
But how did `zx/globals` become `zx/globals.cjs`? Where was the ext attached?

**Comment by uladzimirdev** [comment]
@antongolub upgrade to 8.1.4 (and even 8.1.3) fixed the issue, sorry for bothering

8.1.2 produced that output 
<img width="928" alt="image" src="https://github.com/user-attachments/assets/18049294-2cd1-4eab-ae9b-0e4f0483031e">
