### ISSUE TITLE
Since 8.1.4 YAML.parseAllDocuments is not allowed from zx

### ISSUE THREAD

**Issue by szabopeterakos** [google/zx#870]
### Expected Behavior
```js

```

### Actual Behavior
```js
TypeError: YAML.parseAllDocuments is not a function
```

### Steps to Reproduce

1. update zx to 8.1.4 
2. try to use YAML.parseAllDocuments(x)

### Specifications

- zx version:  8.1.4
- Platform: macos
- Runtime: node

**Comment by szabopeterakos** [comment]
I assume before this YAML.parseAllDocuments was possible, after this release 8.1.4 its no longer there. It should be another way since now or is it an accident?

**Comment by antongolub** [comment]
I'm afraid, the mentioned extra API was previously accidentally added. zx is aimed to provide a basic `YAML` helpers symmetric with `JSON`. This will help us change the implementation in the future if needed, avoiding breaking changes.

**Comment by corporateuser** [comment]
> I'm afraid, the mentioned extra API was previously accidentally added. zx is aimed to provide just a basic `YAML` helpers symmetric with `JSON`. This will help us change the implementation in the future if needed, avoiding breaking changes.

Do not agree with your statement:
From zx documentation [yaml](https://google.github.io/zx/api#yaml) you're promising the whole YAML package and now with https://github.com/google/zx/commit/d7d074d5945b33d85c8e68085839d16b2c55b943 you've decided to remove APIs which you for some reason find redundant. 
This is breaking change, which should not be done in a minor update for sure.

**Comment by nishnp** [comment]
> > I'm afraid, the mentioned extra API was previously accidentally added. zx is aimed to provide just a basic `YAML` helpers symmetric with `JSON`. This will help us change the implementation in the future if needed, avoiding breaking changes.
> 
> Do not agree with your statement: From zx documentation [yaml](https://google.github.io/zx/api#yaml) zx promising the whole YAML package and now with [d7d074d](https://github.com/google/zx/commit/d7d074d5945b33d85c8e68085839d16b2c55b943) you've decided to remove APIs which you for some reason find redundant. This is breaking change, which should not be done in a minor update for sure.

I agree... even If it has to be removed, should not be done in a minor update.

**Comment by antongolub** [comment]
The problem is that we haven't covered this part of the API with tests. That's why it failed so badly. We will definitely invest time in this work.

**Comment by corporateuser** [comment]
I see your point, but initial description of zx goods does not describe that there is a limited set of yaml package, it describes that the whole yaml package available. So if it is really needed to remove additional methods it is like removing the whole package, which breaks backward compatibility. I do not see any point in breaking compatibility within the same major version and do not see any point in still having yaml package and dependencies and artificially removing its methods.

**Comment by corporateuser** [comment]
So, there is no plan to revert the mentioned change, correct?

**Comment by antonmedv** [comment]
Can we create a small stub for this methods? @antongolub not copy original defs, but createca simple method which returns any?

**Comment by antongolub** [comment]
I don't mind, but let's also mark it as deprecated.
