### ISSUE TITLE
Parsing hexadecimals string as number unintentionally

### ISSUE THREAD

**Issue by Cocodrilette** [google/zx#875]
### Expected Behavior
```js
const tx = argv.tx;
          // argv.tx ? String(argv.tx) : null;
          // String(argv.tx)
console.log(tx) // 0x85abc3a2d6796aa4f61e3f56052d1ad05323c599fef3841c3430f8a7ce08e9d3
```

### Actual Behavior
```js
const tx = argv.tx;
          // argv.tx ? String(argv.tx) : null;
          // String(argv.tx)
console.log(tx) // 6.046108994028729e+76
```

### Steps to Reproduce

I tried different parssing versions, but any of them works as expected

1. zx ./debug-tx.mjs

### Specifications

- zx version:  8.0.2
- Platform: linux
- Runtime: node

**Comment by dmelikhov** [comment]
You can call minimist manually and make it treat the argument as a string:
```js
#!/usr/bin/env zx

const argv = minimist(process.argv.slice(2), { string: ["tx"] });

const tx = argv.tx;
console.log(tx);
```

see https://www.npmjs.com/package/minimist#var-argv--parseargsargs-opts

**Comment by Zakronindustry** [comment]
Here’s a potential solution to ensure that argv.tx is treated as a string:

 **Ensure Input is a String**: Convert argv.tx to a string explicitly. This ensures that even if it is read as a number, it will be converted to a string.

  ```javascript
    const tx = String(argv.tx);
    console.log(tx);
```
 **Check Argument Parsing**: Make sure the command-line argument parsing library you’re using does not automatically convert the input. If you’re using a library like yargs or commander, check the documentation to see if there’s an option to treat arguments as strings.

**Verify Command Usage**: Double-check how you’re passing the argument. For example, if you’re using zx, ensure you’re passing the argument correctly and that it’s interpreted as a string.

Here’s a revised version of your code:

```javascript
const tx = String(argv.tx);
console.log(tx);
```
If argv.tx is indeed a very large number and you need to ensure it’s handled as a string in your code, explicitly converting it to a string should resolve the issue.
