### ISSUE TITLE
.lines() function outputs array with an empty string instead of the actual output

### ISSUE THREAD

**Issue by floriangeorgi** [google/zx#911]
### Expected Behavior
```js
#!/usr/bin/env zx
import {$} from 'zx'
console.log($.sync`echo -e "Item1\nItem2\nItem3"`.lines());
```
This code should output: `[ 'Item1', 'Item2', 'Item3' ]`
_This is at least the behavior in version **8.1.4**._

### Actual Behavior
It outputs an array with an empty string: `[ '' ]`

### Steps to Reproduce

1. Create a new node project, install `zx` and add `index.mjs`.
```js
// index.mjs

#!/usr/bin/env zx
import {$} from 'zx'
console.log($.sync`echo -e "Item1\nItem2\nItem3"`.lines());
```
2. Make it executable. `chmod +x index.mjs`
3. Run it with `zx index.mjs`

### Specifications

- zx version:  8.1.8
- Platform: ~~windows~~ / ~~macos~~ / linux
- Runtime: node / ~~deno~~ / ~~bun~~

**Comment by antongolub** [comment]
@floriangeorgi,

Thanks for the report. The fix is on the way.
