### ISSUE TITLE
Add dedicated API documentation?

### ISSUE THREAD

**Issue by FarazzShaikh** [google/zx#92]
How does auto-generated documentation with JSDoc sound? Something along the lines of [this](https://farazzshaikh.github.io/glNoise/). I can add it to the CI Pipeline along with #64 

I think it would be more convenient than scrolling through a long readme.

**Comment by antonmedv** [comment]
Didn't get it. What do you suggest for docs? 

I think it's kind of short.

**Comment by FarazzShaikh** [comment]
I was suggesting a site with separate sections for the functions that are currently in the [readme](https://github.com/google/zx#documentation) along with example usage, argument types, etc.

But you are right, the docs are short.
