### ISSUE TITLE
Support typescript natively

### ISSUE THREAD

**Issue by ziimakc** [google/zx#929]
Allow to run typescript files natively. 

The flag [--experimental-strip-types](https://nodejs.org/api/cli.html#--experimental-strip-types) enables Node.js to run TypeScript files. https://nodejs.org/api/typescript.html

Flag is available in current LTS node v22.

**Comment by antongolub** [comment]
Hey @ziimakc,

Hmm... This should work:
```ts
"test:smoke:strip-types": "node --experimental-strip-types test/smoke/ts.test.ts",
```

What's your use case?

**Comment by antongolub** [comment]
Anyway, it seems reasonable provide overriding the default ext (.mjs) in some cases.

**Comment by antonmedv** [comment]
It will be cool if zx have support for ts without any other:
```
npx zx script.ts
```
zx can spawn a node with `--experimental-strip-types` on it's own.

**Comment by antongolub** [comment]
npx accepts node flags via NODE_OPTIONS for its own internal node spawn

**Comment by ziimakc** [comment]
@antongolub I just want to run typescript files to ensure scripts are correct.

**Comment by antongolub** [comment]
In this case [tsc is required](https://github.com/microsoft/TypeScript/issues/1226) to check (not only strip) types.

**Comment by ziimakc** [comment]
@antongolub yes, tsc to check types and `--experimental-strip-types` to run the file

> "test:smoke:strip-types": "node --experimental-strip-types test/smoke/ts.test.ts"
Indeed, I was confused a bit because of zx explicit imports are required then.
