### ISSUE TITLE
bun: use inherit stdio cause error ERR_STREAM_CANNOT_PIPE

### ISSUE THREAD

**Issue by gutenye** [google/zx#940]
Reproduce

```ts
// a.js
import { $ } from 'zx'
$({ stdio: 'inherit' })`ls`
```

Run it with `bun a.js`

Output error

```
461 |         ;(_b = child.stdout) == null ? void 0 : _b.on("data", (d) => {
462 |           c.store.stdout.push(d);
463 |           c.store.stdall.push(d);
464 |           c.ee.emit("stdout", d, c);
465 |         }).pipe(c.stdout);
                 ^
error: Cannot pipe, not readable
 code: "ERR_STREAM_CANNOT_PIPE"
```

Error comes from [here](https://github.com/webpod/zurk/blob/af9d05171f4d0981f01ff168fb8494f663948e4a/src/main/ts/spawn.ts#L220)

**Comment by antongolub** [comment]
Hey @gutenye,

Provide plz more details. I cannot reproduce the issue on [CI or locally](https://github.com/google/zx/pull/941)

**Comment by gutenye** [comment]
Upgrade bun from 1.1.30 to 1.1.34 fixed the issue.
