### ISSUE TITLE
Can't use stdio inherit and sync together

### ISSUE THREAD

**Issue by gutenye** [google/zx#942]
Given below code

```ts
#/usr/bin/env zx

$({ stdio: 'inherit', sync: true })`ls`
```

Output

```
Error: Cannot read properties of null (reading 'length')
```

The error comes from here

![Image](https://github.com/user-attachments/assets/da07247e-8191-41d4-a4bc-1dd8618e57f7)

Expected

works fine

Information

- zx version: 8.2.0
- node version: 20.12.2

**Comment by antongolub** [comment]
Yet another corner case. Thanks!
