### ISSUE TITLE
Array as argument?

### ISSUE THREAD

**Issue by KSXGitHub** [google/zx#96]
## Example

```typescript
declare const files: string[]
await $`git add ${files}`
```

I use TypeScript, I am unaware if the JavaScript version supports arrays, I only know that the TypeScript compiler reports error.

**Comment by antonmedv** [comment]
Js version supports arrays. I'll update the .d.ts file as well. 

What is your workflow with zx & ts?

**Comment by KSXGitHub** [comment]
> What is your workflow with zx & ts?

I don't exactly understand your question. I use TypeScript because it has better IDE experience than plain JavaScript.

**Comment by antonmedv** [comment]
Do you build scripts? How? Webpack? ts-node?

**Comment by KSXGitHub** [comment]
> Do you build scripts? How? Webpack? ts-node?

I currently use `tsc && node ...`.
