### ISSUE TITLE
Document Halt

### ISSUE THREAD

**Issue by lishaduck** [google/zx#961]
EDIT: Halt should get documented so people can know how it exists.

Old description below:

---

Hello! I'm trying to convert some existing code that uses `child_process` to zx. It's working fine, but I want to print out the commands that are run. I know I can enable verbose mode and override the logger, but that isn't as flexible as the logging I need to do. I see zx 8 uses `zurk` under the hood, which has a `buildCmd` function. While that could work, it's not a template tag, so I'd need to manually verify it's actually what zx is running. I'd love an API to create commands without running them (as I think about it, it'd also be useful if xz exposed an exec function to run a command from the proposed builder tag).

- [x] I'd be willing to PR this if this is a direction you're willing to consider.

**Comment by antongolub** [comment]
>  I'd love an API to create commands without running

You can do it right now:
```ts
const p = $({halt: true})`cdm --foo=${foo}`
console.log(f.cmd)
const o = await p.run()
```

**Comment by lishaduck** [comment]
> const p = $({halt: true})`cdm --foo=${foo}`
> console.log(f.cmd)
> const o = await p.run()

Yeah, that looks like what I want! I'd seen halt in intellisense but it isn't documented, so I didn't know what it did.
