### ISSUE TITLE
feat: apply `promisifyStream` to `ProcessPromise` exposed streams

### ISSUE THREAD

**Issue by antongolub** [google/zx#978]
We've [previously added](https://github.com/google/zx/pull/954) stream extensions to make support mixed piping:
```ts
await $`cmd`.pipe(transform).pipe`cmd`
```

Let's also apply the same approach for `ProcessPromise` exposed streams:
```ts
const p1 = $`cmd`

const p2 = p.stdout.pipe`cmd1`
const p3 = p.stderr.pipe`cmd2`
```

See `util.ts#promisifyStream` for details

**Comment by antongolub** [comment]
```js
const p2 = p.pipe.stdout`cmd1`
const p3 = p.pipe.stderr`cmd2`
```

**Comment by antonmedv** [comment]
Why do we need those APIs?

**Comment by antongolub** [comment]
We can redirect error stream to the next piped process via `2>&1`, but not `stdall`.
