### ISSUE TITLE
feat: prepare for jsr.io publishing

### ISSUE THREAD

**Issue by antongolub** [google/zx#980]
[jsr.io](https://jsr.io/) is a special registry for TS packages publishing. Lets add a compatibility test and make it green.

```js
  "scripts": {
    // ...
    "test:jsr": "jsr publish --dry-run",
  },
```

See: 
* https://github.com/webpod/zurk/blob/main/src/scripts/build-jsr.mjs
* https://github.com/webpod/zurk/blob/main/package.json#L59

**Comment by easymikey** [comment]
@###
