### ISSUE TITLE
$`command`: Interactive prompts not processing the inputs

### ISSUE THREAD

**Issue by m-sureshraj** [google/zx#99]
## Expected Behavior
When the provided command prompts for the user input, it should accept entered value after pressing Enter or Return.

## Actual Behavior
It just keeps reading the entered values without respecting end-of-line input.

```
#!/usr/bin/env zx

$`npm init`
```
![Peek 2021-05-20 13-11](https://user-images.githubusercontent.com/12813750/118939472-585d1080-b96d-11eb-86e9-072b40481665.gif)

## Steps to Reproduce the Problem

1. Just pass an interactive command to the $`` 
```
$`npm init`
```
2. Try to fill it

This behavior could be due to not redirecting the parent process `stdin` to the spawned process `stdin`. I tried the same command with the `spawn`, and it worked fine. 

```
#! /usr/bin/env node
const { spawn } = require('child_process');

spawn('npm', ['init'], { stdio: 'inherit' });
```

## Specifications

- Version: 1.8.0
- Platform: Ubuntu 20.04.2 LTS

**Comment by antonmedv** [comment]
Fixed!

**Comment by m-sureshraj** [comment]
Commit - https://github.com/google/zx/commit/1064e6454c0253424dabf5e133080808ea547346

**Comment by hungdoansy** [comment]
I'm still having this issue at 7.0.8. 

```js
#!/usr/bin/env zx
process.stdin.isTTY = true
await $`echo "Name (with spaces): "`
const rawName = JSON.parse(await stdin())
await $`echo "${rawName.replaceAll(/\s+/, "-")}"`
```
