### ISSUE TITLE
Running a .mjs-script through symlink with early exit creates copy of the script

### ISSUE THREAD

**Issue by ath88** [google/zx#993]
To follow up on #579 - I don't know why it was considered completed, as there is no resolution mentioned in the issue.

I still experience this issue with zx 8.2.4.

To replicate, make a file called `test.mjs` with one line:
```
process.exit();
```
.. then make a symlink to the file with `ln test.mjs test`, and run with `zx test`.

You'll start seeing a copy of `test.mjs` for every execution, showing up in the directory with names like:
- `test-zz5yo0hugt.mjs`
- `test-ysdh5sy58g.mjs`

**Comment by ath88** [comment]
After some digging, I notice that its a combination of a few pieces of code. Namely these:

- https://github.com/google/zx/blob/8.2.4/src/cli.ts#L186
```js
  if (ext === '') {
    const tmpFilename = fs.existsSync(`${filepath}.mjs`)
      ? `${base}-${randomId()}.mjs`
      : `${base}.mjs`

    return writeAndImport(
      await fs.readFile(filepath),
      path.join(dir, tmpFilename),
      origin
    )
  }
```
Here - if there is no extension, we make a copy, now with an extension, and with a random ID in my case, to avoid collisions.

- https://github.com/google/zx/blob/8.2.4/src/cli.ts#L168
```js
export async function writeAndImport(
  script: string | Buffer,
  filepath: string,
  origin = filepath
) {
  await fs.writeFile(filepath, script.toString())
  try {
    await importPath(filepath, origin)
  } finally {
    await fs.rm(filepath)
  }
}
```
Here - we write the new filename, and once we have executed the script, we remove the file again with a `finally` block.

- https://github.com/google/zx/blob/8.2.4/src/cli.ts#L209
```js
  await import(url.pathToFileURL(filepath).toString())
```
Here there actual execution happens. Though - if this executes a `process.exit()` we never reach the `finally` block and the temporary file is never deleted.

A fix - in my case - could be to execute the file without the extension, which works just fine. Removing the first block of code above does it. I don't know why the block was added in the first place - I don't see any comments or information in the git commit message.

However - there is still an issue with `.md` files executing `process.exit()`. Also - should a `finally` block be added elsewhere, this will still not be executed.

Another solution would be to execute the script in another thread, so we avoid having `process.exit()` terminate the parent process. I bet there will be another host of issues cropping up by doing this.

Feedback will be appreciated. :)

**Comment by antongolub** [comment]
_\* Thinking about replacing `randomId` with some sort of file hash..._

**Comment by antongolub** [comment]
@ath88,

Check this out: [v8.2.4-dev.c8ca866](https://www.npmjs.com/package/zx/v/8.2.4-dev.c8ca866)

**Comment by ath88** [comment]
> [@ath88](https://github.com/ath88),
> 
> Check this out: [v8.2.4-dev.c8ca866](https://www.npmjs.com/package/zx/v/8.2.4-dev.c8ca866)

Works as intended. :) Thanks!
