### ISSUE TITLE
feat: add recommended node.js version for development

### ISSUE THREAD

**Issue by easymikey** [google/zx#995]
There is an engines field in the json package. But to make it easier to install and find versions, I wanted to suggest adding  [Volta](https://volta.sh/)

**Comment by easymikey** [comment]
There is no such possibility directly.
I would suggest going the following: create .nvmrc file, add a script to install versions from volta or nvm and update contrubuting docs or may before run before npm install script.

Volta get version from nvmrc:
```bash
volta install node@$(cat .nvmrc)
```

All script.
```bash
#!/bin/bash

if command -v volta &> /dev/null
then
    volta install node@$(cat .nvmrc)
elif command -v nvm &> /dev/null
then
      nvm use
else
    echo "Volta or nvm is not installed."
fi
```

**Comment by antongolub** [comment]
And I wouldn't mind adding several package.json fields for each tool, but it definitely requires #1003 to be implemented

**Comment by easymikey** [comment]
I cants take #1003 if it can be implemented within a week.

**Comment by easymikey** [comment]
Which should I install for development? Last lts or another?

**Comment by easymikey** [comment]
I suggest to add install.sh script and add it to preinstall. But this solution will lead to the addition of env file in CI to script running this script.

what do you think? @antongolub  

PS.  I have not found a solution to install node version when opening a project

```
#!/bin/bash

# Check if RUN_ON_CI is true and exit early
if [ "$RUN_ON_CI" == "true" ]; then
    exit 0
fi

echo "installing Node.js version manager\n"
if command -v fnm &> /dev/null
then
    echo "Installing Fnm\n"
    fnm install  --resolve-engines=false
    echo "\nFnm installed successfully"
elif command -v volta &> /dev/null
then
    echo "Installing Volta\n"
    volta install node@$(cat .nvmrc)
    echo "\nVolta installed successfully"
elif command -v nvm &> /dev/null
then
    echo "Installing NVM\n"
    nvm use
    echo "\nNVM installed successfully"
else
    echo "Volta or nvm is not installed."
fi
```

**Comment by antongolub** [comment]
I suggest using `.node_version` file
https://stackoverflow.com/questions/27425852/what-uses-respects-the-node-version-file

**Comment by easymikey** [comment]
> I suggest using `.node_version` file
> https://stackoverflow.com/questions/27425852/what-uses-respects-the-node-version-file

No problem replace to `.node_version`, but what do you think about using preinstall script and update github ci?

**Comment by antongolub** [comment]
> using preinstall script and update github ci

Let's just dont. CI uses `actions/setup-node` to set the target version explicitly.

**Comment by easymikey** [comment]
And is it worth choosing several popular utilities and reflecting them in the script and contributing docs?

**Comment by easymikey** [comment]
> Let's just dont. CI uses actions/setup-node to set the target version explicitly.

Did I understand correctly, you're suggesting to add a `.node_version` file and updating docs?

**Comment by easymikey** [comment]
@antongolub what do you think about adding `.node_version` file with last node lts version (node@22) ?
